oktadeveloper/okta.github.io

- _source/_posts/2017-10-11-why-are-webhooks-better-than-serverless-extensibility.md
> Adding new post on webhooks.

- _source/_posts/2017-10-10-developers-guide-to-docker-part-3.md
- _source/_posts/2017-10-11-developers-guide-to-docker-part-3.md
Fixed the "Docker part 3" post show it doesn't show up twice in the blog
> Remove article stub

- _source/_posts/2017-10-13-okta-groups-spring-security.md
Minor tweaks, Javascript > JavaScript + a few more
> Minor tweaks, Javascript > JavaScript + a few more

- _source/_docs/api/resources/system_log.md
Fixed a few small errors
- **Fixed outdated event fields (1)**
Before:
After:
- **Fixed outdated event fields (2)**
Before:
After:
* [OKTA-140769](https://oktainc.atlassian.net/browse/OKTA-140769)
* @ryanoblak-okta 
* @mystiberry-okta
> Fix typos and outdated examples

- _source/_posts/2017-10-17-add-the-power-of-webhooks-to-your-app-with-oktas-system-log.md
> Fix incorrect example

- _source/_code/angular/okta_angular_sign-in_widget.md
- Updates Sign-In widget quickstart for new `@okta/okta-angular` SDK
* [OKTA-144772](https://oktainc.atlassian.net/browse/OKTA-144772)
> Updates Widget + Angular quickstart

- _source/_posts/2017-10-20-oidc-with-jhipster.md
> Heroku > Cloud Foundry

- _source/quickstart/php/generic-auth-code.md
- Fix variables inside of the code samples because of some Jekyll tomfoolery
* [OKTA-143768](https://oktainc.atlassian.net/browse/OKTA-143768)
> Updates property values for jekyll issues

- _source/_posts/2017-10-19-build-a-preact-app-with-authentication.md
- title was set to "Built Preact..." changed to "Build Preact..."
cc @jmelberg-okta
> Fixed post title

- _source/_docs/api/getting_started/design_principles.md
- Great suggestion from Chris Barry to clarify the fall through on RL buckets.
* https://github.com/okta/okta.github.io/pull/1398
> clarify rl buckets

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-42.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN for 2017-43
[OKTA-142440](https://oktainc.atlassian.net/browse/OKTA-142440)
> rn for 2017-43

- _source/_docs/platform-release-notes/platform-release-notes.md
> Rn previewfix 43

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-42.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- Feature work for 2017.43 being pushed to source. This week, that's just RN.
[OKTA-146368](https://oktainc.atlassian.net/browse/OKTA-146368)
> rn for 2017-43 (#1410)

- _source/_docs/platform-release-notes/platform-release-notes.md
- excerpt too long
Somehow my last commit didn't get pushed from weekly to source. I know it's in remote weekly because it's in staging.
> hotfix: fix excerpt length

- tests/selenium/framework/page-objects/QuickStartsPage.js
- tests/selenium/spec/blog-page-spec.js
- tests/selenium/spec/check-imported-docs-spec.js
- tests/selenium/spec/quickstarts-spec.js
- Quick start page tests are enabled
- Also enabled a blog-page and doc test
- 2 quick start tests still disabled due to https://oktainc.atlassian.net/browse/OKTA-146417
* [OKTA-146417](https://oktainc.atlassian.net/browse/OKTA-146417)
> Enabled the quick-start tests

- _source/_authentication-guide/auth-overview/index.md
- _source/_authentication-guide/implementing-authentication/set-up-authz-server.md
- _source/_authentication-guide/saml-login/index.md
- Isolating updates to Overview section. Needed to clarify what the Authentication API does and when to use it.
- A few misc changes as well.
> Auth guide overview update

- scripts/helpers.sh
- scripts/travis.sh
> Adding section folding to travis log

- _source/_posts/2017-10-27-okta-oauth-zork.md
- Update Zork post per @lindsaybrunner-okta
> Quick edits from @linds

- _source/_docs/api/resources/users.md
- doc for nextLogin
[OKTA-142029](https://oktainc.atlassian.net/browse/OKTA-142029)
> new query param for create user

- _source/feed-full.xml
This will render *all* articles on the blog. This is needed to do some
upcoming updates with social media automation.
> Adding a full RSS feed.

- _source/feed-full.xml
- tests/selenium/framework/page-objects/QuickStartsPage.js
- :bug: Fixes **headless Chrome** quickstart tests running in Travis
> :bug: Fixes quickstart test links not loading in time

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-43.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN for 2017.44, includes 2017.43
* [OKTA-146921](https://oktainc.atlassian.net/browse/OKTA-146921)
> first draft rn for 2017.44

- _source/_docs/api/resources/users.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-43.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- Push doc changes to source from weekly for 2017.44
* [OKTA-146921](https://oktainc.atlassian.net/browse/OKTA-146921)
> Release 2017 44

- _source/_assets/js/docs.js
Originally #1259
Rebased on source, original branch here: 92937-tr-toc-scroll-position-org
Resolves: #1338
> 97529 he social links

- _source/quickstart/angular/default-example.md
- :bug: Adds a line of code in link the `router out` used by `@okta/okta-angular`
> :bug: Adds missing angular quickstart outlet

- _source/_docs/api/getting_started/design_principles.md
- /users/userid rl 600 to 2000
[OKTA-144705](https://oktainc.atlassian.net/browse/OKTA-144705)
> users userid rl 600 to 2000

- _source/_docs/api/resources/apps.md
- change max length of label from 50 to 100
[OKTA-146865](https://oktainc.atlassian.net/browse/OKTA-146865)
> change max label to 100 from 50

- _source/_docs/api/getting_started/design_principles.md
- Developer added info.
[OKTA-144705](https://oktainc.atlassian.net/browse/OKTA-144705)
> Dok 144705

- _source/_docs/api/resources/users.md
First draft of Grant API doc
- Grant API
[OKTA-134810](https://oktainc.atlassian.net/browse/OKTA-134810)
> Second draft of Grant API

- _source/_docs/api/resources/users.md
- Fixing a typo in source.
[OKTA-127550](https://oktainc.atlassian.net/browse/OKTA-127550)
> change federated to federation

- _source/_docs/api/resources/idps.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-44.md
- Title says it all.
* [OKTA-147915](https://oktainc.atlassian.net/browse/OKTA-147915)
> Release Notes 2017.45

- _source/_docs/api/getting_started/design_principles.md
- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/idps.md
- _source/_docs/api/resources/oauth-clients.md
- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/users.md
- _source/_docs/api/resources/zones.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-44.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
* users userid rl 600 to 2000
* consent beta doc that is not user grants (#1426)
* Second draft of Grant API (#1415)
* resolved conflict from unrelated change for nextLogin parameter
* last major draft
* Release Notes for 2017.45 (#1468)
* Fix filter documentation for /api/v1/zones (#1465)
* [OKTA-147915](https://oktainc.atlassian.net/browse/OKTA-147915)
> Release 2017.45

- _source/_docs/sdk/scim/javadoc/readme.md
- package.json
- scripts/publish.sh
- Cleans up long build scripts in `package.json` by including `pre` and `post` + utility scripts 
Resolves: [OKTA-125222](https://oktainc.atlassian.net/browse/OKTA-125222)
> :art: Updates package.json structure

- _source/_standards/SCIM/index.md
- Fix link to on-premise provisioning guide from d.o.c. Not related to feature work. Tested in localhost.
[OKTA-147438](https://oktainc.atlassian.net/browse/OKTA-147438)
> fix link to on-premise provisioning

- _source/_docs/api/resources/apps.md
> Corrected OIDC apps api example

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-45.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
> Release Notes for 2017.46

- _source/_docs/api/resources/apps.md
- add missing properties to swa 3 field 
[OKTA-147418](https://oktainc.atlassian.net/browse/OKTA-147418)
> update swa 3 app

- _source/_docs/api/resources/users.md
- tests/selenium/framework/page-objects/BlogPage.js
- Updates to user consent doc.
[OKTA-148041](https://oktainc.atlassian.net/browse/OKTA-148041)
> first draft: user consent doc tweaks

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-45.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- Release 2017.46, which is really just some release notes. 
* [OKTA-148750](https://oktainc.atlassian.net/browse/OKTA-148750)
> Release Notes for 2017.46 (#1480)

- _source/_standards/SCIM/index.md
- _source/_use_cases/integrate_with_okta/sso-with-saml.md
> Okta App Network -> Integration Network

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-46.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN 2017.47
[OKTA-149555](https://oktainc.atlassian.net/browse/OKTA-149555)
> RN 2017.47

- _source/_layouts/redirect.html
- redirect_from fails our html proofer
> Fix redirect template

- _source/_docs/api/resources/apps.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-46.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
change max label to 100 from 50 (#1458)
Dok 144705 (#1462)
* users userid rl 600 to 2000
* developer added info
consent beta doc that is not user grants (#1426)
* first draft consent beta
* 2nd draft
* 3rd draft comments
* more edits
* fix link
RN 2017.47 (#1495)
RN for 2017.47
RN Draft
- Pushing 2017.47 weekly changes to source
> Push release 2017.47 to website

- _source/_docs/api/resources/apps.md
- Fixing typo (comma missing after first in list, incorrectly placed with last in list).
* [OKTA-149555](https://oktainc.atlassian.net/browse/OKTA-149555)
> fix comma typo

- _source/_code/ios/quickstart-appauth-swift.md
- _source/_reference/okta_expression_language/index.md
- _source/quickstart/android/default-example.md
- _source/quickstart/ios/default-example.md
> Fixing minor typos

- _source/_posts/2015-12-02-tls-client-authentication-for-services.md
> Fix broken link

- _source/_posts/2017-11-22-three-developer-tools-im-thankful-for.md
@jmelberg-okta would you mind merging this as well when you get a moment? <3
> I was a jerk.

- _source/quickstart/react/default-example.md
- These were issues that were causing confusion
* https://github.com/okta/okta-oidc-js/issues/52
* https://github.com/okta/okta-oidc-js/issues/43
> Fix issues in React guide

- _source/_posts/2017-03-27-angular-okta-sign-in-widget.md
Update "Angular + Sign-In Widget" blog post to use Angular 5 and Okta Sign-In Widget 2.5.0.
> Update "Angular + Sign-In Widget" blog post to use Angular 5

- _source/feed-edgar.xml
This generates RSS articles with tweets embedded in them! This is used by our social media monitoring tool (meet edgar) to help automate some of our articles.
With this change, any "tweets" in markdown metadata will be used to create actual tweets for us =)
> Adding a new RSS feed: `feed-edgar.xml`.

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-47.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN for 48+49
[OKTA-151074](https://oktainc.atlassian.net/browse/OKTA-151074)
> RN 2017-49 first draft

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- Request param `request` for passing JWT
[OKTA-78476](https://oktainc.atlassian.net/browse/OKTA-78476)
> add request param for jwt

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- Nate, Sohaib, and Reman requested a few more changes and asked Fed to review.
[OKTA-151774](https://oktainc.atlassian.net/browse/OKTA-151774)
> requested changes to logout endpoint

- _config.yml
- _source/_3rd_party_notices/index.html
- _source/_code/angular/index.md
- _source/_code/angular/okta_angular_auth_js.md
- _source/_code/angular/okta_angular_sign-in_widget.md
- _source/_code/dotnet/index.md
- _source/_code/ios/quickstart-appauth-swift.md
- _source/_code/java/index.md
- _source/_code/php/index.md
- _source/_code/python/index.md
- _source/_code/react/index.md
- _source/_code/react/okta_react.md
- _source/_code/react/okta_react_sign-in_widget.md
- _source/_includes/sidebar.html
- tests/selenium/spec/side-bar-spec.js
- Updates navigation paths to use pretty URL format.
> https://developer.okta.com/code/java
**Note**: You can still access the `index` page or the `.html` page.
* [OKTA-152088](https://oktainc.atlassian.net/browse/OKTA-152088)
* Linked to [OKTA-147264](https://oktainc.atlassian.net/browse/OKTA-147264)
> :art: Pretty URLs

- _source/_docs/api/resources/users.md
- Add strict param for admin change password endpoints
* [OKTA-151502](https://oktainc.atlassian.net/browse/OKTA-151502)
> Docs for OKTA-151502: Add docs for strict param on admin change password endpoints.

- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
Fully documents Logs API query parameters in preparation for EA.
* [OKTA-149608](https://oktainc.atlassian.net/browse/OKTA-149608)
> OKTA-149608: Fully documents Logs API query parameters.

- _source/_docs/api/resources/oauth2.md
- _source/_docs/platform-release-notes/platform-release-notes2016-43.md
- We missed a few yourOktaDomains, and one is a special case, we wanted the domain westworld.
[OKTA-149754](https://oktainc.atlassian.net/browse/OKTA-149754)
> missed a few yourOktaDomains

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-49.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
> Release notes for 2017.50

- _source/_docs/api/resources/apps.md
> Fixed a typo

- _source/_posts/2017-04-26-bootiful-development-with-spring-boot-and-angular.md
- _source/_posts/2017-12-06-bootiful-development-with-spring-boot-and-react.md
Minor improvements to blog posts
> Minor improvements to blog posts

- _source/_posts/2017-08-08-secure-spring-microservices.md
- _source/_posts/2017-10-17-add-the-power-of-webhooks-to-your-app-with-oktas-system-log.md
- _source/_posts/2017-10-19-build-a-preact-app-with-authentication.md
- _source/_posts/2017-10-19-use-openid-connect-to-build-a-simple-node-website.md
Fixing a number of small typos/goofs I found while reviewing blog posts.
> Fixing typos

- _source/_posts/2017-10-19-build-a-preact-app-with-authentication.md
* IMO, we no longer need to say that the Platform choices include OpenID Connect, because it is implied in the new dev console.
* The proper terminology is [Higher-Order Components](https://reactjs.org/docs/higher-order-components.html).
> Minor edits to Preact blog post

- _source/_authentication-guide/tokens/validating-access-tokens.md
- _source/_authentication-guide/tokens/validating-id-tokens.md
- _source/_posts/2017-10-19-use-openid-connect-to-build-a-simple-node-website.md
- Fixing links into oidc-js repo to be deep links
- Plus trailing whitespace removal
> Fixing links into oidc-js repo to be deep links

- _source/_docs/api/resources/idps.md
- Explain in doc what social login tokens are for (object & endpoint)
[OKTA-125134](https://oktainc.atlassian.net/browse/OKTA-125134)
> what are social login tokens for

- _source/_docs/api/resources/idps.md
- Adding the endpoint to get a user by idp/user ID
[OKTA-85733](https://oktainc.atlassian.net/browse/OKTA-85733)
> first draft add missing endpoint idps

- _source/_authentication-guide/tokens/refreshing-tokens.md
Fixed a typo and formatted an example to be readable without scrolling.
> Improve Auth Guide Refresh Token topic

- _source/_code/dotnet/jwt-validation.md
> Consistent emphasis

- _source/_code/dotnet/index.md
Link to both ASP.NET 4.x and ASP.NET Core examples
> Update ASP.NET links

- _source/quickstart-fragments/dotnet/aspnetcore-auth-code.md
Updates the ASP.NET Core quickstart to be more consistent with #1578
> Update ASP.NET Core code flow quickstart for consistency

- _source/_docs/how-to/creating-token-with-groups-claim.md
> Updates formatting

- _source/_standards/SCIM/index.md
- We missed one Okta Application Network that should be Okta Integration Network. 
No JIRA. This is literally a one-word change requested by the team.
> one word change

- _source/_posts/2017-04-17-angular-authentication-with-oidc.md
- _source/conductor.yml
- scripts/helpers.sh
- scripts/publish.sh
- scripts/setup.sh
These changes:
- Generate conductor file by looking at all index.html's to setup redirections
- Adds a postpublish script to remove .html extension from all files
- Sends promotion messages for conductor that will trigger automatic deployments
[OKTA-152047](https://oktainc.atlassian.net/browse/OKTA-152047)
[OKTA-147564](https://oktainc.atlassian.net/browse/OKTA-147564)
@jmelberg-okta @robertdamphousse-okta @rchild-okta @bdemers @jtodd-okta @jonhohle-okta
> Conductor integration

- _source/quickstart-fragments/dotnet/aspnet4-auth-code.md
- _source/quickstart-fragments/dotnet/aspnet4-implicit.md
- _source/quickstart-fragments/dotnet/aspnetcore-auth-code.md
- _source/quickstart-fragments/dotnet/aspnetcore-implicit.md
- tests/selenium/framework/page-objects/QuickStartsPage.js
No more "coming soon" for ASP.NET 4.x! 🎉
> Add ASP.NET 4.x code flow quickstart

- _source/_includes/sidebar.html
- _source/_reference/api_reference.md
- _source/_reference/authentication_reference.md
- _source/_reference/error_codes/index.md
- _source/_reference/getting_started.md
- _source/_reference/okta_expression_language/index.md
- tests/selenium/framework/page-objects/SideBarPage.js
> Updates TOC and excerpts

- _source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md
Fix project name as reported on the developer blog: http://disq.us/p/1p4ets1
> Fix typo in Angular CRUD blog post

- _source/quickstart-fragments/nodejs/express-auth-code.md
- _source/quickstart-fragments/nodejs/express-implicit.md
- _source/quickstart-fragments/nodejs/generic-implicit.md
- _source/quickstart-fragments/okta-sign-in-page/default-example.md
- _source/quickstart-fragments/react/default-example.md
Adding links to samples from quickstarts. Angular coming soon after sec review of new repo
> Add links to sample applications for Express, React

- _source/_use_cases/api_access_management/index.md
Most of these are small typo fixes, etc. Comments inline.
@mystiberry-okta Feel free to incorporate some or none of these fixes. Cheers!
> Suggestions for improving API AM best practices

- _source/_change-log/2018-02.md
- API change log for 2018.01+02
- We think these bogus commits (historical commits, no file changes) are going to keep accumulating as long as we use merge, so we may need to discuss.
[OKTA-154526](https://oktainc.atlassian.net/browse/OKTA-154526)
> Rn 2018 02

- _source/_docs/api/resources/schemas.md
Make the AppUser schema API GA
This also includes the support for enum and oneOf.  Also remove EA tag for the schema API in general.
* [OKTA-150657](https://oktainc.atlassian.net/browse/OKTA-150657)
> Make the AppUser schema API GA

- _source/_docs/api/resources/users.md
- Docs for Email Operations APIs (Beta)
- Two questions 
1. There doesn't seem a good pattern to document "Errors". I've used my intuition, but let me know if you think it should be formatted differently.
2. The object model is included within the section where operations are listed. As an example, the (unrelated) pre-existing "Clients Grant" lists the model with the "User" model. However, that seems confusing and misleading since the object is not a part of the "User" model. The new Email object model I have added is kept close to the actual operations, but let me know if there is any pattern to follow here.
- Old PR with some comments in https://github.com/okta/okta.github.io/pull/1599
* [OKTA-153174](https://oktainc.atlassian.net/browse/OKTA-153174)
> Docs for Email Operations APIs (Beta)

- _source/_posts/2018-01-11-two-approaches-to-setting-up-a-mern-stack-app.md
- Blog post on setting up a MERN stack app.
> Two Approaches to MERN Stack App Post

- _source/_posts/2018-01-11-two-approaches-to-setting-up-a-mern-stack-app.md
> Added tweets

- _source/_assets/js/quickstart.js
- _source/quickstart-fragments/vue/default-example.md
- tests/selenium/framework/page-objects/QuickStartsPage.js
- tests/selenium/spec/quickstarts-spec.js
- :seedling: Adds Vue.js quickstart
> This will fail tests until [this PR](https://github.com/okta/okta-oidc-js/pull/76) is merged into `master`
* [OKTA-153617](https://oktainc.atlassian.net/browse/OKTA-153617)
> Adds Vue.js quickstart

- _source/_code/angular/okta_angular_auth_js.md
- _source/_posts/2017-05-17-develop-a-mobile-app-with-ionic-and-spring-boot.md
- _source/_posts/2017-08-22-build-an-ionic-app-with-user-authentication.md
- Add link from Ionic + Spring Boot to this post
- Fix import syntax for Auth SDK
> Update Ionic User Authentication post

- _source/_docs/api/getting_started/design_principles.md
- We need more info about what headers to always include.
[OKTA-92271](https://oktainc.atlassian.net/browse/OKTA-92271)
> beef up header doc

- _source/_posts/2017-06-15-build-microservices-architecture-spring-boot.md
> Update article with latest client code from spring-boot-angular-pwa-example

- .travis.yml
> Removes caching in travis

- .travis.yml
> :fire: Stop Travis from removing our generated site

- .travis.yml
- scripts/post-build-prod.sh
> Copy over .git to get: Ignoring /dist

- _source/feed-edgar.xml
The old merge got removed somehow with travis issues and people changing
stuff =/
> Getting rid of Edgar feed (again).

- _source/_posts/2017-03-27-angular-okta-sign-in-widget.md
Updates https://github.com/oktadeveloper/okta-angular-sign-in-widget-example so it works w/o issues.
> Update Angular + Sign-In Widget blog post to fix hanging on sign-in

- _source/_change-log/2018-02.md
- _source/_change-log/2018-03.md
- As title says.
* [OKTA-155211](https://oktainc.atlassian.net/browse/OKTA-155211)
> Release notes for 2018.03

- _source/_docs/api/resources/authorization-servers.md
- Adding `metadataPublish` to Scope object
* [OKTA-106548](https://oktainc.atlassian.net/browse/OKTA-106548)
> Scope operations metadata publish

- _source/_change-log/index.md
- Per executive request, returning the "are you looking for Product RN?" blurb to change log. It was removed during the restructure last month.
[OKTA-156104](https://oktainc.atlassian.net/browse/OKTA-156104)
> return the non-api RN blurb

- _source/_use_cases/integrate_with_okta/index.md
- _source/_use_cases/sso_and_provisioning/draft.md
- _source/_use_cases/users_groups_applications/draft.md
- _source/_use_cases/web_development/draft.md
- _source/documentation/stormpath-import.md
- Removed files that have been around for > 1 year w/o updates or page views
> :fire: Removes dead pages

- _source/quickstart-fragments/okta-sign-in-page/default-example.md
- Adds prerequisite section to Okta Hosted Login quickstart
* [OKTA-155488](https://oktainc.atlassian.net/browse/OKTA-155488)
> Adds prereq section for Okta Hosted Login

- _source/_assets/css/okta/icons/_classes.scss
- _source/_assets/js/quickstart.js
> Add background color to icons

- _source/_docs/api/resources/templates.md
- Adding missing information and cleaning up SMS templates section.
* [OKTA-156656](https://oktainc.atlassian.net/browse/OKTA-156656)
> SMS template improvements

- _source/_docs/api/resources/oauth2.md
- Add `metadataPublish` property on scopes to doc.
[OKTA-106548](https://oktainc.atlassian.net/browse/OKTA-106548)
> add metadataPublish to docs

- _source/_reference/okta_expression_language/index.md
- Doc for Group. functions that let you create a dynaimc whitelist for groups claims
[OKTA-156622](https://oktainc.atlassian.net/browse/OKTA-156622)
> dynamic white list doc

- _source/_posts/2018-01-31-build-secure-todo-app-vuejs-aspnetcore.md
- Fix `localhost` links that weren't caught by external PR #1682
> :bug: Fix localhost links

- _source/_change-log/2018-05.md
- Request to clarify a bug fix item. Just text, no links
[OKTA-156826](https://oktainc.atlassian.net/browse/OKTA-156826)
> add explanatory phrase to mfa bug fix

- _source/_docs/api/getting_started/rate-limits.md
- _source/_docs/api/resources/system_log.md
- _source/_docs/api/resources/trusted-origins.md
- Update broken internal links that contain `.html`
> Update broken internal links

- scripts/travis.sh
- Updates Travis Script to differ between `source` and `weekly` PRs.
> Update Travis CI tests to perform separate tests on weekly

- _source/_posts/2017-03-21-spring-boot-oauth.md
> Update Spring OAuth post to fix bug and add more to application.yml

- _source/_authentication-guide/implementing-authentication/set-up-authz-server.md
- _source/_authentication-guide/social-login/index.md
- _source/_authentication-guide/social-login/social-settings.md
- _source/_docs/api/resources/policy.md
- Various minor doc fixes, with details in specific JIRA tickets.
- Also removed various instances of trailing whitespace, so add a `?w=1` to this PR to see the stuff that's _actually_ changed.
* [OKTA-123541](https://oktainc.atlassian.net/browse/OKTA-123541)
* [OKTA-154908](https://oktainc.atlassian.net/browse/OKTA-154908) / #1594 
* [OKTA-152871](https://oktainc.atlassian.net/browse/OKTA-152871)
> Jv various doc bugs

- _source/_posts/2017-03-21-spring-boot-oauth.md
https://www.youtube.com/watch?v=TaZqDrwBWwA
> Update screencast for Get Started with Spring Boot, OAuth 2.0, and Okta

- _source/_includes/head.html
I fixed some SEO stuff we sorely needed to handle:
- Make meta description legit
- Make swiftype search legit
- Remove bad canonical linkage
> Fix Some SEO Stuffz

- _source/_posts/2017-08-08-secure-spring-microservices.md
https://developer.okta.com/blog/2017/08/08/secure-spring-microservices
> Fix markdown for sub-lists in Spring Microservices blog post

- _source/_change-log/2018-06.md
- _source/_docs/api/resources/oauth2.md
- _source/_docs/how-to/beta-auth-service/api-access-management-troubleshooting.md
- _source/_standards/OAuth/index.md
- _source/_use_cases/api_access_management/index.md
- RN for 2018-06 and removing EA tags for api am
[OKTA-157805](https://oktainc.atlassian.net/browse/OKTA-157805)
> RN for 2018-06 and removing EA tags

- _source/_change-log/2018-05.md
- Update to RN to go with production release, partner of PR 1696
follow on, no JIRA.
> rn bug fix to go with prod

- _source/_posts/2017-08-17-why-jwts-suck-as-session-tokens.md
- _source/_posts/2017-08-29-meet-the-new-okta-identity-platform.md
- _source/_posts/2017-09-06-build-a-cryptocurrency-comparison-site-with-vuejs.md
- _source/_posts/2017-10-11-why-are-webhooks-better-than-serverless-extensibility.md
- _source/_posts/2017-10-19-use-openid-connect-to-build-a-simple-node-website.md
- _source/_posts/2017-11-22-three-developer-tools-im-thankful-for.md
Adding meta descriptions to all my old blog posts.
> Updating meta description tags on all my blog posts.

- _source/_docs/api/resources/oidc.md
> Fixing stuff

- _source/_docs/api/resources/oidc.md
- Fixes a few issues with markdown tables
- Adds some clarity on duplicate query params in OIDC
> Fix a few OIDC formatting issues

- _source/_docs/api/resources/system_log.md
- Clearer AuthenticationContext docs.
* [OKTA-156281](https://oktainc.atlassian.net/browse/OKTA-156281)
> OKTA-156281: Detail AuthenticationContext Object

- _source/_docs/api/resources/system_log.md
* [OKTA-156279](https://oktainc.atlassian.net/browse/OKTA-156279)
> OKTA-156279: Detail Logs Transaction Object

- .travis.yml
- Setup alerting on failed merges.
> :seedling: Adds travis notifications

- _source/_docs/api/resources/schemas.md
- This PR updates the data object in the sample code for Add Property to User Profile Schema
* [OKTA-158834](https://oktainc.atlassian.net/browse/OKTA-158834)
> Update Schemas data for Add Property to User Profile Schema

- _source/_docs/api/resources/system_log.md
* [OKTA-156280](https://oktainc.atlassian.net/browse/OKTA-156280)
> Detail DebugContext Object

- _source/_docs/api/getting_started/rate-limits.md
- Improvements to rate limit doc.
[OKTA-155960](https://oktainc.atlassian.net/browse/OKTA-155960)
> rate limit doc improvement

- _source/_docs/api/resources/authn.md
* [OKTA-155563](https://oktainc.atlassian.net/browse/OKTA-155563)
> Okta 155563 kqs doc fixup

- _source/_posts/2017-08-22-build-an-ionic-app-with-user-authentication.md
- _source/_posts/2017-11-20-build-an-iOS-app-with-secure-authentication-in-20-minutes.md
- Both of these links have broken more than once in the last six months. Removing them seems like the best option.
> Removed broken links

- _source/_authentication-guide/saml-login/index.md
- Added the list of supported algorithms for inbound SAML, and simplified the topic so it's an easy-to-scan task. 
[OKTA-159198](https://oktainc.atlassian.net/browse/OKTA-159198)
> adding algo info and cleaning up for standards

- _source/_change-log/2017-52.md
- _source/_change-log/2018-02.md
- _source/_change-log/2018-03.md
- _source/_change-log/2018-05.md
- _source/_change-log/2018-06.md
- _source/_change-log/2018-07.md
- New changelog entry for 2018.07 release.
- Also removed page titles from 2018 posts, since they're not visible in the new one-page view.
- Also fixed some errant whitespacing issues on other pages.
> Change Log for 2018.07

- _source/_docs/api/resources/system_log.md
Update documentation for the Issuer object.
Bacon: test
Resolves: OKTA-156282
* [OKTA-124190](https://oktainc.atlassian.net/browse/OKTA-156282)
> Update Docs for Issuer Object

- _source/_change-log/2018-07.md
> Making links relative

- _source/_posts/2017-05-17-develop-a-mobile-app-with-ionic-and-spring-boot.md
- _source/_posts/2017-08-22-build-an-ionic-app-with-user-authentication.md
- _source/_posts/2018-02-15-build-crud-app-vuejs-node.md
Added README with instructions to run the app at https://github.com/oktadeveloper/okta-vue-node-example.
> Add link to GitHub repo to Vue.js CRUD post

- _source/_posts/2018-02-20-9-talks-i-cant-wait-to-see-at-iterate.md
- Blog post for 9 Talks I Can't Wait To See At Iterate
> 9 Talks I Can't Wait To See At Iterate Post

- scripts/gh-pages-publish.sh
This is needed to purge this file from master
> Remove cached stormpath migration docs

- _source/_change-log/2017-11.md
> Remove link to elm sample

- scripts/gh-pages-publish.sh
Reverts okta/okta.github.io#1791
> Revert "Remove cached stormpath migration docs"

- _source/_docs/api/resources/system_log.md
- Creates a new section in the syslog docs that describes the relationships between the various ID fields.
* [OKTA-127979](https://oktainc.atlassian.net/browse/OKTA-127979)
> Syslog2: Event ID Correlation

- _source/_change-log/2016-27.md
- _source/_change-log/2016-30.md
- _source/_change-log/2017-03.md
- _source/_change-log/2017-04.md
- _source/_change-log/2017-05.md
- _source/_change-log/2017-09.md
- _source/_change-log/2017-10.md
- _source/_change-log/2017-11.md
- _source/_change-log/2017-12.md
- _source/_change-log/2017-15.md
- _source/_change-log/2017-16.md
- _source/_change-log/2017-17.md
- _source/_change-log/2017-18.md
- _source/_change-log/2017-19.md
- _source/_change-log/2017-20.md
- _source/_change-log/2017-21.md
- _source/_change-log/2017-22.md
- _source/_change-log/2017-23.md
- _source/_change-log/2017-24.md
- _source/_change-log/2017-25.md
- _source/_docs/api/resources/schemas.md
- _source/_docs/api/resources/system_log.md
- _source/_docs/api/resources/users.md
- _source/_use_cases/integrate_with_okta/oan-faqs.md
- Sync `weekly` with `source`
- **To be MERGED** not *squashed*
> Sync weekly

- _source/_posts/2018-02-27-a-breakdown-of-malcolm-and-what-you-need-to-know.md
- _source/_posts/2018-02-27-a-breakdown-of-the-new-saml-authentication-bypass-vulnerability.md
> SAML Vulnerability Blog Post

- _source/_posts/2018-03-01-develop-microservices-jhipster-oauth.md
> Fix missing link in latest blog post

- _source/_change-log/2018-09.md
- Per Operations, reverting OKTA-155752 requires reverting one change log item. No other doc affected AFAIK.
[OKTA-160927](https://oktainc.atlassian.net/browse/OKTA-160927)
> reverted jira requires RN item reversion

- _source/_change-log/2018-09.md
- Remove RN item related to OKTA-155752 which was reverted in a hotfix
[OKTA-155752](https://oktainc.atlassian.net/browse/OKTA-155752)
> remove reverted item

- _source/_authentication-guide/auth-overview/index.md
This table is incorrect.
* [OKTA-161628](https://oktainc.atlassian.net/browse/OKTA-161628)
> Updating erroneous table

- _source/_change-log/2018-10.md
- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
- Change log for 2018.10
[OKTA-161278](https://oktainc.atlassian.net/browse/OKTA-161278)
> RN and EA tag removal

- _source/_change-log/2018-09.md
- _source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md
- Suggested improvement to doc for a hotfixed bug fix for RN. 
[OKTA-161626](https://oktainc.atlassian.net/browse/OKTA-161626)
> tweak to RN related to hotfix

- _source/_docs/api/resources/system_log.md
- I deleted the Beta tag instead of replacing it with EA.
[OKTA-161768](https://oktainc.atlassian.net/browse/OKTA-161768)
> add missing ea tag

- _source/_includes/sidebar.html
- _source/_layouts/docs_index.html
> Moves "How-to" subdirectory to T.O.C

- _source/_docs/api/resources/idps.md
- Added endpoint doc for /finish and /cancel
- Made all request queries consistent (added -d to a bunch of them, changed a few from http to curl)
- Added a "how to set yourself up to use transactions"--even if that content doesn't belong in this doc, it should be somewhere?
[OKTA-133350](https://oktainc.atlassian.net/browse/OKTA-133350)
> Dok 133350

- _source/_posts/2017-03-16-spring-boot-saml.md
- _source/_posts/2018-02-15-build-crud-app-vuejs-node.md
Updates to [Build a Basic CRUD App with Vue.js and Node](https://developer.okta.com/blog/2018/02/15/build-crud-app-vuejs-node) after doing the tutorial today.
> Update Vue Node CRUD example to use latest dependencies

- _source/_change-log/2017-23.md
- _source/_docs/api/resources/authn.md
- Added section related to IDP initiated app sign-on.
- This is related to the code Jira -> https://oktainc.atlassian.net/browse/OKTA-160275
* [OKTA-161190](https://oktainc.atlassian.net/browse/OKTA-161190)
Please review @tthompson-okta @edjohns-okta @mystiberry-okta 
Screenshot of part of the content:
> Add section related to IDP initiated app sign-on API flow

- _source/_change-log/2018-10.md
- _source/_change-log/2018-11.md
- RN 2018.11
[OKTA-162148](https://oktainc.atlassian.net/browse/OKTA-162148)
> rn 2018-11

- _source/_change-log/2018-11.md
- _source/_docs/api/getting_started/rate-limits.md
- Documenting RL increase to logs after it rolled out to all orgs as requested. I didn't bundle with SysLog EA announcement because the RL isn't EA.
[OKTA-157863](https://oktainc.atlassian.net/browse/OKTA-157863)
> Add RL change to doc and RN

- _source/_posts/2018-03-14-hosting-our-first-developer-conference-iterate.md
Making some updates to the Iterate blog post.
> Iterate post updates

- _source/_use_cases/api_access_management/index.md
- Replacing https://github.com/okta/okta.github.io/pull/1863 (I introduced problems)
> add item about clients and access tokens

- _source/_docs/api/resources/system_log.md
Adds a note about `/logs` use cases.
* [OKTA-161716](https://oktainc.atlassian.net/browse/OKTA-161716)
> OKTA-161716 /logs API: add note about use cases

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/authorization-servers.md
- _source/_docs/api/resources/users.md
- Token Management APIs for : User-Client, Authorization Server-Client, Application
* [OKTA-145525](https://oktainc.atlassian.net/browse/OKTA-145525)
> Token Management API

- _source/_authentication-guide/implementing-authentication/set-up-authz-server.md
- _source/_change-log/2017-20.md
- _source/_change-log/2017-32.md
- _source/_change-log/2017-40.md
- _source/_change-log/2017-44.md
- _source/_code/angular/okta_angular_auth_js.md
- _source/_code/ios/quickstart-appauth-swift.md
- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/authorization-servers.md
- _source/_docs/api/resources/oidc.md
- _source/_docs/how-to/creating-token-with-groups-claim.md
- _source/_standards/OAuth/index.md
- _source/test_page/index.md
Changing `${authorizationServerId}` -> `${authServerId}` so that long URLs render better.
> Changing authz server placeholder

- _source/_docs/api/resources/system_log.md
Fix the docs for the Client id field.
Bacon: test
Resolves: OKTA-162578
* [OKTA-162578](https://oktainc.atlassian.net/browse/OKTA-162578)
> Fix Docs for Client id Field

- _source/_docs/api/resources/authn.md
- :bug: Fixes red syntax highlighting when viewing file diffs in GitHub
* The need to use `&#39;`
> :bug: Fix syntax highlighting

- _source/_change-log/2018-12.md
> Changelog entry for 2018.12

- _source/_docs/api/resources/oidc.md
- Fixing URL for OIDC well-known endpoint. More info in JIRA ticket.
* [OKTA-163419](https://oktainc.atlassian.net/browse/OKTA-163419)
> Fixing URL and adding clarifying text

- _source/_posts/2018-03-23-token-authentication-aspnetcore-complete-guide.md
Fast-track this post for the blog today.
> Publish post early

- _source/_posts/2017-07-25-oidc-primer-part-1.md
- _source/_posts/2017-07-25-oidc-primer-part-2.md
- _source/_posts/2017-08-01-oidc-primer-part-3.md
- _source/_posts/2017-12-18-spring-security-5-oidc.md
- _source/_posts/2018-03-23-token-authentication-aspnetcore-complete-guide.md
- _source/_standards/SCIM/index.md
- Fixes [missing CRUD link](https://github.com/okta/okta.github.io/compare/jm-add-missing-crud-link?expand=1#diff-4d4d3bd54f55bfc7712bcd9d8ef4b60eR1052) and fixes markdown lint issues.
* #1879
> Adds missing SCIM link

- _source/_docs/api/resources/authn.md
- scripts/helpers.sh
- Validates API tag endpoints contain a proceeding `/`
* [Issue #1829](#1829)
> Updates URL and tag validation for proceeding '/'

- _source/_posts/2018-03-27-token-authentication-aspnetcore-complete-guide.md
- Fixes broken links introduced with #1880
> Fix broken blog links

- _source/_code/angular/index.md
- _source/_code/dotnet/index.md
- _source/_code/java/index.md
- _source/_code/nodejs/index.md
- _source/_code/php/index.md
- _source/_code/python/index.md
- _source/_code/react/index.md
- _source/_code/vue/index.md
- Add links to sample applications
- Clarify the difference between quickstarts, samples, and guides
- Add code page for Vue
> Code page cleanup for front-end libraries

- _source/quickstart-fragments/angular/default-example.md
- _source/quickstart-fragments/react/default-example.md
- _source/quickstart-fragments/vue/default-example.md
- Updates the Angular, React, and Vue quickstarts to reflect the breaking changes introduced with `1.0.0` versions of their respective libraries.
* [OKTA-164226](https://oktainc.atlassian.net/browse/OKTA-164226)
> Updated quickstarts for 1.0.0 Angular/React/Vue

- _source/_posts/2018-03-30-everything-you-need-to-know-about-the-twelve-factor-app.md
> Publishing April Fools' update.

- _source/_change-log/2018-09.md
- _source/_change-log/2018-14.md
- Change log 2018-14
[OKTA-164979](https://oktainc.atlassian.net/browse/OKTA-164979)
> change log for 2018-14

- _source/_docs/api/resources/oidc.md
> Fixing domain placeholder typo

- _source/quickstart-fragments/angular/default-example.md
Fix errors in Angular quickstart
> Angular quickstart fixes

- _source/_authentication-guide/implementing-authentication/client-creds.md
- Outline number was incorrect, listing 3 twice.
> Fix Outline numbering

- _source/_docs/api/resources/roles.md
- Update roles#app-administrator-role-app-targets to account for app instance administration
* [OKTA-164450](https://oktainc.atlassian.net/browse/OKTA-164450)
Video Capture of changes:
https://okta.box.com/s/9a9teqlkb37ovztrotugp4ib24dbvfx4
> Update roles#app-administrator-role-app-targets to account for app instance administration

- _source/_posts/2018-01-18-cryptocurrency-pwa-secured-by-okta.md
> Update Crypto PWA blog post to make ncu optional

- _source/_change-log/2018-15.md
- change log for 2018.15
[OKTA-166202](https://oktainc.atlassian.net/browse/OKTA-166202)
> 2018-15 change log

- _source/_change-log/2018-15.md
- _source/_docs/api/resources/roles.md
- Merging weekly changes into source and publishing change log for 2018-15 preview release. There'll be an update for production.
[OKTA-166202](https://oktainc.atlassian.net/browse/OKTA-166202)
> Release 2018 15 preview

- _source/_posts/2017-06-21-what-the-heck-is-oauth.md
Fix issues found in "[What the Heck is OAuth?](https://developer.okta.com/blog/2017/06/21/what-the-heck-is-oauth)" blog post.
> Minor fixes for What the Heck is OAuth blog post

- _source/_posts/2018-04-16-add-auth-to-your-pwa-with-okta-and-stencil.md
ping @leebrandt for merge when build passes
> Fixing broken blog post by rm'ing special chars.

- .travis.yml
- _source/_docs/api/resources/authorization-servers.md
- _source/_docs/api/resources/idps.md
- scripts/find-missing-slashes.js
- scripts/helpers.sh
- scripts/htmlproofer.rb
- scripts/post-build-lint.sh
- scripts/travis.sh
- Updates the `htmlproofer` script to accept a second parameter to *only* run on external links
- Refactor test scripts
```
user    8m53.771s
user    8m29.643s  🎉
```
> Update htmlproofer and refactor tests

- _config.yml
- _source/quickstart-fragments/android/default-example.md
- Callout known issue when using Android
> Update android quickstart to call out known issue

- _source/_assets/js/quickstart.js
- _source/quickstart-fragments/android/default-example.md
- _source/quickstart-fragments/ios/default-example.md
- _source/quickstart-fragments/react-native/default-example.md
- tests/selenium/framework/page-objects/QuickStartsPage.js
- tests/selenium/spec/quickstarts-spec.js
- Adds a React Native quickstart to demonstrate login/logout and passing a token downstream to a resource server.
* [OKTA-165049](https://oktainc.atlassian.net/browse/OKTA-165049)
> :seedling: Adds React-Native quickstart

- _source/_posts/2018-03-16-build-react-native-authentication-oauth-2.md
> Fix React Native URL for blog post. Dot causes download

- _source/_posts/2018-04-19-okta-with-grails.md
I had comments for this in the [PR yesterday](https://github.com/okta/okta.github.io/pull/1972), but they were never fixed.
> Minor fixes to Grails blog post

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/authorization-servers.md
- _source/_docs/api/resources/idps.md
Reverts okta/okta.github.io#1918 pushed a few days too early.
> Revert "DO NOT MERGE until 4/27 release. API doc for Custom URL Domain"

- _source/_code/javascript/okta_auth_sdk.md
> Fix link to Okta Sign-In Widget

- _source/_posts/2018-04-24-simple-node-authentication.md
> Fix issues found in code review for new node post

- _source/_posts/2018-04-24-simple-node-authentication.md
> Fixing typo.

- _source/_posts/2017-06-15-build-microservices-architecture-spring-boot.md
- _source/_posts/2018-02-15-build-crud-app-vuejs-node.md
> Fix links in blog posts

- _source/_standards/SCIM/index.md
Document the payload for the SCIM requests 
[Preview Shortcut](https://github.com/okta/okta.github.io/blob/okta-151325-update-SCIM-doc/_source/_standards/SCIM/index.md#example)
* [OKTA-151325](https://oktainc.atlassian.net/browse/OKTA-151325)
> Update SCIM doc with API payload JSONs

- _source/_change-log/2018-14.md
- _source/_change-log/2018-15.md
- _source/_change-log/2018-17.md
> Release notes for 2018.17

- _source/_posts/2018-04-18-guide-to-testing-java-apis-and-angular.md
The current blog template doesn't handle multiple authors. I have a _fix_ for this, but since there is some work on the Hugo side of things too, i'm guessing it is easier to just keep your name at the top.
Thoughts?
> Add java testing sections

- _source/_posts/2018-04-26-build-crud-app-aspnetcore-angular.md
- Fixes a broken link to allow the site to successfully publish.
> Fix blog post link

- _source/_posts/2018-04-26-build-crud-app-aspnetcore-angular.md
the word `{{handlebars}}` was showing up as `` so I added the raw/endraw to fix it.
> Fix handlebars raw/endraw problem

- _source/_posts/2017-04-26-bootiful-development-with-spring-boot-and-angular.md
Fixes missing YouTube video in [Bootiful Development with Spring Boot and Angular](https://developer.okta.com/blog/2017/04/26/bootiful-development-with-spring-boot-and-angular).
> Fix missing YouTube video

- _source/_code/javascript/okta_sign-in_widget.md
> Fixing indentation and Chinese translations

- _source/_posts/2017-04-26-bootiful-development-with-spring-boot-and-angular.md
I accidentally published it to my own channel yesterday.
> Change screencast URL to video on Okta's channel

- _source/_docs/api/resources/authn.md
- add authentication object into stateToken
- expected to go out as part of 2018.18
* [OKTA-163766](https://oktainc.atlassian.net/browse/OKTA-163766)
@tthompson-okta @mystiberry-okta @federations-okta
> add authentication object into stateToken

- _source/_change-log/2018-18.md
- Change log for 2018.18
[OKTA-169134](https://oktainc.atlassian.net/browse/OKTA-169134)
> Change log for 2018.18

- _source/_posts/2018-01-23-replace-local-storage-with-okta-profile-attributes.md
> Add link from previous blog post to latest one (Hitchhiker's Guide to Testing)

- README.md
- _source/_posts/2018-05-02-testing-spring-boot-angular-components.md
This is necessary since I merged all the PR with the tests in it. Seemed easier to go this route rather than deleting all the merges to master.
> Use testing-start branch to begin tutorial

- _source/_posts/2018-05-02-testing-spring-boot-angular-components.md
> Fix YouTube video and documentation link

- _source/_docs/api/resources/authn.md
* [OKTA-162448](https://oktainc.atlassian.net/browse/OKTA-162448)
> call out U2F multi origin limitation

- _source/_use_cases/integrate_with_okta/provisioning.md
- Email request from @karanharibhakti-okta to correct the name of SCIM. No JIRA, minor fix.
> Incorrect label for SCIM

- _source/_docs/api/resources/apps.md
- Doc: Logout redirect URI on Apps API
* [OKTA-165547](https://oktainc.atlassian.net/browse/OKTA-165547)
> Doc: Logout redirect URI on Apps API ek_OKTA-165547

- _source/_authentication-guide/tokens/refreshing-tokens.md
Updating for new ID token refresh feature
> Removing note about ID tokens not refreshing

- _source/_change-log/2018-19.md
> Change log entry 2018.19

- _source/_standards/SCIM/index.md
- Add SCIM doc with group PATCH JSON payloads
[Preview](https://github.com/okta/okta.github.io/blob/okta-168844-add-scim-group-push-patch/_source/_standards/SCIM/index.md#update-group-details-patch-groupsid)
* [OKTA-168844](https://oktainc.atlassian.net/browse/OKTA-168844)
> Update SCIM doc with Group PATCH JSON payloads

- _source/_assets/js/docsIndex.js
- _source/_code/python/index.md
Updating our Python page to describe the new support plan.
> Python updates

- _source/_change-log/2018-14.md
- _source/_change-log/2018-15.md
- _source/_change-log/2018-17.md
- _source/_change-log/2018-18.md
- _source/_change-log/2018-19.md
- _source/_change-log/2018-20.md
Merging new change log into Weekly.
> Rn 2018.20

- _source/_change-log/2017-11.md
- _source/_posts/2018-03-06-okta-open-source-samples-and-quickstarts.md
- _source/_posts/2018-05-18-node-authentication-with-passport-and-oidc.md
- Fixes broken link introduced with #2060
- Fixes external links captured in [this CRON task](https://travis-ci.org/okta/okta.github.io/builds/380373297)
> :bug: Fixes broken link

- _source/_docs/api/getting_started/rate-limits.md
- _source/_docs/api/resources/system_log.md
This reverts commit 41abb9f5345ddef83d46ffe96d563e34b7f13438, reversing
changes made to af8c9e479d5b039ca33f84e8dc662c7d7b30ac21.
> Revert "Merge pull request #2064 from okta/dok-169183-take2"

- _source/_standards/SCIM/index.md
- _source/_use_cases/integrate_with_okta/oan-faqs.md
- _source/_use_cases/integrate_with_okta/sso-with-saml.md
OKTA-143640
- change the link from oanmanager.okta.com to oinmanager.okta.com
* [OKTA-143640](https://oktainc.atlassian.net/browse/OKTA-143640)
> change the link from oanmanager.okta.com to oinmanager.okta.com

- _source/_posts/2018-04-20-hello-okta-dave.md
- _source/_posts/2018-05-22-simple-multifactor-authentication-in-node.md
> Redirect Hello Dave to /blog

- _source/_change-log/2018-22.md
> Changelog for 2018.22

- _source/_code/angular/okta_angular_sign-in_widget.md
- _source/_code/react/okta_react_sign-in_widget.md
- Updates the Angular and React quickstart walkthroughs to reflect the `1.0.0` updates.
> Updates code walkthroughs

- _source/_standards/SCIM/index.md
- scripts/helpers.sh
- add doc for redirection endpoint for OAuth in scim
* [OKTA-170023](https://oktainc.atlassian.net/browse/OKTA-170023)
> add doc for redirection endpoint for OAuth in scim

- _source/_posts/2018-02-15-build-crud-app-vuejs-node.md
- _source/_posts/2018-05-17-microservices-spring-boot-2-oauth.md
Failures in Travis: https://travis-ci.org/okta/okta.github.io/builds/388441295
> Fix 404s found by link checker

- _source/_docs/api/resources/authn.md
- _source/_docs/api/resources/factors.md
- Add U2F Factors API content to developer doc
- Remove EA label
* [OKTA-172280](https://oktainc.atlassian.net/browse/OKTA-172280)
> Add U2F Factors API content to developer doc

- _source/_posts/2018-06-11-how-to-prevent-your-users-from-using-breached-passwords.md
We can publish this ASAP. It's minor changes for a blog post.
> Updating links

- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
Adjust System Log docs for GA:
- Remove "EA" flag from System Log API doc.
- Add guidance for new projects to Events API doc.
* [OKTA-174890](https://oktainc.atlassian.net/browse/OKTA-174890)
/cc @analytics-okta
> Adjust System Log docs for GA

- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
Reverts okta/okta.github.io#2116
> Revert "Adjust System Log docs for GA"

- _source/_change-log/2018-24.md
> Change log entry for 2018.24

- _source/_posts/2018-06-19-deploy-your-aspnet-core-app-to-azure.md
Change old syntax to new syntax.
> Fix yourOktaDomain placeholder

- _source/_change-log/2018.25.md
> Change log entry for 2018.25

- _source/_code/javascript/okta_sign-in_widget.md
- The Live Widget is cool and we should link to it from our SIW Guide.
* [OKTA-176367](https://oktainc.atlassian.net/browse/OKTA-176367)
> Adding links to Live Widget

- _source/_change-log/2018-25.md
- _source/_change-log/2018-27.md
> Change Log entry for 2018.27

- _source/_posts/2018-07-06-secure-api-mulesoft.md
adds space so the list doesn't look as broken
> add extra space after numbered list items

- _source/_change-log/2018-28.md
> Change log for 2018.28

- _source/_posts/2018-07-11-build-react-graphql-api-user-authentication.md
- _source/_posts/2018-07-11-ci-cd-spring-boot-jenkins-x-kubernetes.md
nevil > naval https://twitter.com/jstrachan/status/1017525573193789442
markdown fix for GraphQL post
> Fix minor typos in recent blog posts

- README.md
Minor updates to our readme to make it more consistent with our other repo readmes. Bonus: more prominent callout to Developer Forum.
> Simplify readme and call out Developer Forum

- _source/_posts/2018-05-11-policy-based-authorization-in-aspnet-core.md
- _source/_posts/2018-07-03-deploy-vue-app-aws.md
- _source/_posts/2018-07-11-ci-cd-spring-boot-jenkins-x-kubernetes.md
> Updated broken links

- _source/_change-log/2018-29.md
Platform release notes for the 2018.29 release.
> Change log for 2018.29

- _source/_standards/SCIM/index.md
Removed a date in the past, and removed links to Stack Overflow in favor of the Developer Forum.
> Small fixes to SCIM standards page

- scripts/publish.sh
- scripts/setup.sh
- Changes build scripts to make them easier to debug
* [OKTA-182388](https://oktainc.atlassian.net/browse/OKTA-182388)
> General script cleanup

- _source/_posts/2018-06-06-node-api-oauth-client-credentials.md
> update to remove a .

- _source/_posts/2018-06-26-securely-manage-users-node-app.md
> flipped two words for readability

- _source/_docs/api/resources/users.md
- Accompanying changes for https://github.com/okta/okta-core/pull/28254 to clean up Grants API
- Add correct `issuer` value and remove `issuerId`
- Remove `"issuer"` and `"revoke"` HAL links and add hints for `"self"` for `GET` and `DELETE`
* [OKTA-175296](https://oktainc.atlassian.net/browse/OKTA-175296)
> Update API docs to reflect Grants API cleanup

- _source/_docs/api/resources/apps.md
- Adds example requests and responses for enabling/disabling self-service for an app instance. Includes a hint for updating username mappings and user profile properties given a specific error.
* [OKTA-182497](https://oktainc.atlassian.net/browse/OKTA-182497)
> Update self-service field in Apps API

- _source/_posts/2018-07-02-build-a-secure-crud-app-with-aspnetcore-and-react.md
Reader commented that The .NET Framework 2+ should be .NET Core 2+. They were right. I fixed. :)
> Fixed from comment suggestion

- _source/_posts/2018-08-02-aspnet-core-angular-crud.md
fixed a list that got jacked up by GDocs
> Fixed list that Google hosed when I copied it

- _source/_posts/2018-08-02-aspnet-core-angular-crud.md
> Changed title for Lindsay

- _source/_docs/api/postman/logs.json
- _source/_docs/api/resources/system_log.md
- _source/_reference/postman_collections/index.md
I published the latest Postman collection for System Log API to getpostman.com, and this PR updates the links in our docs to point to the new version.
> Update System Log postman collection

- _source/_change-log/2018-32.md
- _source/_docs/api/resources/system_log.md
* Changelog entry for 2018.32
* Added new event type mentioned in changelog to System Log API reference
Tested and renders fine. Under review by the Release Notes team.
> Changelog 2018.32

- _source/_change-log/2018-32.md
- _source/_docs/api/resources/system_log.md
Changelog and updates for 2018.32 release.
> Release 2018.32

- _source/_posts/2018-02-06-build-user-registration-with-node-react-and-okta.md
> Small code change in navigation component

- _source/_change-log/2018-33.md
> Changelog 2018.33

- _source/_docs/api/resources/policy.md
- As in title. Also added "The" to beginning of paragraph that precedes note. 
* [OKTA-184756](https://oktainc.atlassian.net/browse/OKTA-184756)
> Adding note about non-Okta non-AD users for group password policy

- _source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md
Inline tip:
CTA to Angular 7 post at bottom:
> Add fix for Angular 6+ in Spring Boot 2 + Angular 5 blog post

- _source/_change-log/2018-35.md
> Changelog 2018.35

- _source/_docs/api/resources/oauth-clients.md
- _source/_docs/api/resources/oidc.md
- documentation for jwks upload
- expand set of accepted signing algorithms for client assertion tokens and authorize request objects
* [OKTA-181514](https://oktainc.atlassian.net/browse/OKTA-181514)
@jakubvul @yuliu-okta 
> DOC updates for private_key_jwt

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/users.md
Adding parameter to endpoints which received the new sendEmail parameter
* [OKTA-176005](https://oktainc.atlassian.net/browse/OKTA-176005)
Cherry picked from @Krisoblucki-okta 's original PR [here](https://github.com/okta/okta.github.io/pull/2294) because that was made off of `source` instead of `weekly`.
> Update documentation for the addition of the sendEmail

- _source/_docs/api/resources/linked-objects.md
- package-lock.json
doc Linked Object property name restrictions
* [OKTA-186278](#186278)
* [OKTA-186278](https://oktainc.atlassian.net/browse/OKTA-186278)
> DWW OKTA-186278 doc Linked Object property name restrictions

- _source/_posts/2017-06-21-what-the-heck-is-oauth.md
> small fixes to article

- _source/_docs/api/resources/oidc.md
- Acting on Gronberg's feedback.
> Acting on feedback

- _source/_posts/2018-09-13-build-and-understand-express-middleware-through-examples.md
> Changes requested by @mraible

- _source/_posts/2018-09-14-how-to-get-more-users-to-enable-2fa-on-their-accounts.md
> adds 2fa-enabled image to frontmatter

- _source/_docs/api/resources/policy.md
Update policy system property to be boolean
> Update policy system property to be boolean

- _source/_posts/2018-08-30-build-one-time-password-token-for-mfa.md
- Just updated the tweets (which have not yet been published)
> updated tweets per @lindsayb610

- _source/_posts/2018-09-17-desktop-app-electron-authentication.md
Example app changes at https://github.com/oktadeveloper/okta-appauth-js-electron-example/pull/1
> Update Electron blog post for Electron 3.0 and AppAuth 1.1.1

- _source/_change-log/2018-38.md
> Change log entry for 2018.38

- _source/_posts/2018-03-01-develop-microservices-jhipster-oauth.md
Also fixes Heroku images on mobile.
> Fix PR number in JHipster microservices post

- _config.yml
- _source/_assets/css/event-types.scss
- _source/_assets/js/docs.js
- _source/_assets/js/event-types.js
- _source/_data/docs.yml
- _source/_data/event-types.json
- _source/_docs/api/resources/event-types.md
- _source/_docs/api/resources/system_log.md
- _source/_layouts/base.html
- _source/_layouts/docs_page.html
Adds event type catalog data and templated page
- Adds new event-types.md page
- Links from system_log.md page
- Adds support for removing ToC via page variables
* [OKTA-188842](https://oktainc.atlassian.net/browse/OKTA-188842)
> OKTA-188842: Adds event type catalog data and templated page

- _source/_data/event-types.json
- _source/_docs/api/resources/event-types.md
Updates new event type descriptions.
* [OKTA-190315](https://oktainc.atlassian.net/browse/OKTA-190315)
> OKTA-190315: Updates new event type descriptions.

- _source/_change-log/2018-39.md
> Change log.2018.39

- _source/_docs/api/resources/oidc.md
- Fix description of parameter priority for authorize request JWT
* [OKTA-187642](https://oktainc.atlassian.net/browse/OKTA-187642)
@larsjohansen-okta @jakubvul
> Update parameter priority order for authorize request object.

- _source/_assets/css/event-types.scss
- _source/_assets/js/event-types.js
- _source/_data/event-types.json
- _source/_docs/api/resources/event-types.md
Updates event types to include the release number that each event type was introduced.
- Adds url deep linking based on search state which is synchronized between input and url
- Removes "shuffle" icon for legacy event type mappings 
- Adds  "tag" icon to each tag
- Improves visual separation of event types via improved header
- Bolds the "top level" object of each event type id to aid in visual scanning
- Improves whitespace 
- Isolates css styles from not affecting footer
- Cleans up javascript file
* [OKTA-190678](https://oktainc.atlassian.net/browse/OKTA-190678)
@okta/analytics
> OKTA-190678: Updates event types to include the release that the event type was introduced

- _source/_data/docs.yml
- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
- _source/_use_cases/events-api-migration/index.md
Renames "Events API Deprecation" to "Events API Migration"
> Renames "Events API Deprecation" to "Events API Migration"

- _source/_posts/2018-08-21-build-secure-rest-api-with-node.md
> Updating H2s for SEO.

- _source/_data/event-types.json
Event type updates for 2018.41. See weekly email for details.
* [OKTA-192649](https://oktainc.atlassian.net/browse/OKTA-192649)
> OKTA-192649: Event type updates for 2018.41

- _source/_change-log/2018-41.md
> Changelog 2018.41

- _source/_docs/api/getting_started/rate-limits.md
- Just what the title says. Also changed the page title to be consistent with the URL.
> Should be merged as part of 2018.41 release
* [OKTA-192151](https://oktainc.atlassian.net/browse/OKTA-192151)
> Adding note about rate limit notifications (2018.41)

- _source/_use_cases/events-api-migration/index.md
fix anchor links (please double-check that i did it right)
> Fix links on Events API migration document

- _source/_change-log/2018-42.md
> Entry for 2018.42

- _source/_docs/api/resources/authn.md
> Fix typo: SeurID → SecurID

- _source/_change-log/2018-43.md
- Adding change log entry for 43. Also making small update to 40, to match style of other entries.
* [OKTA-194990](https://oktainc.atlassian.net/browse/OKTA-194990)
> 2018.43 Change Log

- _config.yml
- _source/_code/javascript/okta_auth_sdk.md
> Update AuthJS guide for 2.0 signatures

- _source/_standards/SCIM/SCIMFiles/Okta-SCIM-11-SPEC-Test.json
Reverts okta/okta.github.io#2428
@ivanvoloshyn-okta
> Revert "ai_OKTA-192001_Update_SCIM_1.1_Spec_Test_Suite"

- _source/_reference/postman_collections/index.md
- Alphabetizing the list of Postman collections.
> Alphabetizing the list of Postman collections

- _source/_docs/api/postman/api-access-mgmt.json
- _source/_docs/api/postman/authorization-server.json
- _source/_reference/postman_collections/index.md
- Updating Postman collections to create separate Authorization Server collection. Previously, Authorization Server APIs were in a folder in the API Access Management (OAuth 2.0) collection.
* [OKTA-159456](https://oktainc.atlassian.net/browse/OKTA-159456)
> [OKTA-159456] Updating Postman collections

- _source/_posts/2018-04-26-build-crud-app-aspnetcore-angular.md
removed all triple backticks for inline code. fixed the problem. Also fixed some formatting of button names.
> Fixes to code formatting backticks

- _source/_change-log/2018-45.md
- Fixing table at top of change log entry, to include link to new feature.
* [OKTA-196732](https://oktainc.atlassian.net/browse/OKTA-196732)
> Fixing table at top of change log entry, to include link to new feature.

- _source/_docs/api/resources/policy.md
- Policy API doc: fixing code example for creating a rule, adding name parameter to rules object table.
* [OKTA-190165](https://oktainc.atlassian.net/browse/OKTA-190165)
> [OKTA-190165] Policy API doc: fixing code example for creating a rule

- docs/.vuepress/vuepress-theme-default/layouts/404.vue
> [VuePress] 404 page

- _source/_change-log/2018-45.md
- This pull request is to sync up weekly with the most recent version of the change log for 2018.45.
* [OKTA-196732](https://oktainc.atlassian.net/browse/OKTA-196732)
> Sync up change log 2018.45 on weekly

- _source/_posts/2017-09-14-lazy-developers-guide-to-auth-with-vue.md
- _source/_posts/2017-10-04-aspnet-authorization.md
> Fixed two broken links

- _source/_code/react/index.md
- Fixes an issue where the recommended blog posts links were not formatted properly
* #2455
> Fix related blog post list on react code page

- _source/_docs/api/resources/schemas.md
- Removing link to draft support doc
* [OKTA-195910](https://oktainc.atlassian.net/browse/OKTA-195910)
> Removing link to draft support doc

- _source/_posts/2018-09-17-desktop-app-electron-authentication.md
Example app changes in https://github.com/oktadeveloper/okta-appauth-js-electron-example/pull/3.
> Fix compile errors in Electron post

- _source/_docs/api/resources/factors.md
- Fixing description for SMS factor that he been misapplied to Call factor.
> Call factor Typo #2

- _source/_change-log/2018-48.md
- Platform Change Log: Adding entry for 2018.48.
* [OKTA-198901](https://oktainc.atlassian.net/browse/OKTA-198901)
> [OKTA-198901] Platform Change Log: Adding entry for 2018.48.

- _source/quickstart-fragments/nodejs/express-implicit.md
- _source/quickstart-fragments/react/default-example.md
- Fix React code examples to reflect recent updates (clientId requirements and auth object)
> Fix React code example to reflect recent updates

- _source/_posts/2018-11-15-node-express-typescript.md
- minor fixes to article content
> minor fixes

- _source/_change-log/2018-45.md
- _source/_change-log/2018-49.md
> Change log Entry 2018.49

- _source/_docs/api/resources/oidc.md
I noticed that there was no example for the /token endpoint. Even though is not super hard to figure out how to form the request, I think an example is super useful and can avoid frustration.
Do I really need a jira for this? :)
> Added an example for the /token endpoint

- _source/_posts/2018-10-10-react-native-spring-boot-mobile-app.adoc
It doesn't look so good currently. ;)
> Change Markdown to AsciiDoc in React Native blog

- _source/_change-log/2018-50.md
- Change log entry for this week
> New changelog entry 2018.12.1

- _source/_docs/api/resources/zones.md
> zones: fix curl commands

- _source/_docs/how-to/add-user-consent-to-flow.md
> add consent: fix curl

- _source/_docs/how-to/updating_saml_cert.md
> updating saml: fix curl

- _config.yml
- Update signin-widget version to latest 2.14
* [OKTA-198363](https://oktainc.atlassian.net/browse/OKTA-198363)
> :art: update signin widget version to 2.14

- _source/_posts/2017-06-21-what-the-heck-is-oauth.md
> Use Nate's YouTube Video for What the Heck is OAuth

- _source/_posts/2018-12-20-crud-app-with-python-flask-react.md
fixed list
fixed last header
added link to GH repo
> Fixes and GH repo added

- .travis.yml
- package.json
- scripts/helpers.sh
- scripts/publish.sh
- scripts/setup.sh
- scripts/travis.sh
> [VuePress] Deployment Scripts Updated

- _source/_change-log/2018-52.md
- Creating change log entry for release 2018.12.2 / 2018.52
* [OKTA-203207](https://oktainc.atlassian.net/browse/OKTA-203207)
> Creating change log entry for release 2018.12.2 / 2018.52

- _source/_posts/2018-12-27-build-a-basic-android-app-with-xamarin-and-visual-studio.md
Junk Commit to include a space to push through a re-build
> Add space to trigger build

- _source/_change-log/2018-52.md
- Minor tweaks to the release notes for 2018-12-2.
* [OKTA-203207](https://oktainc.atlassian.net/browse/OKTA-203207)
> Minor tweaks to the release notes for 2018-12-2.

- packages/@okta/migrate-from-jekyll/rules/alterMarkdownStrings.js
- packages/@okta/migrate-from-jekyll/rules/index.js
- packages/@okta/migrate-from-jekyll/rules/updateResourceMarkdownStrings.js
- packages/@okta/vuepress-site/docs/api/resources/apps/index.md
- packages/@okta/vuepress-site/docs/api/resources/authn/index.md
- packages/@okta/vuepress-site/docs/api/resources/authorization-servers/index.md
- packages/@okta/vuepress-site/docs/api/resources/events/index.md
- packages/@okta/vuepress-site/docs/api/resources/factor_admin/index.md
- packages/@okta/vuepress-site/docs/api/resources/factors/index.md
- packages/@okta/vuepress-site/docs/api/resources/groups/index.md
- packages/@okta/vuepress-site/docs/api/resources/idps/index.md
- packages/@okta/vuepress-site/docs/api/resources/linked-objects/index.md
- packages/@okta/vuepress-site/docs/api/resources/oauth-clients/index.md
- packages/@okta/vuepress-site/docs/api/resources/oidc/index.md
- packages/@okta/vuepress-site/docs/api/resources/policy/index.md
- packages/@okta/vuepress-site/docs/api/resources/roles/index.md
- packages/@okta/vuepress-site/docs/api/resources/schemas/index.md
- packages/@okta/vuepress-site/docs/api/resources/sessions/index.md
- packages/@okta/vuepress-site/docs/api/resources/system_log/index.md
- packages/@okta/vuepress-site/docs/api/resources/templates/index.md
- packages/@okta/vuepress-site/docs/api/resources/trusted-origins/index.md
- packages/@okta/vuepress-site/docs/api/resources/users/index.md
- packages/@okta/vuepress-site/docs/api/resources/zones/index.md
converts all api_operation calls to Vue component
Removes markdown-it attrs
> [VuePress] Update resource markdown

- _source/_reference/okta_expression_language/index.md
Updated the string.stringSwitch examples per Don Woods in the String Functions table.
* [OKTA-103244](https://oktainc.atlassian.net/browse/OKTA-103244)
> updated the string.stringSwitch examples per Don Wood

- _source/_posts/2017-04-17-angular-authentication-with-oidc.md
To reduce errors reported in [Angular Authentication with OpenID Connect and Okta in 20 Minutes](https://developer.okta.com/blog/2017/04/17/angular-authentication-with-oidc).
> Specify npm versions in Angular OIDC post

- _source/_change-log/2019-1-0.md
- _source/_data/event-types.json
- _source/_docs/api/getting_started/rate-limits.md
- _source/_docs/api/resources/idps.md
- _source/_docs/api/resources/policy.md
- Release Notes entry for 2019.1.0 and all relevant documentation updates
* [OKTA-204087](https://oktainc.atlassian.net/browse/OKTA-204087)
> Release 2019.1.0

- _source/_docs/api/resources/oidc.md
- _source/_reference/authentication_reference.md
- We have an empty file that uses an ineffective redirect strategy. I have deleted the file and added the URL to the OIDC page's `redirect_from` list.
> Removing empty file, creating redirect

- _source/_docs/how-to/creating-token-with-groups-claim.md
- Added OKTA-Mastered section at the top and fixed some typos and missing articles in titles.
* [OKTA-166854](https://oktainc.atlassian.net/browse/OKTA-166854)
> added okta-mastered section

- _source/_change-log/2018-52.md
- _source/_change-log/2019-01-0.md
- Adding item to 2019.01.0 RN
- Renaming file so that it is sorted properly
- Fixing typo in 2019.12.2 RN
> Adding item to 2019.01.0 RN

- packages/@okta/vuepress-site/docs/api/getting_started/enabling_cors/index.md
- packages/@okta/vuepress-theme-default/global-components/CorsTest.vue
- packages/@okta/vuepress-theme-default/package.json
- yarn.lock
Creates a component for testing CORS
> [VuePress] CORS Test Component

- _source/_posts/2019-01-22-whats-new-in-es2019.md
> changes 'article' to 'post'

- _source/_authentication-guide/social-login/facebook.md
- _source/_authentication-guide/social-login/google.md
- _source/_authentication-guide/social-login/linkedin.md
- _source/_authentication-guide/social-login/microsoft.md
- Just what it says in the title
> Fixing links

- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-default/package.json
- yarn.lock
Updates from 1.0.0-alpha.30 to 1.0.0-alpha.33
> Updates to alpha.33 VuePress

- _source/_change-log/2019-01-2.md
OKTA-205446 addition to Release Notes
> OKTA-205446 addition to Release Notes

- _source/_posts/2019-02-04-create-and-verify-jwts-in-php.md
> [blog] Create and Verify JWTs in PHP with OAuth 2.0

- _source/_docs/api/resources/users.md
- Removing EA lifecycle tag from mentions of hashed password functionality.
- Merge for release 2019.02.0.
* [OKTA-191976](https://oktainc.atlassian.net/browse/OKTA-191976)
> Hashed Passwords: Removing EA lifecycle flag.

- _source/_docs/api/getting_started/rate-limits.md
- Adding information about high-capacity rate limits.
- Targeting 2019.2.0 release.
* [OKTA-204227](https://oktainc.atlassian.net/browse/OKTA-204227)
> Adding info about High Capacity Rate Limits

- _source/_authentication-guide/social-login/google.md
- Updating Google social login instructions
- Is this PR related to a Monolith release? This should go out with 2019.02.0
> Removing Googleplus mentions

- _source/_change-log/2019-02-0.md
- Change log and updates for weekly release.
* [OKTA-209158](https://oktainc.atlassian.net/browse/OKTA-209158)
> Changelog 2019.02.0

- _source/_change-log/2019-02-0.md
Using initial caps for name of Inline Hook feature
> Changing capitalization of Inline Hooks

- _source/_code/dotnet/index.md
- _source/_code/dotnet/okta-oauth-aspnet-codeflow.md
- _source/_code/dotnet/okta-oauth-spa-authjs-osw.md
- _source/_code/dotnet/okta-oidc-spa-osw-aspnet.md
Fixes OKTA-209821.
Remove blank pages and redirect to .NET index page.
* [OKTA-209821](https://oktainc.atlassian.net/browse/OKTA-209821)
> Remove blank .NET Code pages

- _source/_reference/okta_expression_language/index.md
- Updating inaccurate EL examples. 
- **Is this PR related to a Monolith release?** No
* [OKTA-103179](https://oktainc.atlassian.net/browse/OKTA-103179)
> Applying EL doc fixes

- _source/_code/dotnet/aspnetcore/index.md
Fix malformed link.
* [OKTA-209927](https://oktainc.atlassian.net/browse/OKTA-209927)
> Fix malformed link in .NET page

- _source/_change-log/2019-02-0.md
> Fixing dates

- _source/_use_cases/inline_hooks/import_hook/import_hook.md
- _source/_use_cases/inline_hooks/index.md
- Documentation page for the import inline hook.
- Import inline hooks scheduled to be released in EA in release 2019.03.0.
* [OKTA-207277](https://oktainc.atlassian.net/browse/OKTA-207277)
> Doc for Import Inline Hook

- _source/_docs/api/getting_started/rate-limits.md
- _source/_docs/api/resources/system_log.md
- Removed misleading rate limit text.
- Added system log event
- This PR should be merged as part of the 2019.03.0 release.
* [OKTA-209915](https://oktainc.atlassian.net/browse/OKTA-209915)
> Updating rate limit text and adding new system event

- _source/_use_cases/inline_hooks/import_hook/import_hook.md
- Minor edits to the Import Inline Hook doc page.
- Address comments made by Jacky on pull request https://github.com/okta/okta.github.io/pull/2760
* [OKTA-207277](https://oktainc.atlassian.net/browse/OKTA-207277)
> Import Inline Hook: minor edits.

- _source/_change-log/2019-03-0.md
> change log for 2019 March 3

- _source/_change-log/2019-03-0.md
- putting in the correct import hook description
> import hook description

- _source/_authentication-guide/generic-oidc/index.md
- fixed formatting and urls to code
> fixed formatting and urls to code

- _source/_posts/2019-03-13-build-rest-api-with-aspnet-web-api.md
> Fix author for post

- _source/_posts/2018-08-21-build-secure-rest-api-with-node.md
To fix this problem: https://devforum.okta.com/t/error-your-client-id-is-missing/3363
> Fixed OktaVerifier constructor call

- _source/_docs/api/resources/authn.md
- `s/password password/password/`
> Remove remove extra word

- _source/_posts/2018-07-19-simple-crud-react-and-spring-boot.md
Related: https://github.com/oktadeveloper/okta-spring-boot-react-crud-example/pull/11
> Fix code flaw in React + Spring Boot CRUD post

- _source/_use_cases/inline_hooks/import_hook/import_hook.md
- Adding coverage of the com.okta.user.update command.
- Adding note that the UI cannot be used with AD and LDAP.
* [OKTA-214512](https://oktainc.atlassian.net/browse/OKTA-214512)
> Import Inline Hook: Corrections

- _source/_change-log/2019-03-1.md
- _source/_change-log/2019-03-2.md
> RN entry for 2019.03.2

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> Adds notice for new repo

- _source/_posts/2019-03-25-build-crud-app-with-python-flask-angular.md
> Fixed featured image to an Angular image instead of the .NET image

- _source/_posts/2018-09-13-build-and-understand-express-middleware-through-examples.md
Fixes issue [#49](https://github.com/oktadeveloper/okta-blog/issues/49).
> Fixed typo in code

- _source/_posts/2018-08-27-build-crud-app-vuejs-netcore.md
fixes issue [#49](https://github.com/oktadeveloper/okta-blog/issues/49)
> Fixes to post from post comments

- _source/_posts/2018-07-09-five-minute-php-app-auth.md
fixes https://github.com/oktadeveloper/okta-blog/issues/47
> [blog] add default openid scope

- _source/_posts/2018-11-15-node-express-typescript.md
If you need to submit changes for documentation, plesae do so at [our new repo](https://github.com/okta/okta-developer-docs)
Updates code sample for Node TypeScript Express post.
* https://github.com/oktadeveloper/okta-blog/issues/46
> updates code sample to use 'raw'

- _source/_posts/2019-02-19-add-social-login-to-spring-boot.md
If you need to submit changes for documentation, plesae do so at [our new repo](https://github.com/okta/okta-developer-docs)
Fixes user-authorization-uri in Spring Login with Spring Boot and updates post language to reflect fix.
> fixed auth login uri issue

- _source/_posts/2019-02-25-java-i18n-internationalization-localization.adoc
> Add i18n screencast to its blog post

- _source/_posts/2018-07-19-simple-crud-react-and-spring-boot.md
Example app fixed in https://github.com/oktadeveloper/okta-spring-boot-react-crud-example/pull/12.
> Fix @PutMapping path in React + Spring Boot post

- _source/_posts/2019-04-24-crud-app-aspnet-core-sql-server.md
> Fixing SQL Server Version

- _source/_posts/2019-03-20-linking-your-alexa-skils-securely.md
> Fixing capitalization in title

- _source/_posts/2019-04-04-java-11-java-12-jhipster-oidc.adoc
> Fix link to screencast

- _source/_posts/2019-03-11-node-sql-server.md
If you need to submit changes for documentation, plesae do so at [our new repo](https://github.com/okta/okta-developer-docs)
- Is this PR related to a Monolith release? If so, which one?
> fixes code samples in Node.js + SQL Server tutorial

- _source/_posts/2018-08-28-nginx-auth-request.md
> [blog] update nginx blog post

- scripts/htmlproofer.rb
You can see the error at https://travis-ci.org/okta/okta.github.io/builds/535541971#L1321.
> Fix cron tests by ignoring /search/index.html

- _source/_posts/2019-05-30-vue-pwa-typescript.md
Example app changes in https://github.com/oktadeveloper/okta-vue-books-pwa-example/pull/2.
>  Update Vue PWA post to use TypeScript

- _source/_includes/header.html
Documentation updated their primary nav
> He sync nav docs

- _source/_posts/2018-05-08-build-video-chat-app-with-javascript-webrtc-and-okta.md
- _source/_posts/2019-05-29-build-crud-nodejs-graphql.md
- scripts/publish.sh
Restoring previously removed images due to size limits.
> Restoring images

- _source/_posts/2019-06-20-ionic-4-tutorial-user-authentication-and-registration.md
Fixes based on Facebook feedback.
> Clarify instructions and fix link in Ionic post

- _source/_posts/2019-05-23-java-microservices-spring-cloud-config.adoc
Reported in a [blog post comment](http://disq.us/p/22xj5gd).
> Fix typo in JHipster microservices post

- _source/_posts/2019-07-09-software-is-a-creative-endeavor.md
> Software creative Blog post initial load

- _source/_posts/2019-07-12-secure-your-aspnet-core-app-with-oauth.md
> DO NOT MERGE UNTIL 7/12/19: Initial commit of Ryan's ASP.NET Core OAuth 2.0 Post

- _source/_data/authors.yml
> updated for jimena

- _source/_posts/2017-10-17-add-the-power-of-webhooks-to-your-app-with-oktas-system-log.md
- Describe your changes: As per https://github.com/Runscope/requestbin, the web version of request bin has been discontinued. This PR removes the reference to requestb.in.
- Is this PR related to a Monolith release? No
> Removed reference to requestb.in

- _source/_posts/2019-07-17-monitoring-with-actuator.md
Improves [Actuator post](http://localhost:4000/blog/2019/07/17/monitoring-with-actuator) to add syntax highlighting for Java, remove bold links, and remove extra line breaks.
> Improvements to Actuator post

- _source/_posts/2019-07-25-the-hardest-thing-about-data-encryption.md
> Data encryption

- _source/_posts/2019-07-29-hashing-techniques-for-password-storage.md
> Adding new post on password hashing.

- _source/_posts/2019-08-01-secure-applications-with-certificate-pinning.md
> Adding new article on cert pinning.

- _source/_posts/2019-08-14-javafx-tutorial-oauth2-oidc.md
> Add tutorial to title of JavaFX post

- _source/_posts/2018-07-27-build-crud-app-in-aspnet-framework-webapi-and-angular.md
> Fixed repo URL for example code from Ibro's Repo to OktaDeveloper one.

- _source/_posts/2019-08-22-okta-authjs-pkce.md
quick fix for @mraible's suggested updates
> Implemented @mraible's suggestions

- _source/_posts/2019-08-22-okta-authjs-pkce.md
> fixes typo and minor markdown lint issues

- _source/_posts/2019-08-28-reactive-microservices-spring-cloud-gateway.adoc
No more snapshot, no more: https://github.com/oktadeveloper/okta-maven-plugin
> Remove the need for the SNAPSHOT repo when using okta-maven-plugin

- _source/_posts/2019-08-30-php-authorization-oauth-2-okta.md
> add tweets

- .github/workflows/blank.yml
> Test workflows

- _source/_posts/2019-09-05-laravel-authentication.md
> Adding test.
