- docs/api/rest/users.md
@larsjohansen-okta @stsai-okta @tthompson-okta @karlmcguinness-okta 
These are the changes to the users api for
1. Remove the 10000 default for api results per DDRR.
2. Added secondary email in many places.
3. New post method for partial user updates.
Please review these changes and let me know if we can push this to master.
> Users.md changes second email, profile update post method

- docs/api/rest/users.md
How's the wording?
@croche-okta @tthompson-okta @eklein-okta @stsai-okta @larsjohansen-okta @rwang-okta
> Added additional profile filters

- docs/api/rest/users.md
@stsai-okta @karlmcguinness-okta @croche-okta 
This is the doc for OKTA-53810 going into preview on April 8. If this PR is good, we can have a link to it from the preview release notes. Thx!  -Evan
> Added info to Password Rest in Users.md to convert a user to a federated user

- docs/getting_started/design_principles.md
@karlmcguinness-okta 
This is the finalized text about character sets. Good to go?
> Character Set Description

- docs/getting_started/okta_expression_lang.md
@amoghvasekar-okta @georgekwon-okta 
Is this good to go for the preview release on Wednesday?
> Added new conversion function OKTA-56124

- _source/_includes/blog_post.html
- _source/assets/css/page-blog.scss
- assets/css/page-blog.css
- blog/2015/04/07/android-unit-testing-part-2/index.html
- blog/2015/04/14/android-unit-testing-part-3/index.html
- blog/2015/04/23/android-unit-testing-part-4/index.html
- blog/2015/05/08/productionalizing-active-mq/index.html
- blog/2015/05/08/software-engineering-design-principles/index.html
- blog/index.html
- sitemap.xml
Icons come from the existing font awesome library that's in place.
I also cleaned up the styling of the title to not show the underline for blog posts.
> Adds social links for blog posts

- _source/_data/authors.yml
- _source/_posts/2015-06-11-trustpage.md
I changed the article and the author.yml file since yesterday.
> Trust page blog

- _source/docs/guides/saml_guidance.md
- Updated the **SAML for Mobile Native Apps** section with a link to the **Okta Mobile Connect** guide.
- Removed ~~Supporting Okta Mobile Connect~~ section, since that information is now in the **Okta Mobile Connect** guide.
- Added **Testing SAML** section with a link to the Okta SAML validation tool.
- Updated links in the **SAML Toolkits** section.
@slee-okta: FYI @eklein-okta: For your review.
> Update SAML Guidance 

- _source/docs/api/resources/roles.md
> Corrections to routes

- _source/_data/docs.yml
- _source/docs/api/resources/schema.md
@karlmcguinness-okta  @georgekwon-okta  Please Review the new schema doc
> Schema docs

- _source/docs/api/resources/authn.md
- _source/docs/api/resources/factors.md
Can we publish?
@srinivasanagandla-okta
> Added push factor to factors and authn

- _source/docs/api/resources/sessions.md
Here is the server-side PR: https://github.com/okta/okta-core/pull/11365
@karlmcguinness-okta @joelfranusic-okta please review.
> Update Sessions API model with new attributes.

- _source/docs/api/resources/apps.md
@karlmcguinness-okta @bng-okta 
FYI @tgu-okta
> key rollover improvement

- _source/docs/api/resources/apps.md
@karlmcguinness-okta
FYI @tgu-okta
> small change

- _source/_data/authors.yml
- _source/_includes/blog_post.html
- _source/_layouts/blog_index.html
- _source/_layouts/blog_post.html
- _source/_posts/2015-12-07-oauth.md
- _source/_posts/2016-01-05-rest-service-auth-jwt.md
- blog/2015/04/07/android-unit-testing-part-2/index.html
- blog/2015/04/14/android-unit-testing-part-3/index.html
- blog/2015/04/23/android-unit-testing-part-4/index.html
- blog/2015/05/08/productionalizing-active-mq/index.html
- blog/2015/05/08/software-engineering-design-principles/index.html
- blog/2015/05/22/tcmalloc/index.html
- blog/2015/12/02/tls-client-authentication-for-services/index.html
- blog/2015/12/07/oauth/index.html
- blog/2016/01/05/rest-service-auth-jwt/index.html
- blog/index.html
- feed.xml
- sitemap.xml
> Add JWT service auth blog post

- _source/docs/guides/social_authentication.md
> Update URLs and Postman collection

- _source/docs/guides/oan_guidance.md
Also, I know Tim Gu suggested some edits last week but I don't think his were merged. This is not a branch off of his updates but what is currently live on the site. Both our changes need to be incorporated though I don' t think there will be any conflicts.
- minor text updates throughout
- updated some images (did this in a “hacky” way and should likes upload to images section in github but I was unsure how to do this)
- updated some FAQS
> Updates to OAN Guide

- _source/docs/api/resources/idps.md
> Remove one place where type was still present in userNameTemplate.

- _source/docs/api/resources/idps.md
Docs PR for OKTA-77359
@tthompson-okta 
@karlmcguinness-okta 
@joelfranusic-okta 
@mattloughran-okta
> Move policy.subject.format to protocol.settings.nameFormat

- _source/docs/api/resources/idps.md
Simple change for OKTA-77367
@tthompson-okta 
@karlmcguinness-okta 
@joelfranusic-okta 
@mattloughran-okta
> Adds activate & deactivate lifecycle links to example.

- _source/docs/api/resources/sessions.md
Relates-To: OKTA-76767
Primary Reviewer: @joelfranusic-okta 
Reviewer: @federations-okta 
FYI: @mattloughran-okta @eklein-okta  (we'll need your help with the merge once Joel gives it a shipit)
> Add login field into the session model in seesions.md

- _source/docs/api/resources/users.md
Users can now be created with a federated or social provider.
Primary reviewer: @tthompson-okta @eklein-okta 
Secondary reviewers: @federations-okta
> OKTA-74077

- _source/docs/api/resources/users.md
Added additional info for User creation with authentication provider
> OKTA-74077-fix

- _source/docs/api/resources/search-beta.md
Adding a separate search-beta.md file to give beta customers documentation for Advanced User Search API.
Reviewers: @joelfranusic-okta @mattloughran-okta @tthompson-okta @karlmcguinness-okta @cwu-okta @eklein-okta
> OKTA-77020 - for beta customers

- _source/docs/api/resources/policy.md
- Add resource types, link between them
- Add object examples
- Add new endpoints
- Add new resource types
> Major updates to policy.md

- _source/docs/api/resources/oidc.md
- _source/docs/examples/session_cookie.md
Added documentation to the OIDC endpoints.
Still missing links to public-client app documentation which is not ready yet.
Removed Okta specific error codes for now for the authorize endpoint.
Primary reviewer: @karlmcguinness-okta 
Reviewers: @joelfranusic-okta 
@eklein-okta @mattloughran-okta I think Karl's got some changes planned before it'll come your way, but FYI.
> Okta 77563 mchugh oidc

- _source/docs/api/resources/oauth-clients.md
Resolves: OKTA-78919
@joelfranusic-okta @slee-okta @karlmcguinness-okta @hassenkaraa-okta @federations-okta
> Documentation for the OAuth Client Registration API.

- _source/docs/api/resources/oauth-clients.md
Clarify some assumptions in the Public Client App API, specifically for clients which intend to use the Resource Owner Password flow.
@joelfranusic-okta @karlmcguinness-okta @hassenkaraa-okta @mystiberry-okta @mohitchugh-okta @federations-okta
> OKTA-79914

- _source/docs/api/getting_started/error_codes.md
- _source/docs/api/resources/oidc.md
Cleaned up the code as per OKTA-79132.
Made changes to both oidc and error_codes.md
Resolves: OKTA-79132
Primary reviewer: @joelfranusic-okta 
Reviewers: @tthompson-okta 
FYI - @mystiberry-okta
> OKTA-79132 Add cleaned up error codes back in the OIDC doc

- _source/docs/api/resources/idps.md
Very small change to the links object docs.
@karlmcguinness-okta @mattloughran-okta @slee-okta @joelfranusic-okta @eklein-okta
> Changes login link to authorize

- _source/docs/api/resources/oidc.md
- _source/docs/guides/social_authentication.md
Make a few corrections to the ID token examples and client registration guide.
@mystiberry-okta @hassenkaraa-okta @slee-okta @joelfranusic-okta @karlmcguinness-okta @federations-okta
> OKTA-77056

- _source/docs/api/resources/oidc.md
Clarified which all claims are returned in this case.
Also removed login claim and added preferred_username claim as per some earlier code changes.
Reviewers: @tthompson-okta @joelfranusic-okta 
FYI: @mystiberry-okta
> OKTA-76866 Reduce information in the id_token claim if a token claim was requested

- _source/docs/api/resources/users.md
@karlmcguinness-okta 
Does this look ok? Or anyone else I should add to this PR?  Thanks!
> Adding callout about escaping custom attributes for OKTA-80022

- docs/api/postman/client-registration.json
Related-to: OKTA-81944
Primary Reviewer: @tthompson-okta @mystiberry-okta 
> add initiate_login_uri into postman for client registration

- _source/docs/guides/oan_guidance.md
updated from oan@okta.com  --> developers@okta.com
> updated email

- docs/api/postman/client-registration.json
Make sure that create/update of OAuth Client are valid requests.
Related to: OKTA-81319
@federations-okta 
> Update postman collections for client registration.

- _source/docs/guides/oan_guidance.md
I'm not the best w/ tables. Is there a way to put text on different lines within the tables? could not find a way to do this.
> updates to provisioning section for SCIM

- _source/docs/guides/oan_guidance.md
> minor updates to provisioning section

- _source/docs/api/postman/client-registration.json
Re-update client registration postman collection in the correct place, since https://github.com/okta/okta.github.io/commit/923dd4cb1d7041b60ca8c601057f6e6f4b97d30e was overwritten.
@joelfranusic-okta @mystiberry-okta @federations-okta 
Related to: OKTA-81319
> Updates client-registration postman in correct place.

- _source/docs/api/getting_started/design_principles.md
- _source/docs/api/resources/oidc.md
Api docs for request debugging using the X-Okta-Request-Id.
Resolves: OKTA-84899
Primary Reviewer: @mystiberry-okta @hassenkaraa-okta 
Reviewer : @federations-okta
> Add X-Okta-Request-Id header to responses Resolves: OKTA-84899

- _source/docs/api/getting_started/design_principles.md
- _source/docs/api/resources/oidc.md
This reverts commit b6ea3694c7f50c9b3d498399686d97f41a2474a9.
Mysti merged too soon. Will merge next week.
> Revert "Add X-Okta-Request-Id header to responses Resolves: OKTA-84899"

- _source/docs/guides/social_authentication.md
Added Microsoft to our social auth guide
Reviewers: @federations-okta @mystiberry-okta @karlmcguinness-okta @hassenkaraa-okta @slee-okta
> OKTA-84215

- _source/docs/api/postman/idps.json
- Updated idps.json with Microsoft IdP information.
Primary reviewer: @mystiberry-okta @tthompson-okta 
Secondary reviewers: @joelfranusic-okta @karlmcguinness-okta @hassenkaraa-okta @federations-okta
> OKTA-83346

- _source/docs/api/resources/oidc.md
Add documentation for how to perform ID token validation.
This is based on @mystiberry-okta's branch (oidc_update_mysti) since it touches the same file.
@karlmcguinness-okta @hassenkaraa-okta @joelfranusic-okta @federations-okta
> OKTA-84163

- _source/docs/api/getting_started/api_test_client.md
- _source/docs/api/resources/idps.md
- _source/docs/api/resources/oidc.md
Had a weird git pull request so created a new one. The previous one: https://github.com/okta/okta.github.io/pull/202/commits/3e24e409c51ae3a70e3fb0135ed343d19ba07690
> Oidc update safety

- _source/docs/api/resources/social_authentication.md
Just adding a file to resources for new ToC
> Adding soc auth to resources

- _source/docs/api/resources/oidc.md
API docs for adding none to supported token end point auth methods
Reviewer: @hassenkaraa-okta @mystiberry-okta 
Resolves: OKTA-85766
> Add none to supported token end point auth methods RESOLVES: OKTA-85766

- _source/docs/api/resources/oidc.md
API docs for adding refresh token as supported grant type
Primary Reviewer: @hassenkaraa-okta @mystiberry-okta 
Reviewer: @federations-okta 
Resolves: OKTA-85768
> Adding refresh_token as supported grant type Resolves: OKTA-85768

- _source/docs/api/resources/policy.md
> Policy as generated

- _source/docs/api/resources/oidc.md
@ashishgupta-okta as discussed, I fixed the typos we found. Can you verify? Thanks!
> Fixed typos in oidc param table

- _source/docs/api/resources/oidc.md
- _source/docs/api/resources/sessions.md
- Updated AMR values for OIDC according to the newest spec: https://tools.ietf.org/html/draft-jones-oauth-amr-values-05
Primary reviewer: @tthompson-okta 
Secondary reviewers: @federations-okta @mystiberry-okta @karlmcguinness-okta
> OKTA-86328

- _source/docs/guides/okta_sign-in_widget.md
@Ujjwalreddy-okta can you review and okay the changes that you requested? OKTA-87063
(Is UP the right Team?)
> update 1.0.2 links to 1.2

- _source/docs/api/resources/authn.md
@edjohns-okta Here is the change you suggested. 
Should anyone else on Fed team review, @cwu-okta ?
> Doc recoveryState example typo

- _source/docs/api/resources/idps.md
- Added DISABLED as an option for account linking for social auth
Primary reviewer: @mystiberry-okta @tthompson-okta 
Secondary reviewers: @federations-okta
> OKTA-75653

- _source/docs/api/resources/oidc.md
@tthompson-okta I'd missed this entirely, but found your original comment and added it back in. I'd love to ship this for Preview if it's okay. Thanks!!!!
> typo and missing state text

- _source/docs/guides/okta_auth_sdk.md
@mystiberry-okta @joelfranusic-okta @raphaellondner-okta @slee-okta @karlmcguinness-okta @rchild-okta @larsjohansen-okta @stsai-okta 
This will serve as our docs for [the okta-auth-js sdk](https://github.com/okta/okta-auth-js).
> Added more docs for okta-auth-js

- _source/docs/api/resources/users.md
This has already been approved in the JIRA: https://oktainc.atlassian.net/browse/OKTA-83631
> clarify user status values

- _source/docs/api/resources/oidc.md
Need a ship it ASAP. Just marked nonce as required.
https://oktainc.atlassian.net/browse/OKTA-89243
> nonce is required in oidc.md

- _source/docs/api/getting_started/design_principles.md
- _source/docs/api/resources/users.md
@raphaellondner-okta  Here are the changes you requested about search operators. I'm verifying with Fed team as I'm not sure the list of non-supported items is correct.
> draft of changes for operators in search

- _source/docs/api/resources/oidc.md
Primary Reviewer: @tthompson-okta @mystiberry-okta 
> PKCE for OAuth

- _source/docs/api/resources/oidc.md
@cwu-okta @mohitchugh-okta Did this right away, since it was a short, one-line change. Is it cool?
> Changed nonce description per OKTA-89966

- _source/docs/api/resources/apps.md
- _source/docs/api/resources/oidc.md
@ashishgupta-okta @cwu-okta
Very simple change for OKTA-86962. Changed the sample return to false for WantAuthnRequestsSigned. Please give ship by tomorrow (5/24/16) for the preview release.
> Authn requests

- _source/docs/api/resources/oidc.md
@larsjohansen-okta  can you check this? should I just remove that whole paragraph?
> remove unsupported URL-encoded auth method

- _source/docs/api/resources/oidc.md
- add some missing error codes
- move OpenID Connect Discovery up one level out of OAuth 2.0 Endpoints
@mystiberry-okta @federations-okta
> Clean up OIDC docs

- _source/docs/guides/oan_guidance.md
changed links to new SCIM guide http://developer.okta.com/docs/guides/scim_guidance.html
> updated links in provisioning section

- _source/docs/api/resources/oauth2.md
@tthompson-okta  you commented on this work for OKTA-88783 once before, but then we split up oidc.md into two docs, and the conflict was so messy that I nuked that PR and redid these minor changes. Can you review?
Previous PR: https://github.com/okta/okta.github.io/pull/237
@royalchan-okta you should probably give the file a once-over to ensure I haven't made any git-related mistakes. Thanks!
> doc 88783 explain offline access req

- _source/docs/api/resources/okta_signin_widget.md
- _source/docs/guides/okta_sign-in_widget.md
@Ujjwalreddy-okta  and @raphaellondner-okta  Please review--did I catch all instances of 1.3.2? Did I break anything?
Also @Ujjwalreddy-okta  don't forget to send me the two links to those property files.
> change 1.3.2 > 1.2.0, fix broken links

- _source/docs/api/resources/system_log.md
Someone should take this and finish it. It should not be merged in current state!
@guyzehavi-okta @jeffpeeler-okta
> API Doc for SysLog2 System Log

- _source/docs/api/resources/social_authentication.md
A link was missed when creating the OAuth2 page.
Primary reviewer: @mystiberry-okta 
> Fixes link on social auth page.

- _source/docs/api/resources/system_log.md
In https://github.com/okta/okta.github.io/pull/266/files I moved the note to the wrong location. This is just correcting that error.
> move note to requested location

- _source/docs/api/resources/oauth2.md
> Fixed oauth.md typos and bugs

- _source/docs/api/resources/oidc.md
Reviewer: @mystiberry-okta @federations-okta
> Add client_id param to /oauth2/v1/keys

- _source/docs/guides/scim_guidance.md
Runscope made a special link for Okta
> Fix Runscope link

- _source/docs/api/resources/oidc.md
Changes verified in local build. I should have found these minor issues in https://github.com/okta/okta.github.io/pull/273
> minor format fixes, no tech content changes

- _source/docs/api/resources/oauth2.md
@larsjohansen-okta here's the recreation of PR 239 (sounds like a country song!). Please review.
> replace text that was lost from PR 239

- _source/docs/api/resources/users.md
> Fix syntactical error in doc.

- _source/docs/api/resources/apps.md
@cwu-okta Please review. I can republish site as soon as we merge this.
> remove KEY_ROLLOVER ff name from doc.

- _source/docs/guides/okta_sign-in_widget.md
@Ujjwalreddy-okta only the 2nd commit needs review. Is the note okay (since the doc will be published today, but the new version won't be available for Prod until Monday? Or should I not publish this until Monday and remove the note?)
@eklein-okta feel free to suggest any changes to the note text...
> Doc signin bump 133

- _source/docs/api/resources/oidc.md
The prod doc also mentions the limit: 
https://support.okta.com/help/articles/Knowledge_Article/Using-OpenID-Connect
(bottom of the topic, step 5).
Because there were three "notes" in a row, I had to turn them into a bullet list. The first two bullet's content shouldn't have changed/is unrelated to groups claim.
@royalchan-okta or @ashishgupta-okta is this okay to ship? Preview RN go out tonight...
> add groups claim limit for 88276

- _source/docs/api/getting_started/okta_expression_lang.md
> Fix incorrect md on Okta Expression Language page

- _source/docs/guides/scim_guidance.md
http://pages.okta.com/DeveloperSCIM.html
> updated links for SCIM dev program sign up

- _source/docs/api/postman/users.json
> Add suspend/unsuspend operations to users postman collection.

- _source/_includes/header.html
- _source/docs/platform-release-notes/platform-release-notes.md
- _source/docs/platform-release-notes/platform-release-notes2016-23.md
- _source/docs/platform-release-notes/platform-release-notes2016-24.md
- _source/docs/platform-release-notes/platform-release-notes2016-25.md
Reviews come from an email query. Mysti will update as needed from those responses.
Do not merge until after this week's preview goes out.
> Rn 2016 26

- _source/docs/api/resources/_site/authn.html
- _source/docs/api/resources/authn.md
@edjohns-okta can you approve these changes for OKTA-94177 (was OKTA-92800).
Do you think I should add to the text for the error code itself? Currently it's this:
"E0000014	Update of credentials failed.	403"
Thanks!
> error code fix for password complexity

- _source/docs/api/resources/oauth2.md
Primary Reviewers: @royalchan-okta @mystiberry-okta 
@federations-okta 
OKTA-94115
> Add expires_in to fragment response for access token

- _source/docs/platform-release-notes/platform-release-notes.md
it looked awful, I couldn't leave it be.
> Changed 'this guide' to Okta Sign-In Widget

- _source/docs/api/resources/oidc.md
Reviewer: @mystiberry-okta @federations-okta
> Access Token for OIDC

- Gemfile.lock
- _source/_plugins/tocGenerator.rb
- _source/assets/css/layout-docs.scss
- _source/assets/js/docs.js
- _source/docs/api/resources/oauth-clients.md
- _source/docs/api/resources/oauth2.md
Reviewer: @mystiberry-okta @federations-okta 
It is based on the oauth2-beta branch so only the last commit is for the access token.
@mystiberry-okta when the @royalchan-okta 's PR will be merged into master? Should my changes based on his PR?
> Access Token for OAuth2

- _source/docs/platform-release-notes/platform-release-notes.md
This isn't great information architecture, but making the read-once-and-discard sections smaller will help readability.
> rn format change

- _source/docs/api/resources/authn.md
@edjohns-okta I made up the descriptions for excludeUsername and the two age properties. Can you review them?  The rest is copy-paste from the RN. This should have been done Mon/Tues, sorry I let it slip.
@karlmcguinness-okta fyi.
> api doc for 88985

- _source/docs/platform-release-notes/platform-release-notes.md
- _source/docs/platform-release-notes/platform-release-notes2016-27.md
- _source/docs/platform-release-notes/platform-release-notes2016-28.md
Fixing first heading ("expires_in" is very very small)
Fixing file names so they all follow the same convention. Will delete errant files shortly.
> RN 2016-29 updates

- _source/docs/guides/okta_sign-in_widget.md
Resolves: OKTA-96315
The current 1.4.0 links 404
@mystiberry-okta @rchild-okta
> Fix okta-signin-widget 1.4.0 links

- _source/docs/api/resources/oidc.md
Fixed typos and removed email_verified
> doc-87540-oidc-tweaks

- _source/docs/api/resources/idps.md
IDP api changes for Extensible user matching
Primary Reviewers: @larsjohansen-okta @mystiberry-okta 
Reviewers: @federations-okta
> IDP Api changes for Extensible User Matching OKTA-93061

- _source/docs/api/resources/oauth2.md
Link to spec defining acceptable scopes.
Primary reviewer: @yuliu-okta 
@federations-okta 
Related to: OKTA-95050
> Describe form of allowable custom scopes.

- _source/docs/platform-release-notes/platform-release-notes.md
- _source/docs/platform-release-notes/platform-release-notes2016-29.md
Version being distributed for review.
> Rn 2016.30

- _source/docs/platform-release-notes/platform-release-notes.md
> fix broken links in 2016.30

- _source/_data/docs.yml
- _source/docs/guides/saml_guidance.md
Split among SAML, SCIM, and everything else.
> added headings to guides ToC

- _source/docs/api/resources/social_authentication.md
> add instruction to choose implicit checkbox

- _source/docs/api/resources/policy.md
Straight copy from the release notes. @edjohns-okta  I'm merging this for today's site refresh, but please feel free to leave feedback and I'll address it.
I moved one section, so the diff is hard to read.
> add expand rules to get policy

- _source/docs/guides/scim_guidance.md
SCIM Guidance page updated to reflect the changes for filter string generated for different unique field names.
[OKTA-83183](https://oktainc.atlassian.net/browse/OKTA-83183)
> Updated SCIM Guidance page for filtering on username

- _source/docs/api/resources/system_log.md
bug number is really 97609 (the branch name refers to a dupe bug).
> fix log query param details

- _source/docs/platform-release-notes/platform-release-notes.md
https://oktainc.atlassian.net/browse/PDOC-9
> remove dates from platform RN

- _source/docs/api/postman/apps.json
And removed Template SAML from the collection.
Pictures for better visuals:
Resolves: [OKTA-97380](https://oktainc.atlassian.net/browse/OKTA-97380)
@mystiberry-okta @bng-okta please review.
> Added Custom SAML and SWA to Postman collection

- _source/docs/api/resources/oidc.md
Trevor spotted the workflow info that shouldn't be in oidc.md. 
Resolves: OKTA-98225
> remove bad flow info from oidc.md

- _source/docs/api/resources/oidc.md
We missed this link to the content we just removed.
> remove a bad link from oidc.md

- _source/docs/api/resources/apps.md
Updated examples using Template SAML to use the custom SAML app instead.
Resolves: [OKTA-97383](https://oktainc.atlassian.net/browse/OKTA-97383)
@mystiberry-okta @bng-okta please review.
> Updated examples using Template SAML

- _source/docs/api/resources/oauth2.md
Related: OKTA-93308
Reviewer: @mystiberry-okta @federations-okta
> scope response parameter for OAuth2

- _source/docs/api/resources/oauth2.md
- _source/docs/api/resources/oidc.md
Primary reviewers: @larsjohansen-okta @mystiberry-okta 
> Adds information on the groups claim in the access token.

- _source/docs/api/resources/oauth2.md
Related: OKTA-92081
Primary Reviewer: @royalchan-okta @mystiberry-okta 
> Change the OAuth2 introspection response

- _source/docs/api/resources/idps.md
changes for delete idp key
Primary Reviewer: @royalchan-okta 
> changes for delete key

- _source/docs/api/resources/schemas.md
> fix broken links in schema.md

- _source/docs/api/getting_started/okta_expression_lang.md
@brianzuzga-okta Can you review these changes for OKTA-78343? Thanks!
> typos in EL Country Code conversion functions

- _source/docs/api/resources/oidc.md
@raphaellondner-okta , I wasn't sure if I needed to add any text about not knowing which key is used, let me know if you think it still needs to be added.
This should also be reviewed by someone on @federations-okta (Royal? Yu?) to ensure I haven't introduced any errors.
> remove x5c and x5t from oidc doc

- _source/docs/guides/scim_developer_program.md
- _source/docs/guides/scim_guidance.md
@bng-okta can you review these changes for your OKTA-95480? Thanks!
> replace 3-legged w/auth. code grant flow and better links

- _source/oidc_playground/playground/build_assets/assets/playground.css
- Last minute small UI fix
- @mystiberry-okta 
- @federations-okta
> Minor UI fix

- _source/docs/guides/scim_developer_program.md
- _source/docs/guides/scim_guidance.md
Updates requested by David & Vivek. for OKTA-99212
> update SCIM doc

- _source/_docs/api/resources/schemas.md
API changes for remove UD property 
Primary Reviewer: @royalchan-okta  @mystiberry-okta 
Reviewers : @federations-okta
> OKTA-96281

- _source/_standards/SCIM/index.md
- _source/_standards/SCIM/scim_developer_program.md
- _source/_use_cases/integrate_with_okta/index.md
@dhorvath Here are the changes you requested (plus one little edit that caught my eye) for OKTA-100206. Please review and let me know if it's okay.
> doc-100206-scim

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-34.md
Don't merge until teams verify content.
@jpf This is my first PR in the new environment, if the location looks weird to you, ping me!
> first draft RN 2016.35

- _source/docs/api/resources/oauth2.md
Primary Reviewer: @yuliu-okta 
@federations-okta @mystiberry-okta 
Related to: OKTA-99238
> Change /as/ to /oauth2/ in the issuer url.

- _source/assets/js/docs.js
@karlmcguinness-okta for your review
> Fix scrolling for anchor links

- _source/_docs/api/resources/oauth2.md
@jpf found my syntax problems. fixed tags. Thank you!
> fixed beta tag problem

- _source/_3rd_party_notices/Okta_Cloud_Provisioning_Connector_Tool.md
Closing PS-100. @mystiberry-okta for your review, please merge if you don't see any issues with the change.
> Rename 3rd party license

- _source/_docs/api/resources/social_authentication.md
@frankmontanaro-okta  This PR is for your OKTA-91549, except I didn't do the last part relating to response_mode, because I'm not sure what we need to add. I'd like to move that part to a new JIRA for @larsjohansen-okta  or one of the developers, unless you can explain what I should add here for response_mode.
So, please verify my changes, and let me know whether it's okay to push the response_mode out to another JIRA (or, maybe the fix is simple and I just didn't get it?).  Thanks!
Forgot to say, the first items are already done and published, you can view them here:
http://saml-doc.okta.com/IdentityProvider_Docs/Facebook_Identity_Provider_Setup.html
> doc updates okta-91549

- _source/_standards/SCIM/index.md
- _source/_standards/SCIM/scim_developer_program.md
Fixes OKTA-100775 and OKTA-100771
> SCIM bug fixes

- _source/_standards/SCIM/index.md
- _source/_use_cases/integrate_with_okta/index.md
Fixes OKTA-100332. Don't merge until @dhorvath responds to query about change in text.
> updates to SCIM doc

- _source/_docs/platform-release-notes/platform-release-notes2016-35.md
MD file accidentally removed (?).
> missing file

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-36.md
> rn 2016-37

- _source/_standards/SCIM/index.md
Don't push this until you hear back from David about client credential flow. See comments in https://oktainc.atlassian.net/browse/OKTA-102157
> updating two flows we don't support for SCIM

- _source/_docs/api/resources/apps.md
changes for Key sharing
Primary Reviewer: @mystiberry-okta  @yuliu-okta 
Reviewers : @federations-okta
> changes for Key sharing

- _source/_code/javascript/okta_sign-in_widget.md
- _source/_code/javascript/okta_sign-in_widget_ref.md
Removed unnecessary parameters, split OAuth and social providers documentation and clarified some OIDC/OAuth parameters
> OSW documentation update to v1.6.0

- _source/_docs/platform-release-notes/platform-release-notes.md
> Doc rn 2016 40

- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
Resolves: OKTA-95163
@rchild-okta @raphaellondner-okta @mystiberry-okta
> Add access tokens and auth codes in okta-auth-js

- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
- _source/_docs/platform-release-notes/platform-release-notes.md
This reverts commit 78eaa185f4b6ca77f475acfce7e439eebf144df5.
Per Reman Child
@rchild-okta or @lboyette-okta  can you confirm this is the right thing for me to do? I'll merge, fix the RN, and republish as soon as I get the okay.
> Revert "Add access tokens and auth codes in okta-auth-js"

- _source/_reference/okta_expression_language/index.md
I also ordered the string functions in alpha order.
@donwoods-okta  and @eklein-okta can you review? Needs to be published by Wed. so RN link will work. THANKS!
> add new EL string functions

- _source/_docs/api/resources/idps.md
Are the new operations in the right place?
Anything missing? 
Any extra explanations or gotchas needed?
> add list users, delete users for idps

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/idps.md
Partial fix of links, more to come. Don't want to leave this merge hanging and create unnecessary manual merges.
> fixing some links

- _source/_docs/how-to/updating_saml_cert.md
@cwu-okta @danielzeller-okta @vladdha-okta @mystiberry-okta Please check this PR.  As soon as it's okay, we can rebuild the site and send it out for a more general review.
> With Hector's changes

- _source/_docs/how-to/updating_saml_cert.md
Just merging these small changes without further review...
> Cindy's final review changes

- _source/_includes/sidebar.html
@mystiberry-okta this would address the Jira mentioned above.
> OKTA-104368

- _source/_code/dotnet/sdk.md
- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/php/simplesamlphp.md
- _source/_docs/api/resources/templates.md
- _source/_use_cases/mfa/index.md
- docs/sdk/core/api.html
> removing the last of the broken links

- _source/_docs/api/resources/oidc.md
api doc changes for OKTA-102113
Primary Reviewer: @royalchan-okta @mystiberry-okta 
Reviewers: @federations-okta
> api doc changes for OKTA-102113

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-41.md
- _source/_reference/okta_expression_language/index.md
Don't merge until .42 production goes out.
> don't publish until prod!!!

- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
- _source/_docs/api/resources/social_authentication.md
- _source/_includes/sidebar.html
- _source/_sass/okta/base/_variables.scss
- _source/_sass/okta/components/_Header.scss
- _source/_sass/okta/components/_PageContent.scss
- _source/_sass/okta/components/_Sidebar.scss
- _source/_sass/okta/components/_TableOfContents.scss
- _source/_use_cases/mfa/index.md
- _source/assets/css/okta.scss
- _source/assets/js/docs.js
This PR attempts to combine #416 and #432
Changes include:
- Discarding the "hamburger" from #416 in favor of keeping the previous dropdown menu
- Updates to headings in select API documents from #432 - to fix ToC rendering 
- Disable `scrollLock()` on small screens
A preview of these changes is available at: https://frozen-ridge-22271.herokuapp.com/
> Merge ToC and sidebar

- docs/platform-release-notes/platform-release-notes.html
> update site with fixed RN heading

- _source/_docs/api/resources/oauth2.md
Small fix for headers on the oAuth2 page. @mystiberry-okta is this ok?
> fix headers for JWTs in OAuth2 doc

- _source/_sass/okta/components/_Sidebar.scss
@mystiberry-okta this should fix the regression that you found.
> `h3, ul` selector was in the wrong place

- _source/_docs/api/resources/factors.md
- _source/_reference/error_codes/index.md
E0000109 was created for OKTA-104738
- @mystiberry-okta 
Resolves: 106951
Bacon: test
> Add error code E0000109 to developer documentation

- _source/_docs/api/resources/oauth-clients.md
Docs pr for https://github.com/okta/okta-core/pull/17282
Primary Reviewers: @yuliu-okta @mystiberry-okta 
> Call out that redirect URIs may not contain a fragment component.

- _source/_docs/api/resources/system_log.md
Currently the documentation does not reflect some of the additions we have made to the API. This change brings the docs in line with the API changes.
Resolves: OKTA-106368
> Update System Log Docs

- _source/_docs/api/resources/resource-server-beta/required-config-changes-for-auth-server.md
@yuliu-okta I addressed all your comments. Had some trouble with git, so ping me right away if you see anything amiss. Looking for a shipit.
IGNORE!!!!! I found more comments from Yu.
> Fix migration doc

- _source/_docs/how-to/beta-auth-service/api-access-management-troubleshooting.md
The last section has a funky title--feel free to suggest something better.
Let me know if there's more things I should add here, I got everything in https://oktawiki.atlassian.net/wiki/pages/viewpage.action?spaceKey=eng&title=OAuth+2.0+Beta+Docs%3A+Gotchas+and+Limits+And+Limitations as of today.
> first draft gotchas

- _source/_docs/api/resources/resource-server-beta/required-config-changes-for-auth-server.md
- _source/_docs/how-to/beta-auth-service/api-access-management-troubleshooting.md
- _source/_docs/how-to/set-up-auth-server.md
Anyone on @federations-okta  can review: I just added the beta tags to our new topics.
> add beta tag to three new auth. server topics

- _source/_code/javascript/okta_sign-in_widget_ref.md
> Add additional res.statuses to oktaSignIn.renderEl

- _source/assets/css/page-blog.scss
@jpf fixes the styling issue on individual blog posts
> change margin on blog posts for title and avatar

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-45.md
Waiting for approval from RN email list.
> RN for 2016.46

- _source/_docs/api/resources/authn.md
@johngronberg-okta @authteam-okta This is just one step in the work for OKTA-106836, but since it's swapping the order of operations and model and the file is over 5,000 lines long, wanted to check in this big change, so that anyone else modifying the file won't hit a conflict.  
We expect to change the order of all the api resource topics from Model/Operation to Operation/Model in the coming weeks.  
It also includes a little "getting started" section to help drive people to SIW.
> check in big re-ordering to prevent future conflicts.

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-46.md
No comments on circulated draft, so merging this baby!
> first draft 2016.47 RN

- _source/_docs/api/resources/oidc.md
doc changes for OKTA-106645
@royalchan-okta @mystiberry-okta 
> doc changes for OKTA-106645

- docs/api/resources/oauth2.html
> refresh site for label error

- _source/_docs/api/resources/social_authentication.md
@danielzeller-okta can you review these changes? Thanks!
> Correct field labels in Social Auth dev doc

- _source/_use_cases/integrate_with_okta/index.md
@vladdha-okta or @karanharibhakti-okta  can you verify this change is correct? I didn't include a "why" because I don't know the "why," but not sure you need it. Happy to add that, though, if you have it.
Also, please use the github review function by clicking the green "Review Changes" button instead of just adding comments. Okta wants to be able to find all reviews in the same place for compliance.
> SWA-only OAN apps special process

- _source/_docs/api/resources/oidc.md
@yuliu-okta and optionally @karlmcguinness-okta  can you review my changes? Please use the Review button instead of just leaving comments (Vicky/Pam/Becky have requested we do this for compliance with compliance). Thanks! I didn't create a table because the content didn't really look scannable, push back if you think it should be in a table, or if there are related subtleties that are missing.
> thin/fat id_token matrix

- _source/_docs/api/resources/factors.md
This change will adding the necessary documentation required to use Factors API for Voice Call MFA factor
> WIP Voice Call Factors API doc Resolves: OKTA-104091

- _source/_docs/api/resources/factors.md
This change will fix the unsupported update="true" for Voice Call MFA Factor
> Fix Voice Call Doc API Resolves: OKTA-109039

- _source/_docs/api/resources/authn.md
Needs review, especially the sample request and response I added. Used postman to create it.
> doc OKTA-106836

- _source/_docs/api/resources/users.md
- docs/api/postman/users.json
@mystiberry-okta @georgekwon-okta Please review.
FYI: @keithchin-okta @daytonwilliams-okta @donwoods-okta 
Resolves: OKTA-94138
> Add user delete operation to users API documentation and postman collection

- Gemfile.lock
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-47.md
Exception to Review button because reviewers don't all have access to github.
> rn 2106.49 1st draft

- _source/_docs/api/resources/authn.md
- *Added section for enroll and verify API details for U2F factor*
- *Also fixed references to rain.okta1.com and changed them to your-domain.okta.com*
Please review @mystiberry-okta @tthompson-okta
> API doc for U2F factor enroll and challenge in authentication API

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
Changes for well known endpoint for API access management
@larsjohansen-okta @mystiberry-okta 
> Changes for well known endpoint for API access management

- _source/_docs/api/getting_started/api_test_client.md
- _source/_docs/api/resources/authn.md
- _source/_docs/api/resources/users.md
Fixes to source. if you roll back the publication of 2016.49, don't roll back this commit.
> build revealed a few issues

- _source/_docs/api/resources/authn.md
This change will add AuthN API documentation for Voice Call Factor .  The documentation has been added for the following flows
Enrollment 
Activation 
Verification
Password Reset Flows
> Document Voice Call for AuthN API Resolves: OKTA-109300

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
@yuliu-okta Please check this carefully, especially the description in step 4 compared to the sentence that starts "Step 4 uses..."  I'm not sure whether they are contradicting each other.
Thanks!
> updating key rollover for oauth 2.0

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-49.md
Waiting for comments from email dist. list.
> RN 2016.50

- _source/_docs/api/postman/users.json
- _source/_docs/api/resources/users.md
Added description on the API call to clear user sessions. 
Updated the users postman collection with the new call.
Resolves: OKTA-99060
Reviewers:
@srinivasanagandla-okta @tthompson-okta @mystiberry-okta
> Added description of clear sessions call.

- _source/_docs/api/postman/authentication.json
- _source/_docs/api/resources/authn.md
Updated the documentation with sample of the poll endpoint, request and response.
Updated the postman collection with information about the endpoint.
Resolves: OKTA-109889
Reviewers:
@mystiberry-okta @gauthamgowrishankar-okta @tthompson-okta
> Added description of activation poll method.

- _source/_docs/api/resources/social_authentication.md
Small changes for example.
@mystiberry-okta The document at http://saml-doc.okta.com/IdentityProvider_Docs/Google_Identity_Provider_Setup.html also need to add a step to enable Google+ API, can you please help on it?
Reviewer: @mystiberry-okta @federations-okta
> Fix doc for social auth

- _source/_docs/api/resources/system_log.md
@guyzehavi-okta or anyone, can you review this slight expansion of the intro to system log requested by Trevor? If we can add anything more, that'd be great. Also, is it really still Beta? The admin feature is now EA.
> improve intro to system log api

- _source/_docs/platform-release-notes/paltform-release-notes2016-51.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
Waiting for feedback before merging.
> rn for 2016.52

- _source/_docs/api/resources/system_log.md
> fix beta tag in system_log.md

- _source/_docs/api/resources/authn.md
Based on Karl's comment on previous commit.
Resolves: OKTA-104925
Reviewers: @mystiberry-okta @tthompson-okta
> Makes the samples consistent with rest of the document.

- scripts/lint.sh
- Install ruby version found in .ruby-version
- Use rvm as a function instead of a command
- Install bundler again, since we'll have a new version of ruby
> Add lint.sh with code to check documentation for URL consistency

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/authn.md
- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/factors.md
- _source/_docs/api/resources/groups.md
- _source/_docs/api/resources/idps.md
- _source/_docs/api/resources/roles.md
- _source/_docs/api/resources/schemas.md
- _source/_docs/api/resources/sessions.md
- _source/_docs/api/resources/templates.md
- _source/_docs/api/resources/users.md
- scripts/lint.sh
@mystiberry-okta for your review, this will add the `/api/v1` prefix to URLs as appropriate as well as unit test code to verify that the URLS look okay.
Please pay extra attention to the changes made in the `.md` files.
> Prefix URLs with "/api/v1" as approprate

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/idps.md
> first check-in

- _source/_reference/okta_expression_language/index.md
Primary Reviewer: @larsjohansen-okta @mystiberry-okta 
> Add EL function Arrays.toCsvString()

- docs/platform-release-notes/platform-release-notes.html
- reference/okta_expression_language/index.html
forgot to link to new content.
> updates to site

- _source/error.html
This will allow us to have a "branded" error page.
> Add error page for custom 404 error messages

- _source/_docs/api/resources/oauth2.md
API doc for Authorization Server key pinning
@yuliu-okta @mystiberry-okta 
> API doc for Authorization Server key pinning

- _source/_docs/api/resources/oauth-clients.md
Primary Reviewers: @larsjohansen-okta @richardmateosian-okta 
@federations-okta @mystiberry-okta 
OKTA-113371
> Documentation for external client_id and client_secret.

- _source/_docs/api/resources/oauth-clients.md
Primary Reviewer: @royalchan-okta @richardmateosian-okta 
> Docs for PublicClientApp status.

- _source/_docs/api/resources/oauth2.md
- _source/_includes/sidebar.html
- _source/_standards/OAuth/index.md
- _source/_standards/OIDC/index.md
- _source/_standards/SAML/index.md
- _source/_standards/SCIM/index.md
- _source/_use_cases/api_security/draft.md
- _source/_use_cases/promote-oan-integration/index.md
> add topic on marketing your OAN integration

- _source/_docs/api/resources/policy.md
@edjohns-okta and @johngronberg-okta I've made the requested lifecycle tag adjustments, and also moved the operation to the top as we did with the other published topics. Please review.
> lifecycle tags for policy

- _source/_standards/SCIM/index.md
Requested by David H. Should have been removed already.
> remove bogus link

- _source/_docs/api/postman/authentication.json
- _source/_docs/api/postman/factors.json
- _source/_docs/api/postman/users.json
- _source/_docs/api/resources/authn.md
- _source/_docs/api/resources/users.md
@joelfranusic-okta or @johngronberg-okta  I need a close review of these changes. I should only be changing answers that contain part of the question.
> goodbye cowboy dan

- _source/_posts/2015-12-02-tls-client-authentication-for-services.md
Unnecessary notice footer
@rchild-okta
> Remove unnecessary notice

- _source/_plugins/ApiTags.rb
> Allow API lifecycle status tags to render in tables

- _source/_standards/SCIM/index.md
@bng-okta Can you please review?
> filtering changes for SCIM

- _source/_docs/api/resources/oauth2.md
OKTA-113844
@larsjohansen-okta @richardmateosian-okta
> Add refresh token revocation implicit triggers

- _source/_docs/api/resources/system_log.md
Updating the documentation for syslog 2 API.
Resolves: OKTA-111800
> Update Documents for Syslog 2 API

- _source/_docs/api/resources/users.md
- Documents new query param on the clear sessions endpoint which revokes OAuth tokens
@royalchan-okta  @richardmateosian-okta 
> clear sessions revokes tokens

- _source/_posts/2015-05-08-software-engineering-design-principles.md
Only found one instance of the former, so we can now say that we use it totally consistently!
> Changing 'backward compatible' to 'backwards compatible'

- _source/_docs/how-to/byo_saml.md
@cwu-okta @yuliu-okta @mystiberry-okta @richardmateosian-okta 
This is the technical doc review for BYO Cert. Please review the following:
1. Is the procedure correct?
2. Is anything missing?
3. Should there be any more detail in the introduction or any dire warnings?
Please note that the links to the APIs are NOT correct at this point in time. Don't worry about them for this review.
Thanks,
Evan
> Doc review for SAML BYO-Cert OKTA-115500

- _source/_docs/api/resources/idps.md
duplicating https://github.com/okta/okta.github.io/pull/708 since it was accidentally merged early and reverted
> REOPENED: documentation for force link to social idp

- _source/_docs/api/resources/roles.md
this is a similar change to #253 
@alifatolahi-okta 
@brianzuzga-okta
> removing last app target now throws an exception

- _source/_docs/api/resources/policy.md
Resolves: OKTA-99063
Bacon: test
> Update the Multifactor Policy section of the Policy API document

- _source/_posts/2017-03-30-react-okta-sign-in-widget.md
Please review @leebrandt. I basically fixed a couple of links and made one of your images smaller so it's not so gigundous.
> Fix minor issues in React post

- _source/_posts/2017-03-16-spring-boot-saml.md
See https://github.com/oktadeveloper/okta-spring-boot-saml-example/pull/2 for details.
> Update with PR from @AlexeySoshin 

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-15.md
resolves: OKTA-123085
test: bacon
> RN source for 2017-16

- _source/_posts/2017-03-27-angular-okta-sign-in-widget.md
- _source/_posts/2017-04-17-angular-authentication-with-oidc.md
> Fix double curly braces in code listings

- _source/_docs/api/resources/apps.md
@annaluo-okta , @tthompson-okta , @swastimishra-okta , please review this doc for OKTA-123576.
1. I added a note explaining when to use the overrides which is too generic. Please provide additional explanation of when someone should use these. 
2. I guessed Nillable=True and Unique=False for all four, and that the datatype is string.
3. Can I use trevor's example from the JIRA as the request example?
> override settings in apps api

- _source/_code/php/quickstart-signin-widget.md
> Adds Quickstart for Sign-In Widget using PHP

- _source/_posts/2015-05-08-software-engineering-design-principles.md
- _source/_posts/2016-03-22-use-kentor-authservices-with-okta.md
- _source/assets/css/page-blog.scss
> Fix text overflow on mobile

- .travis.yml
- README.md
- _source/templates/api-endpoint.md
- package.json
- scripts/helpers.sh
- scripts/lint.sh
- scripts/publish.sh
- scripts/selenium.sh
- scripts/setup.sh
- scripts/travis.sh
- tests/selenium/conf.js
- tests/selenium/spec/page-layout-browser-size-tests.js
Two commits:
1. **Adds TravisCI with build and e2e testing**
- TravisCI config file
- SauceLabs for master/topic branches, phantomjs for pull requests, and Chrome
for local testing
- Swapped out default CLI reporter with one that's more informative
- Fixed broken selenium tests, and added function for ignoring tests that
will never pass in phantomjs
2. **Updates bacon ci scripts to work with Travis changes**
- Moves ci-update-package and ci-pkginfo out of dependencies
- Refactors linting logic and shared functions into helpers.sh
- Fixes linting logic, which didn't actually error on linting mistakes
- Adds linting to Travis script
* [OKTA-124739](https://oktainc.atlassian.net/browse/OKTA-124739)
- @lboyette-okta @sergiymelnyk-okta
> Adds Travis CI

- _config.yml
- _source/_layouts/blog_index.html
- _source/assets/css/page-blog.scss
Add pagination for blog entries. Set to 10 per page in `_config.yml`.
Learned how to do it from https://jekyllrb.com/docs/pagination/.
- DevEx
> Add pagination for blog entries

- .github/PULL_REQUEST_TEMPLATE.md
- tests/selenium/spec/check-upstream-docs-tests.js
- Updates PR template with new process changes. Specifically, we no longer need to call out approvals and squashing (taken care of gating checks), and added a note about adding tests.
[x] Other
- @jmelberg-okta
> Updates PR template with new process

- _source/_use_cases/authentication/session_cookie.md
Change deprecated phrasing on session cookies page
* [OKTA-112190](https://oktainc.atlassian.net/browse/OKTA-112190)
> change deprecated phrasing on session cookies page

- _source/_docs/api/resources/factors.md
- Four examples have errors in the request URLs, indicating the path `users/users`.
* [OKTA-125575](https://oktainc.atlassian.net/browse/OKTA-125575)
- @mystiberry-okta
> :bug: Fixes URL in request samples

- _source/_docs/api/resources/oidc.md
* [OKTA-89621](https://oktainc.atlassian.net/browse/OKTA-89621)
@rchild-okta
> how to change token_endpoint_authentication

- _source/_docs/api/getting_started/getting_a_token.md
- Support requested clarity around service accounts/user perm dictates api token perms. They read our recent revision and asked for further changes.
* [KNOW-90](https://oktainc.atlassian.net/browse/KNOW-90)
@johngronberg-okta  since you worked on this file before, want to make sure it's okay to modify.
> request from support KNOW-90

- _source/_reference/okta_expression_language/index.md
- Remove an incorrect note that causes cases.
* [OKTA-116016](https://oktainc.atlassian.net/browse/OKTA-116016)
@jakubvul-okta or @johngronberg-okta
> remove incorrect note

- _source/_docs/api/resources/oauth2.md
Support requested a resource owner password flow example request and response.
* [OKTA-124310](https://oktainc.atlassian.net/browse/OKTA-12431)
@johngronberg-okta
> add resource owner password flow example req and resp

- _source/_docs/api/resources/oauth2.md
- _source/_docs/platform-release-notes/platform-release-notes2017-18.md
- Fixes image url in release notes to include new formatting
- Updates CURl request formatting in `oauth2` documentation
> Fixes image url and CURL request formatting

- _source/_docs/platform-release-notes/platform-release-notes.md
* [OKTA-125862](https://oktainc.atlassian.net/browse/OKTA-125862)
@nandagopalseshagiri-okta plus email approval from Security. Please use the approval button instead of a lgtm message.
> add hf for okta-125862

- _source/_posts/2017-05-10-developers-guide-to-docker-part-1.md
- blog/2017/05/10/developers-guide-to-docker-part-1.html
- blog/index.html
- docs/platform-release-notes/platform-release-notes.html
- feed.xml
- sitemap.xml
- Fixed typo in Docker post
- [Blog Post Google Doc](https://docs.google.com/document/d/1ENj_9EjBqMtmycwqWFUAniuawjGmZKELzeTiXulcFzI)
> Fixed typo in Docker post

- scripts/publish.sh
RESOLVES OKTA-126146
- Will now deploy to [the staging site](https://d384qaxymvjmjw.cloudfront.net/) when PRs are merged into the `weekly` branch
* [OKTA-126146](https://oktainc.atlassian.net/browse/OKTA-126146)
@lboyette-okta
> Deploys to staging site on updates to weekly

- _source/_docs/platform-release-notes/platform-release-notes.md
- code/java/index.html
- code/php/index.html
- code/python/index.html
- docs/platform-release-notes/platform-release-notes.html
- documentation/index.html
- feed.xml
- sitemap.xml
* [OKTA-126227](https://oktainc.atlassian.net/browse/OKTA-126227)
@rchild-okta Not sure if all the index files should have content changes.
> add one vertical space

- _source/_code/dotnet/okta-oauth-aspnet-codeflow.md
- _source/_code/dotnet/okta-oauth-spa-authjs-osw.md
- _source/_code/dotnet/okta-oidc-spa-osw-aspnet.md
- _source/_code/dotnet/powershell.md
- _source/_code/dotnet/sample_application.md
- _source/_code/dotnet/sdk.md
- _source/_code/java/okta-aws-cli-assume-role.md
- _source/_code/java/okta-openidconnect-appauth-sample-android.md
- _source/_code/java/oktasdk-java.md
- _source/_code/java/spring_security_saml.md
- _source/_code/php/quickstart-signin-widget.md
- _source/_code/php/simplesamlphp.md
- _source/_code/python/pysaml2.md
- _source/_code/python/sdk.md
- code/dotnet/index.html
- code/java/index.html
- code/php/index.html
- sitemap.xml
- Fixes sort issue where different computers would generate different orderings
* [OKTA-126601](https://oktainc.atlassian.net/browse/OKTA-126601)
@lboyette-okta
> Adds weight to code pages for deterministic sort

- README.md
Updated ReadMe instructions
* [OKTA-125390](https://oktainc.atlassian.net/browse/OKTA-125390)
- Read it in GitHub
> Added new instructions

- _source/_reference/okta_expression_language/index.md
@larsjohansen-okta @yuliu-okta @cwu-okta @mystiberry-okta @jakubvul-okta 
Here is the first draft of the getFilteredGroups documentation on the Okta Expression Language page. In addition to any general comments, please check the following:
1. Is it technically correct?
2. Does it address the use case adequately?
3. Is the location and style okay? Mysti and Jakub, please let me know if I missed any new conventions.
4. Are there any typos (gasp!)?
Thanks,
Evan
> Doc for OKTA-124721 getFilteredGroups

- _source/_docs/api/resources/apps.md
Incomplete first draft for property bag. @larsjohansen-okta note the XX for what the overall size limit is for the schema. I should be able to provide the request and response, if I get stuck I'll ask for help.
In addition to correcting any errors, think about what all might be missing that would help the customer. Should I link to this from expressions page, or from oauth-clients page?
* [OKTA-124720](https://oktainc.atlassian.net/browse/OKTA-124720)
@johngronberg-okta @larsjohansen-okta
> Property bag

- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-19.md
Release Notes for 2017.20 reviewed in email.
* [OKTA-126536](https://oktainc.atlassian.net/browse/OKTA-126536)
@jakubvul-okta Tech content reviewed via email.
> Release Notes for 2017.20

- docs/api/resources/apps.html
- docs/api/resources/authn.html
- docs/api/resources/events.html
- docs/api/resources/factor_admin.html
- docs/api/resources/factors.html
- docs/api/resources/groups.html
- docs/api/resources/idps.html
- docs/api/resources/oauth-clients.html
- docs/api/resources/oauth2.html
- docs/api/resources/oidc.html
- docs/api/resources/policy.html
- docs/api/resources/resource-server-beta/required-config-changes-for-auth-server.html
- docs/api/resources/roles.html
- docs/api/resources/schemas.html
- docs/api/resources/sessions.html
- docs/api/resources/social_authentication.html
- docs/api/resources/system_log.html
- docs/api/resources/templates.html
- docs/api/resources/users.html
- docs/api/resources/zones.html
- docs/platform-release-notes/platform-release-notes.html
- docs/platform-release-notes/platform-release-notes2016-index.html
- docs/platform-release-notes/platform-release-notes2017-19.html
- documentation/index.html
- reference/okta_expression_language/index.html
- sitemap.xml
- Production build, no additional changes.
* [OKTA-126537](https://oktainc.atlassian.net/browse/OKTA-126537)
@jakubvul-okta or anyone in DevEx
> Production build

- _source/_posts/2017-04-26-bootiful-development-with-spring-boot-and-angular.md
- blog/2017/04/26/bootiful-development-with-spring-boot-and-angular.html
- feed.xml
- sitemap.xml
Simplify BeerController and add missing import to Spring Boot + Angular blog post
* #844 
DevBlog team + DevEx
> Simplify BeerController and add missing import

- _source/sitemap.xml
- sitemap.xml
- Removes the fluctuating dates from the sitemap.xml
> Removes the fluctuating dates from the sitemap.xml

- _source/_docs/api/resources/system_log.md
* [OKTA-126537](https://oktainc.atlassian.net/browse/OKTA-126537)
> revert system log status change

- docs/api/resources/apps.html
- docs/api/resources/authn.html
- docs/api/resources/events.html
- docs/api/resources/factor_admin.html
- docs/api/resources/factors.html
- docs/api/resources/groups.html
- docs/api/resources/idps.html
- docs/api/resources/oauth-clients.html
- docs/api/resources/oauth2.html
- docs/api/resources/oidc.html
- docs/api/resources/policy.html
- docs/api/resources/resource-server-beta/required-config-changes-for-auth-server.html
- docs/api/resources/roles.html
- docs/api/resources/schemas.html
- docs/api/resources/sessions.html
- docs/api/resources/social_authentication.html
- docs/api/resources/system_log.html
- docs/api/resources/templates.html
- docs/api/resources/tokens.html
- docs/api/resources/users.html
- docs/api/resources/zones.html
- documentation/index.html
- sitemap.xml
- 2nd try to publish 2017.20
* [OKTA-126537](https://oktainc.atlassian.net/browse/OKTA-126537)
@rchild-okta
> Pub rn2017.20part2

- _source/_docs/api/resources/policy.md
Document the "include" element of the AuthProvider condition.
Resolves: OKTA-126461
Bacon: test
Fixup errors in the password policy settings example JSON.
Document the "include" element of the AuthProvider condition.
* [OKTA-126461](https://oktainc.atlassian.net/browse/OKTA-126461)
> Fixup errors in the password policy settings example JSON.

- tests/selenium/conf.js
- tests/selenium/framework/page-objects/BasePage.js
- tests/selenium/framework/page-objects/BlogPage.js
- tests/selenium/framework/page-objects/DocsPage.js
- tests/selenium/framework/page-objects/SideBarPage.js
- tests/selenium/framework/page-objects/TableOfContentsPage.js
- tests/selenium/spec/api-tags-spec.js
- tests/selenium/spec/blog-page-spec.js
- tests/selenium/spec/page-layout-browser-size-spec.js
- tests/selenium/spec/search-bar-spec.js
- tests/selenium/spec/side-bar-spec.js
- tests/selenium/spec/table-of-contents-spec.js
Added the following tests - 
1. Side bar navigation
2. API URL and Life cycle tags check
Updated spec files to use "fat arrows"
* [OKTA-125840](https://oktainc.atlassian.net/browse/OKTA-125840)
> Adding new protractor tests

- tests/selenium/framework/page-objects/CodePage.js
- tests/selenium/spec/code-layout-spec.js
Added the following test
1. Code page layout order -> Tests if the elements in the code page are in order (ordered based on their weights)
* [OKTA-125840](https://oktainc.atlassian.net/browse/OKTA-125840)
> Adding a protractor test

- _source/_posts/2017-04-17-angular-authentication-with-oidc.md
- blog/2017/04/17/angular-authentication-with-oidc.html
- documentation/index.html
- feed.xml
- sitemap.xml
Fix typo in Angular OIDC blog post
DevEx Team
> Fix typo in Angular OIDC blog post

- _source/_docs/api/resources/oauth2.md
- Add the oidc well-known endpoint to the AS metadata HAL link
* [OKTA-124562](https://oktainc.atlassian.net/browse/OKTA-124562)
- @larsjohansen-okta @mystiberry-okta 
> Add metadata HAL link changes

- _source/_docs/platform-release-notes/platform-release-notes.md
- docs/platform-release-notes/platform-release-notes.html
- RN for Preview Fix (OKTA-127155)
* [OKTA-127209](https://oktainc.atlassian.net/browse/OKTA-127209)
> preview fix RN

- _source/documentation/stormpath-import.md
- documentation/stormpath-import.html
- feed.xml
- sitemap.xml
Also changed "attribute" to "property", which will make the diff messier than it need be. Sorry. 
* [OKTA-127386](https://oktainc.atlassian.net/browse/OKTA-127386)
> Added info about username format and how hashed passwords are used

- _source/_docs/api/resources/oidc.md
- Add OIDC authorize request examples
- Add some copy / caps changes from Richard
- I was tangled up in some git spaghetti, so I might need some help making the commit history look clean. 
* [OKTA-86040](https://oktainc.atlassian.net/browse/OKTA-86040)
@mystiberry-okta @cwu-okta
> Add new OIDC Authorize Request examples

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-20.md
- Release Notes for 2017.21
* [OKTA-127308](https://oktainc.atlassian.net/browse/OKTA-127308)
@jakubvul-okta
> RN 2017.21

- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
- Customer request for browser security details.
* [OKTA-125208](https://oktainc.atlassian.net/browse/OKTA-125208)
@robertdamphousse-okta or @lboyette-okta or @jmelberg-okta or @rchild-okta
> browser security settings

- Gemfile
- scripts/helpers.sh
> Test bacon failure fix for github-pages gem install

- Gemfile
- scripts/helpers.sh
- scripts/setup.sh
> Test bacon failure by downgrading bundler version

- tests/selenium/spec/side-bar-spec.js
- tests/selenium/spec/table-of-contents-spec.js
> Fixing selenium test failure on bacon

- code/javascript/okta_sign-in_widget_external_ref.html
> Testing cloudfront cache configuration

- README.md
- Missed one update to README.md based on RC comment.
* [OKTA-126533](https://oktainc.atlassian.net/browse/OKTA-126533)
@rchild-okta
> missed one update

- scripts/helpers.sh
- scripts/setup.sh
- tests/selenium/spec/side-bar-spec.js
- tests/selenium/spec/table-of-contents-spec.js
1. Downgrading bundler version to 1.14.6
2. Adding strict mode in protractor tests to overcome failure due to older node version bacon
@rchild-okta 
> Fixing failure on bacon

- scripts/selenium.sh
This reverts commit 5fe2dd7da2f5d8a39420df5647fe5cf168bea22e.
> Revert "Test installation of latest chrome version (#907)"

- _source/search/index.html
- search/index.html
- 🐛  Fixes bug where search results would not show up on mobile screen sizes.
> :bug: Fixes mobile search

- _config.yml
- feed.xml
- sitemap.xml
- Always use UTC for feed and sitemap generation
> Always use UTC for feed and sitemap generation

- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-21.md
* [OKTA-128085](https://oktainc.atlassian.net/browse/OKTA-128085)
waiting for email review
> Jv okta 128085 rn2017.22

- _source/_docs/api/resources/authn.md
- Added section about "Step up authentication". 
* [OKTA-124760](https://oktainc.atlassian.net/browse/OKTA-124760)
@mystiberry-okta @edjohns-okta @tthompson-okta @karlmcguinness-okta
> Added section about "step up authentication" when signing into an app with custom login page.

- _source/documentation/stormpath-import.md
- documentation/stormpath-import.html
- Adding information about email uniqueness and what we do when there are identical username prefixes.
* [OKTA-127783](https://oktainc.atlassian.net/browse/OKTA-127783)
> Jv okta 127783 migration docs

- _source/_docs/api/resources/idps.md
- IdP documentation changes in support of OKTA-127848. Parent API dev task: OKTA-124821.
- Adding new conditions object to policy.provisioning object. Updated all examples, and added detail sections for object and sub-objects. Marked as beta. 
* [OKTA-127848](https://oktainc.atlassian.net/browse/OKTA-127848)
@johngronberg-okta 
> Adding provisioning conditions to IdP API doc

- _source/_docs/api/resources/oauth2.md
- docs/api/resources/oauth2.html
- documentation/index.html
- sitemap.xml
- Removed two beta tags from OAuth 2.0 API doc. 
* [OKTA-124731](https://oktainc.atlassian.net/browse/OKTA-124731)
@rchild-okta to check production build files (2nd commit)
@cwu-okta  to check the removal (1st commit, screen shots attached)
> Doc hf beta tags

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- Fixed revoke response code to 200
Related okta-core PR: https://github.com/okta/okta-core/pull/20738
* [OKTA-127736](https://oktainc.atlassian.net/browse/OKTA-127736)
- @petermiller-okta @mystiberry-okta
> OKTA-127736

- _source/_docs/api/resources/idps.md
- _source/_docs/api/resources/oauth-clients.md
- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- API docs for RP Initiated Logout
* [OKTA-94106](https://oktainc.atlassian.net/browse/OKTA-94106)
- @larsjohansen-okta @mystiberry-okta
> RP Initiated Logout

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/idps.md
- Only apps with SAML_2_0, SAML_1_1, WS_FEDERATION and OPENID_CONNECT sign on modes will show the signing property
https://github.com/okta/okta-core/pull/20777
* [OKTA-76439](https://oktainc.atlassian.net/browse/OKTA-76439)
- @mystiberry-okta @danielzeller-okta
> OKTA-76439

- _source/_docs/api/resources/groups.md
- docs/api/resources/groups.html
- documentation/index.html
- sitemap.xml
- Hotfix for Group Rules API missing its Beta tag
Amy Kim reviewed via email.
> Doc hf group rules beta

- _source/integrate_with_okta/index.html
- Change link in "Secure user identity via SSO" block to point to /use_cases/integrate_with_okta/sso-with-saml.html per Dana Palmie at Okta.
* Bug# in Flickerbox system.
> Change standards SAML url to point to use cases SSO with saml

- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- adds the `registration_endpoint` to the OAuth & OIDC metadata.
* [OKTA-127457](https://oktainc.atlassian.net/browse/OKTA-127457)
- @royalchan-okta @mystiberry-okta 
> Documents registration_endpoint portion of oauth/oidc metadata.

- _source/_docs/api/getting_started/api_test_client.md
Improve readability and reduce confusion for developers who aren't familiar with Okta.
- @mystiberry-okta @jakubvul-okta
> Improve Getting Started page

- _source/_docs/api/resources/authn.md
- Added information about remember device policy to "Verify factor" section
- Added details of "Remember device policy object" to embedded objects section
- Added rememberDevice attribute to all the factors
* [OKTA-129449](https://oktainc.atlassian.net/browse/OKTA-129449)
@nandagopalseshagiri-okta @edjohns-okta @tthompson-okta @mystiberry-okta
> Added details of rememberDevice option.

- _source/_code/dotnet/powershell.md
Fix broken links.
- @mystiberry-okta
> Update Powershell links

- README.md
RESOLVES OKTA-131046
- Updating the publish process to account for differences in master and weekly.
* [OKTA-131046](https://oktainc.atlassian.net/browse/OKTA-131046)
> Updates docs for publishing

- _source/_docs/platform-release-notes/platform-release-notes.md
- code/dotnet/index.html
- code/dotnet/powershell.html
- docs/platform-release-notes/platform-release-notes.html
- documentation/index.html
- sitemap.xml
Fix some already published problems.
> Hot 2017.25

- _source/_docs/api/resources/schemas.md
* [OKTA-128267](https://oktainc.atlassian.net/browse/OKTA-128267)
@donwoods-okta and optional @richardmateosian-okta
> date doc bug in schemas

- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/roles.md
- _source/_docs/api/resources/users.md
- User Admin > Group Admin
* [OKTA-127249](https://oktainc.atlassian.net/browse/OKTA-127249)
@jakubvul-okta
> user admin is now group admin

- _source/_docs/api/resources/oauth2.md
- Made existing information about custom claims/scopes not being returned more prominent, added links to APIs that DO return those claims and scopes. 
* [OKTA-131335](https://oktainc.atlassian.net/browse/OKTA-131335)
> Made note more prominent, added helpful links

- _source/_posts/2017-06-27-seven-tools-net-developers.md
- blog/2017/06/27/seven-tools-net-developers.html
- blog/index.html
- blog/page/2/index.html
- blog/page/3/index.html
- documentation/stormpath-import.html
- feed.xml
- package-lock.json
- package.json
- sitemap.xml
> 7 Essential Tools for .NET Developers 2017 Blog Post

- _source/_docs/api/resources/oauth2.md
Explain how native apps can revoke tokens
https://oktainc.atlassian.net/browse/OKTA-130215
@jmelberg-okta
> Okta 130215-doc

- _source/_code/php/quickstart-signin-widget.md
- Started off just wanting to fix a typo, but then found some more things to fix. 
> Minor edits for the PHP Sign-in Widget Quickstart

- _source/_docs/platform-release-notes/platform-release-notes.md
Final tweak to release notes
* [OKTA-131949
> Remove unnecessary bullet

- _source/_docs/api/resources/oidc.md
Add Cache-Control example to header.
https://oktainc.atlassian.net/browse/OKTA-122113
@larsjohansen-okta 
@johngronberg-okta
> OKTA-122113-doc

- _source/_posts/2017-03-30-react-okta-sign-in-widget.md
- blog/2017/03/30/react-okta-sign-in-widget.html
- feed.xml
- Fixes malformed link from #993 
* [OKTA-132252](https://oktainc.atlassian.net/browse/OKTA-132252)
> :bug: Fixes malformed link

- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
Update latest release numbers for sign-in and auth JS
* OKTA-131642
> Update release nos

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-26.md
Platform release notes for 2017.27
* https://oktainc.atlassian.net/browse/OKTA-132199
> Rn 2017.27

- _source/documentation/index.html
* [OKTA-130667](https://oktainc.atlassian.net/browse/OKTA-130667)
@jmelberg-okta
> removing commented, outdated code

- _source/_code/javascript/okta_sign-in_widget.md
Based on feedback from R Degges I:
- Made it clear that you configure CORS inside the Trusted Origins section of the UI
- Added instructions for Python 3 to go alongside the existing ones for Python 2
* [OKTA-129755](https://oktainc.atlassian.net/browse/OKTA-129755)
> Acting on feedback from rdegges

- .github/PULL_REQUEST_TEMPLATE.md
- Updates the PR template to be less noisy and ease external contribution experience.
> Updates PR template to be less noisy

- _source/_docs/api/resources/groups.md
- As requested, add beta tag to group rule model
* [OKTA-133007](https://oktainc.atlassian.net/browse/OKTA-133007)
> Beta for group rule model

- _source/test_page/index.md
- tests/selenium/framework/page-objects/BasePage.js
- tests/selenium/framework/page-objects/SideBarPage.js
- tests/selenium/framework/page-objects/TableOfContentsPage.js
- tests/selenium/spec/side-bar-spec.js
- tests/selenium/spec/table-of-contents-spec.js
1. Create a test page to be used for selenium tests
2. Remove hard coded text checks in selenium tests
* [OKTA-132585](https://oktainc.atlassian.net/browse/OKTA-132585)
> Improve d.o.c tests

- _source/_docs/api/getting_started/design_principles.md
- Warn people not to use undocumented API endpoints
* [OKTA-92604](https://oktainc.atlassian.net/browse/OKTA-92604)
> warning about undocd api endpoints

- _source/_docs/api/resources/idps.md
- package-lock.json
- Updated IdP page to point to new social login links
> Updated Social Login instruction links. 

- _source/_docs/api/resources/factors.md
- email factor addition to factors api for enroll, activate and verify
* [OKTA-129432](https://oktainc.atlassian.net/browse/OKTA-129432)
@gauthamgowrishankar-okta @karlmcguinness-okta
> OKTA-129432 email factor api doc

- _source/_code/javascript/okta_sign-in_widget.md
- _source/_code/php/quickstart-signin-widget.md
- _source/_docs/sdk/core/csharp_api_sdk/search.html
- Update 1.11.0 to 1.13.0 (RN coming later)
* [OKTA-131661](https://oktainc.atlassian.net/browse/OKTA-131661)
> Update 1.11.0 to 1.13.0 

- _source/_docs/api/resources/oauth-clients.md
> Revert client spec compliance

- _source/_docs/api/resources/idps.md
- Adding documentation for `SUSPENDED` action alongside `DEPROVISIONED`
* [OKTA-130159](https://oktainc.atlassian.net/browse/OKTA-130159)
@richardmateosian-okta 
@johngronberg-okta 
> Suspended Documentation (PMULS + IdP)

- _source/_docs/api/resources/social_authentication.md
- Doc the limit on social auth flows (social auth requests)
* [OKTA-122142](https://oktainc.atlassian.net/browse/OKTA-122142)
> Social auth timeout doc

- _source/_docs/api/getting_started/api_test_client.md
- _source/_docs/api/postman/admin-roles.json
- _source/_docs/api/resources/roles.md
- Labels in Postman collection need to change from User Admin to Group Admin per UI changes.
* [OKTA-131310](https://oktainc.atlassian.net/browse/OKTA-131310)
> Mystiberry okta patch 1

- _source/_posts/2017-07-13-apache-shiro-spring-boot.md
- blog/2017/07/13/apache-shiro-spring-boot.html
- blog/index.html
- feed.xml
> :memo: Fixes blog title

- _source/_code/javascript/okta_sign-in_widget.md
- Adding missing prerequisites to quickstart sign-in widget
> Adding missing prereqs

- _source/_standards/SCIM/index.md
- Minor update to Test with Customers section requested by Tim Gu.
* [OKTA-120763](https://oktainc.atlassian.net/browse/OKTA-120763)
> Tim Gu request for SCIM doc

- _source/_code/php/quickstart-signin-widget.md
> Updates PHP signin widget code sample

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-28.md
- Create platform release notes for 2017.29
* https://oktainc.atlassian.net/browse/OKTA-132201
> Rn 2017.29

- _source/_docs/how-to/inbound-saml-with-oidc.md
- Added instructions on using an inbound SAML flow to get an OIDC token.
**Suggestions for a different title are welcome!**
* [OKTA-126756](https://oktainc.atlassian.net/browse/OKTA-126756)
> Added new Inbound SAML with OIDC page

- _source/_code/php/jwt-validation.md
> Adds PHP JWT Validation Guide

- _source/_code/javascript/okta_angular_auth_js.md
- _source/_code/javascript/okta_angular_sign-in_widget.md
- Adds Angular & Okta walkthrough for code page
* [OKTA-132538](https://oktainc.atlassian.net/browse/OKTA-132538)
> :memo: Adds Angular + Auth JS & Widget walkthrough

- _source/_docs/api/resources/users.md
- Change request example from PUT to POST, because POST doesn't erase unspecified property values.
* [OKTA-134582](https://oktainc.atlassian.net/browse/OKTA-134582)
> fix PUT request to POST

- _source/_code/javascript/okta_angular_auth_js.md
- _source/_code/javascript/okta_angular_sign-in_widget.md
- Updates Angular AuthJS and OSW walkthroughs
> Updated angular samples

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-28.md
- _source/_docs/platform-release-notes/platform-release-notes2017-29.md
Platform release notes for 2017.30
https://oktainc.atlassian.net/browse/OKTA-132202
> Okta 132202

- _source/_use_cases/api_access_management/index.md
- Keeps consistency throughout pages by adding a header to the API Access Management page
- :bug: Fixes overlaying "Edit Page" 
* #1108
> Adds header to API Access Management page

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/oauth-clients.md
- _source/_docs/api/resources/oauth2.md
Add HTTP status codes to some additional response examples.
https://oktainc.atlassian.net/browse/OKTA-133829
> Okta 133829a

- _source/_docs/api/resources/policy.md
- Fix minor typos in Policy API documentation
* [OKTA-135948](https://oktainc.atlassian.net/browse/OKTA-135948)
> Fix typos in Policy API doc

- Gemfile
- package-lock.json
- package.json
- scripts/clean.js
The npm scripts wouldn't run under Windows because of a few issues.
Ping @rchild-okta or @jmelberg-okta for a review.
> Fix errors on Windows

- _source/_posts/2017-07-25-oidc-primer-part-1.md
- _source/_posts/2017-07-25-oidc-primer-part-2.md
- _source/_posts/2017-08-01-oidc-primer-part-3.md
- blog/2017/07/25/oidc-primer-part-1.html
- blog/2017/07/25/oidc-primer-part-2.html
- blog/2017/08/01/oidc-primer-part-3.html
- feed.xml
- cross-links from each part to the other parts per @lindsaybrunner-okta
> Oidc series update

- _source/_docs/api/resources/authn.md
- docs/api/resources/authn.html
- Updates reference to old path.
> Updates reference to current path

- _source/_docs/api/resources/oidc.md
- _source/_docs/api/resources/policy.md
- _source/_docs/api/resources/roles.md
- 🐛 Fixes trailing dot in URLs
> Fix trailing dot in URLs

- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2016-index.md
- _source/_docs/platform-release-notes/platform-release-notes2017-30.md
Create release notes for 2017.31
https://oktainc.atlassian.net/browse/OKTA-135654
> Create release notes for 2017.31

- _source/_docs/api/getting_started/design_principles.md
- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/system_log.md
- Update rate limit doc on developer.okta.com
* [OKTA-130728](https://oktainc.atlassian.net/browse/OKTA-130728)
* [OKTA-133448](https://oktainc.atlassian.net/browse/OKTA-133448)
> Dok 130728

- _source/_docs/api/resources/authn.md
- _source/_docs/api/resources/policy.md
- Mention that app-level MFA via api is not supported.
[OKTA-131972](https://oktainc.atlassian.net/browse/OKTA-131972)
> no app-level MFA via api

- _source/_docs/api/resources/sessions.md
- _source/_reference/okta_expression_language/index.md
- Minor tweaks related to deprecation: 1. a typo and 2. addding tag so customer can click it and see what we mean (still available, but scheduled for removal).
OKTA-112190
> fix deprecated references

- _source/_docs/api/resources/apps.md
- _source/_docs/api/resources/policy.md
- _source/_docs/api/resources/schemas.md
- _source/_docs/api/resources/social_authentication.md
- _source/_docs/how-to/set-up-auth-server.md
- A few files were using old style text instead of EA tags.
OKTA-126953
> making EA tags consistent

- _source/_docs/api/resources/oauth2.md
- _source/_standards/OAuth/index.md
- Default AS doc changes
[OKTA-134352](https://oktainc.atlassian.net/browse/OKTA-134352)
> default AS

- _source/_assets/css/okta/components/_PageContent.scss
- _source/_standards/OAuth/index.md
- assets/css/layout-docs.css
- More OAuth doc polish
* [OKTA-102541](https://oktainc.atlassian.net/browse/OKTA-102541)
> need to fix yellow

- _source/_docs/api/resources/system_log.md
- Clarify differences between System Log and Events API
[OKTA-132832](https://oktainc.atlassian.net/browse/OKTA-132832)
> improve intro to System Log beta

- _source/_docs/platform-release-notes/platform-release-notes.md
- Requested changes, breaking late.
> Late rn comments

- _source/_posts/2017-08-09-jax-rs-vs-spring-rest-endpoints.md
- blog/2017/08/09/jax-rs-vs-spring-rest-endpoints.html
- blog/index.html
- blog/page/2/index.html
- blog/page/3/index.html
- blog/page/4/index.html
- feed.xml
- sitemap.xml
Add new blog post
Two commits, first is the source, second is the generated prod build
> Blog Post: JAX-RS v Spring

- _source/_docs/how-to/byo_saml.md
- Point to the most correct URL for publishing idps and apps (csrs)
* [OKTA-131057](https://oktainc.atlassian.net/browse/OKTA-131057)
> correct URLS to idps and apps csrs

- _source/_docs/api/resources/policy.md
- Flip Password Policy API to EA on Policy API documentation
- Made a new PR (cherry-picked the old commit onto the new `weekly` branch) because we rolled over onto a new `weekly` release
* [OKTA-135947](https://oktainc.atlassian.net/browse/OKTA-135947)
> EA Password Policy API on Okta Developer site

- _source/_posts/2017-08-09-jax-rs-vs-spring-rest-endpoints.md
- blog/2017/08/09/jax-rs-vs-spring-rest-endpoints.html
- docs/how-to/byo_saml.html
- feed.xml
> Minor updates based on review

- _source/_docs/api/getting_started/api_test_client.md
More explanation of how to create an organization, and what the URL means.
@alexdahl-okta @jakubvul-okta
> Call out org creation and explain oktapreview

- _source/_assets/js/quickstart.js
- _source/quickstart/react/default-example.md
Copy of the current quickstart, modified to example the new default AS flow, and an access token usage.
* [OKTA-137727](https://oktainc.atlassian.net/browse/OKTA-137727)
> Add react quickstart in new quickstart structure

- _config.yml
- _source/_assets/js/quickstart.js
- _source/quickstart/java/generic-implicit.md
- _source/quickstart/java/spring-auth-code.md
- _source/quickstart/java/spring-implicit.md
First pass at the quick start docs.  It will help to have the clients defined so we can test out the wizard end to end.
> Quickstarts java

- .travis.yml
CI only change, if green we should merge
> Strip ci cache

- _source/quickstart/ios/default-example.md
> :seedling: Adds iOS quickstart

- _source/quickstart/php/generic-auth-code.md
- _source/quickstart/php/generic-implicit.md
> :seedling: Adds PHP quickstarts

- _source/quickstart/java/spring-implicit.md
- quickstart/angular/default-example.html
- quickstart/ios/default-example.html
- quickstart/java/spring-implicit.html
- quickstart/react/default-example.html
> Add example RestController for /api/messages to match client quickstart

- _source/_standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
- documentation/index.html
- sitemap.xml
- standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
- Update a SCIM 2.0 test file referenced by our doc.
[OKTA-136974](https://oktainc.atlassian.net/browse/OKTA-136974)
> Dok 136974

- _source/_assets/js/quickstart.js
- _source/quickstart/dotnet/aspnet4-auth-code.md
- _source/quickstart/dotnet/aspnet4-implicit.md
- _source/quickstart/dotnet/aspnetcore-auth-code.md
- _source/quickstart/dotnet/aspnetcore-implicit.md
- _source/quickstart/dotnet/generic-auth-code.md
- _source/quickstart/dotnet/generic-implicit.md
Adds quickstarts for ASP.NET Core 2.0 and ASP.NET 4.x
Note: Currently punting on the ASP.NET 4.x Code Flow example. It's unreasonably large/difficult since the tech is older and doesn't support OIDC natively. I'll circle back around to this.
@jmelberg-okta @robertjd
> Adds .NET quickstarts

- Gemfile.lock
- _source/_posts/2017-08-28-developers-guide-to-docker-part-2.md
- blog/2017/08/28/developers-guide-to-docker-part-2.html
- blog/index.html
- blog/page/3/index.html
- blog/page/4/index.html
- documentation/index.html
- feed.xml
- sitemap.xml
- Second post in Docker for Developers Series
> Docker part 2 Post

- _source/_posts/2017-08-28-developers-guide-to-docker-part-2.md
- blog/2017/08/28/developers-guide-to-docker-part-2.html
- feed.xml
- Fixes for localhost link and the ending period.
> Docker part 2 fixes

- _source/_posts/2017-04-17-angular-authentication-with-oidc.md
- blog/2017/04/17/angular-authentication-with-oidc.html
- documentation/index.html
- sitemap.xml
Fix code, list and {{ variables }}
See https://github.com/okta/okta.github.io/commit/962ce0bdad49c591b07873288a8f75c30c0e04a0 for markdown changes.
> Fix code, list and {{ variables }}

- _source/quickstart/widget/default-example.md
- documentation/index.html
- quickstart/widget/default-example.html
- sitemap.xml
- Fix bug in the Sign-In Widget quickstart
> :bug: Widget quickstart fix

- Gemfile.lock
- _source/_code/php/quickstart-signin-widget.md
- _source/_docs/api/resources/apps.md
- Exposes auto_key_rollover property for OIDC client in /apps API
- Updates OAuth Credential Object and examples
* [Issue #131959](#131959)
* [OKTA-131959](https://oktainc.atlassian.net/browse/OKTA-131959)
> Key rollover okta 131959

- _source/_docs/api/resources/policy.md
- Password Policy (GroupPasswordPolicy) is GA
[OKTA-139748](https://oktainc.atlassian.net/browse/OKTA-139748)
> password policy GA

- Gemfile.lock
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-35.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN for 2017.36 
[OKTA-140171](https://oktainc.atlassian.net/browse/OKTA-140171)
> RN for 2017-36

- Gemfile.lock
- _source/_posts/2017-06-21-what-the-heck-is-oauth.md
- blog/2017/06/21/what-the-heck-is-oauth.html
- blog/index.html
- blog/page/2/index.html
- blog/page/3/index.html
- blog/page/4/index.html
- documentation/index.html
- feed.xml
- sitemap.xml
Fix title capitalization in What the Heck Is OAuth post
> Fix title capitalization in What the Heck Is OAuth post

- Gemfile.lock
- _source/_code/dotnet/index.md
- blog/index.html
- blog/page/2/index.html
- blog/page/3/index.html
- blog/page/4/index.html
- code/dotnet/index.html
- documentation/index.html
- feed.xml
- sitemap.xml
- Production build on #1245 
- Includes recent blog posts that were not published
> Fix .NET example link

- _source/quickstart/dotnet/aspnetcore-auth-code.md
- Link to new example project
- Minor code fixes to make the experience smoother
> Minor tweaks to .NET code flow quickstart

- Gemfile.lock
- documentation/index.html
- sitemap.xml
- standards/SAML/setting_up_a_saml_application_in_okta.html
- Publish note that you need to use Classic UI for a SAML task
* [Issue #1228](#1228)
Source changes: https://github.com/okta/okta.github.io/pull/1229
> publish changes from 1229

- _source/quickstart/widget/default-example.md
- quickstart/widget/default-example.html
> Remove orphaned copy button

- tests/selenium/spec/check-imported-docs-spec.js
- tests/selenium/spec/quickstarts-spec.js
- Disabled failing tests to unblock doc PR merges
* [OKTA-141828](https://oktainc.atlassian.net/browse/OKTA-141828)
> Disabled failing tests to unblock doc PR merges

- _source/_docs/api/resources/schemas.md
- docs/api/resources/schemas.html
- documentation/index.html
- sitemap.xml
Doc for enum/oneOf for schema APIs
* [OKTA-OKTA-140437](https://oktainc.atlassian.net/browse/OKTA-OKTA-140437)
> Okta-140437

- Gemfile.lock
- _source/_standards/SCIM/index.md
- standards/SCIM/index.html
- Update link to OAN Manager
[OKTA-141479](https://oktainc.atlassian.net/browse/OKTA-141479)
> Dok 141479

- Gemfile.lock
- _source/_docs/how-to/inbound-saml-with-oidc.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-36.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
Self explanatory!
* [OKTA-141799](https://oktainc.atlassian.net/browse/OKTA-141799)
> Release Notes for 2017.38

- scripts/selenium.sh
- Updated chrome version to 61 for headless chrome support
- Removed dependency on xvfb 
> Testing headless chrome

- _source/_docs/api/getting_started/design_principles.md
- rl for users/id is 600
[OKTA-141473](https://oktainc.atlassian.net/browse/OKTA-141473)
> rl for users id is 600

- _config.yml
> Adding .nojekyll file to _source to be generated to /dist

- _source/quickstart/angular/default-example.md
- Updates the Angular quickstart to use the new `@okta/okta-angular` SDK
* [OKTA-141102](https://oktainc.atlassian.net/browse/OKTA-141102)
> Updated Angular quickstart

- _source/_docs/api/resources/policy.md
Reverts okta/okta.github.io#1302 per submitter's request.
> Revert "Document new excludeAttributes array in Password Complexity Object"

- _source/_docs/api/resources/schemas.md
- Add beta tags to two properties to be super sure people know they might change (they're already in a Beta section, but it doesn't hurt to be careful!).
No content changes to the tables, just cleaning up the formatting so the tables behave better in GitHub.
[OKTA-142736](https://oktainc.atlassian.net/browse/OKTA-142736)
> add beta, fix table formats

- _config.yml
- _source/_code/javascript/okta_sign-in_widget.md
- _source/_docs/api/resources/groups.md
- _source/_docs/api/resources/roles.md
- package-lock.json
- package.json
- Close out GH Issues pertaining to content updates
* Issue #876
* Issue #1293
> Various content updates

- Gemfile.lock
- _source/_code/javascript/okta_auth_sdk.md
- _source/_code/javascript/okta_sign-in_widget.md
- _source/_code/php/quickstart-signin-widget.md
- _source/_code/php/simplesamlphp.md
- _source/_code/python/pysaml2.md
- _source/_docs/api/getting_started/design_principles.md
- _source/_docs/api/resources/events.md
- _source/_docs/api/resources/groups.md
- _source/_docs/api/resources/oauth2.md
- _source/_docs/api/resources/oidc.md
- _source/_docs/api/resources/policy.md
- _source/_docs/api/resources/schemas.md
- _source/_docs/api/resources/users.md
- _source/_docs/how-to/creating-token-with-groups-claim.md
- _source/_docs/how-to/inbound-saml-with-oidc.md
- _source/_docs/how-to/set-up-auth-server.md
- _source/_standards/OIDC/index.md
- _source/_standards/SCIM/index.md
- _source/_use_cases/integrate_with_okta/oan-faqs.md
- _source/_use_cases/integrate_with_okta/promotion.md
- _source/_use_cases/integrate_with_okta/sso-with-saml.md
- _source/documentation/stormpath-import.md
- Weekly changes are all doc-only.
[OKTA-142434](https://oktainc.atlassian.net/browse/OKTA-142434)
> Release 2017 39 no RN changes

- _source/quickstart/angular/default-example.md
- _source/quickstart/nodejs/express-implicit.md
- _source/quickstart/nodejs/generic-implicit.md
Adding implicit quickstart content for Generic Node and Express
Also adding a few cleanup items on the Angular example of how to use the acess token
> Adding implicit quickstart content for Generic Node and Express

- _source/quickstart/react/default-example.md
- Updates the React quickstart to use the new React SDK
> Update react quickstart

- _source/_assets/js/quickstart.js
- _source/quickstart/nodejs/express-auth-code.md
- tests/selenium/spec/quickstarts-spec.js
Quickstart for auth code flow for Express.js
@lboyette-okta this is a rebased version of your original work (before the DOC changes), plus some extra context that I've added
> Express Authorization Code integration

- _source/_docs/api/getting_started/design_principles.md
- _source/_docs/api/resources/policy.md
- _source/_docs/api/resources/roles.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- _source/_docs/platform-release-notes/platform-release-notes2017-38.md
- _source/_docs/platform-release-notes/platform-release-notes2017-index.md
- RN for 2017.40 (no changes for .39)
[OKTA-140976](https://oktainc.atlassian.net/browse/OKTA-140976)
> API RN for 2017.40

- _source/_docs/api/getting_started/design_principles.md
- Adding concurrent rate limit info from RN to regular doc
[OKTA-142995](https://oktainc.atlassian.net/browse/OKTA-142995)
> Add new concurrent RL to main doc

- Gemfile
- Gemfile.lock
- _config.yml
- Assets were not being copied over correctly due to an updated dependency. Reverting + updating the `Gemfile.lock` accordingly.
> :bug: Fix build assets

- _source/quickstart/php/generic-implicit.md
- Updates based on OKTA-142954
- Does not resolve the issue of old orgs in regards to that part of the ticket.  This is a wider issue that needs to be addressed globally.
* [OKTA-142954](https://oktainc.atlassian.net/browse/OKTA-142954)
> Updates based on OKTA-142954

- _source/_docs/platform-release-notes/platform-release-notes.md
- There was concern about misleading customers that OIDC scopes themselves were new.
Hotfix no JIRA
> hotfix for customer clarity

- _source/_docs/api/getting_started/design_principles.md
- _source/_docs/platform-release-notes/platform-release-notes.md
- Language changes requested for rate limit info. Also noticed it made more sense to describe org-wide before concurrent, so swapped sections.
- bug fix was reverted, so we're also removing the note.
Hotfix, no JIRA
> Updates requested

- _source/_posts/2017-03-27-angular-okta-sign-in-widget.md
Fix link to CLI release in Angular Sign-In Widget blog post
> Fix link to CLI release in Angular Sign-In Widget blog post

- Gemfile.lock
- _source/_posts/2017-10-10-nosql-options-for-java-developers-part-ii.md
Blog post about NoSQL Options for Java Developers, Part 2
Attaching PDF for layout review.
[NoSQL Options for Java Developers, Part II _ Okta Developer.pdf](https://github.com/okta/okta.github.io/files/1372955/NoSQL.Options.for.Java.Developers.Part.II._.Okta.Developer.pdf)
> Blog post about NoSQL Options for Java Developers, Part 2

- _source/_posts/2017-10-10-nosql-options-for-java-developers-part-ii.md
Change Laurent Doguin's profile link to Twitter
> Change Laurent Doguin's profile link to Twitter
