oktadeveloper/okta.github.io

_source/assets/css/page-blog.scss

Lists weren't showing bullet points or numbers, and blockquotes had no
indentation or styling what so ever. This commit resolves that and keeps
all changes under the .blog class in an effort to avoid affecting
styling of the rest of the site.

CSS Styling for the blogs ol, ul, blockquote

---

_source/docs/guides/pysaml2.md
docs/guides/pysaml2.html

This uses relative paths to fix the broken links. If you prefer absolute links it can be changed.

Fixing broken links to the "Setting up a SAML application in Okta" example page

---

_source/docs/guides/social_authentication.md

It is illegal to use the response_mode=query param if using response_type=id_token, which is all we support.

Remove response_mode=query param

---

_source/docs/guides/oan_guidance.md

Rename "Java Connector" to "Java SDK", which is the official terminology. Update descriptions to be clearer.

Edits to Provisioning section

---

_source/docs/guides/pysaml2.md

On my OS X workstation I found that following the listed steps presented me with the following error:
```
saml2.sigver.SigverError
SigverError: Can't find ['xmlsec1']
```
That problem was remedied by running `brew install libxmlsec1`, but as a complete SAML neophyte it was not obvious that the `xmlsec1` PySAML could not find was a missing system-level dependency.

Include prerequisites in getting started steps

---

_source/docs/api/resources/authn.md

Replaced typo ("OKTA" to "GOOGLE" provider type in Enroll Google Authenticator Factor" section)

Updated authn.md

---

_source/docs/api/resources/idps.md

In OKTA-78503 we renamed the `FINISH` status to `SUCCESS`, and return a `next` link instead of a `finish` link when the status is `SUCCESS`.
In OKTA-78504 we moved the `/tx/{id}/lifecycle/jit` endpoint to `/tx/{id}/lifecycle/provision`, and renamed the HAL links accordingly.
@mattloughran-okta @joelfranusic-okta @slee-okta @eklein-okta 

Changes IdP transaction docs to reflect code changes.

---

_source/docs/api/resources/apps.md

Added the query parameters 'activate', which is a boolean that allows creating apps with INACTIVE status
Reviewers: @federations-okta and @karlmcguinness-okta 
Related to: https://oktainc.atlassian.net/browse/OKTA-78078
Note: first time changing api docs, so let me know if I am missing something

OKTA-78078: apps api can now create inactive apps

---

_source/docs/api/getting_started/okta_expression_lang.md

We now use the 'idpuser.' prefix for IdP users username transform EL instead of 'saml.' or 'appuser.'
I'm not 100% sure about the content here, so please give feedback.
https://github.com/okta/okta-core/pull/12246
Reviewers: @karlmcguinness-okta @joelfranusic-okta @mattloughran-okta @slee-okta @eklein-okta  @tthompson-okta @cwu-okta

Adds docs for the idpuser prefix for Okta EL

---

_source/docs/api/resources/users.md

Based on my testing, the response doesn't include the password reset URL - it simply sends back an empty JSON :
`schandra$ curl -s -H "Authorization: SSWS <removed>"  -H "Accept: application/json"  -H "Content-Type: application/json"  -X POST "https://schandra.okta.com/api/v1/users/:uid/lifecycle/reset_password?provider=FEDERATION&sendEmail=false"
{}
schandra$`

Fixed response for call to change a user's creds provider to FEDERATION

---

_source/docs/api/getting_started/design_principles.md
_source/docs/api/resources/oidc.md

Readding because it was already reverted due to a premature commit to master.
this supercedes https://github.com/okta/okta.github.io/pull/206
Api docs for request debugging using the X-Okta-Request-Id.
Resolves: OKTA-84899
Primary Reviewer: @mystiberry-okta @hassenkaraa-okta 
Reviewer : @federations-okta

Add X-Okta-Request-Id header to responses Resolves: OKTA-84899

---

_source/docs/api/resources/oidc.md

Notes that the `state` parameter is no longer optional on the authorize endpoint.
@tthompson-okta 

Require the state parameter on the authorize endpoint

---

_source/docs/api/resources/oidc.md
_source/docs/api/resources/social_authentication.md

- More fully note that the `nonce` parameter is now required.
- Add documentation to social-auth that reflects `nonce` and `state` being required.
Resolves: OKTA-89262
@federations-okta 

Adds more documentation about the requirement for the state and nonce parameters

---

_source/docs/api/postman/users.json
_source/docs/api/resources/users.md

The user will be created and immediately added to that group.  This is necessary for User Admins who can only create users in their targeted groups.
Relates-to: OKTA-89867

Create user call expanded to allow group ids to be passed in.

---

_source/docs/api/resources/system_log.md

@mystiberry-okta @johnfung-okta  copied a bulletpoint about URL encoding from user API doc.  Based on Michael Rucker's feedback.

Note that URLs must be encoded

---

_source/_layouts/docs_page.html

@jpf Do you see anything wrong with me removing this? The file hasn't been touched since 2015, but when I remove this line, a local build of site makes the double-footer problem go away.

remove extra footer

---

_source/_data/docs.yml
_source/_includes/docs_nav.html
_source/_includes/footer.html
_source/_includes/header.html
_source/docs/platform-release-notes/platform-release-notes.md
_source/docs/platform-release-notes/platform-release-notes2016-23.md
_source/docs/platform-release-notes/platform-release-notes2016-24.md

There's one bug: for some reason, the headings under the title aren't being displayed in the table of contents. I'm not sure what's wrong--they were showing up at one point...?! Because the RN are short, I don't think this is a showstopping bug.
https://oktainc.atlassian.net/browse/OKTA-91805

move platform RN to dev site

---

_source/_includes/head.html

Typekit was doing blocking on load, this makes it async so other things can load. Initial tests show a 20-25% speed up in load times.
Ref:  http://blog.typekit.com/2015/08/04/new-embed-code-for-asynchronous-font-loading/

Switched typekit to async mode

---

_source/docs/api/resources/groups.md
_source/docs/api/resources/users.md

@karlmcguinness-okta @jaikumarbathija-okta @tthompson-okta @mystiberry-okta  
Support was requesting documentation for the change to the HAL links on User collections before we start turning it on. Our current phrasing is a little vague about when exactly you get each link, this is clarifying that consumers should only expect a self link for collections of Users
Main change is in the Links Object doc, and then the various example responses are also updated:

Update User Links doc to reflect individual vs collection returns

---

_source/docs/api/resources/oauth2.md

Clarify that while ID Tokens are valid at introspection endpoint, Accces Tokens and Refresh Tokens are the intended uses.
@raphaellondner-okta  or @tthompson-okta , this section is missing request and response examples. Not sure I'm set up to create them, but if you supply the examples, I'll happily add them. Long term, will get set up properly so I can do these simple tasks.

okta-97071 doc update

---

_source/_docs/api/resources/oidc.md

@yuliu-okta , can you review this? I was wondering if we need to include any of the following from the spec, as well (we try to avoid just copying the spec, but this info seemed important (access token vs. ID Token):
_________________________
The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described inSection 5.3.2, when a response_type value is used that results in an Access Token being issued. However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token.
In some cases, the End-User will be given the option to have the OpenID Provider decline to provide some or all information requested by RPs. To minimize the amount of information …

OKTA-99877

---

_source/_code/dotnet/powershell.md
_source/_code/dotnet/sdk.md
_source/_code/python/sdk.md

@raphaellondner-okta could you review the updates before we go live?
Here are what the changes would look like if they were to go live:

Add links to .NET and Python SDKs for the Okta API

---

_source/assets/js/docs.js

I switched to fixed height to match the header + page-content padding. 
The selector `a[href*=#]:not([href=#])` is not valid with recent jquery which caused the filed to fail to finish loading.

removed lots of dead code and fixed anchor scroll (jquery 3 issue)

---

scripts/brokenlinks-scanner.sh

This is a basic script to spider developer.okta.com to discover broken
links.
Example report result:
```
---request begin---
HEAD /code/php/setting_up_a_saml_application_in_okta.html HTTP/1.1
Referer: http://developer.okta.com/code/php/simplesamlphp.html
User-Agent: Wget/1.14 (linux-gnu)
Accept: */*
Host: developer.okta.com
Connection: Keep-Alive
---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 404 Not Found
Server: GitHub.com
Content-Type: text/html; charset=utf-8
ETag: "57f55021-247c"
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: 17EB2F32:C721:4CFE135:57FD0D01
Content-Length: 9340
Accept-Ranges: bytes
Date: Tue, 11 Oct 2016 16:18:03 GMT …
```

Add broken links scanner for bacon task

---

_source/_code/dotnet/sample_application.md
_source/_layouts/docs_page.html
_source/_sass/okta/components/_Sidebar.scss

Media query only applies to documentation pages. Which are pages with the `docs_page` layout.
Change is staged here: https://frozen-ridge-22271.herokuapp.com/
Compare these pages to the same ones on developer.okta.com
https://frozen-ridge-22271.herokuapp.com/code/javascript/okta_auth_sdk.html
https://frozen-ridge-22271.herokuapp.com/code/javascript/

Update sidebar media query for small screens

---

_source/_standards/SCIM/index.md
_source/_standards/SCIM/scim_developer_program.md

Checking in the fixes, but a CSS issue masks the fix. When OKTA-106509 is fixed, these links will function correctly.

fix broken links for SCIM

---

_source/_docs/api/getting_started/api_test_client.md
_source/_docs/api/getting_started/design_principles.md
_source/_docs/api/getting_started/enabling_cors.md
_source/_docs/api/getting_started/getting_a_token.md
_source/_docs/api/getting_started/index.md
_source/_docs/index.md
_source/_includes/sidebar.html
_source/_reference/api_reference.md
_source/_reference/error_codes/index.md
_source/_reference/getting_started.md
_source/_reference/okta_expression_language/index.md
_source/_reference/release_notes.md
_source/_use_cases/authentication/index.md
_source/_use_cases/integrate_with_okta/index.md
_source/_use_cases/mfa/index.md
_source/documentation/index.html

This PR contains the following navigational changes:
* on http://developer.okta.com/documentation/:
- In the Use Cases section the order is now Authentication, MFA, Integrate with Okta (more logical order than before). 
- In the reference section, Getting started now shows up first.
* Going to the API getting started page now directs to the API test client setup instead of the design principles page
* Sidebar is re-arranged to match the changes to the /documentation nav
* /docs re-directs to /documentation now instead of docs/api/getting_started/design_principles.html
@mystiberry-okta do these seem OK to you?

Tweaks to document order and re-direct changes

---

_source/_docs/api/resources/factors.md

Documentation about enrolling SMS factor using an existing phone via "/api/v1/users/{userId}/factors" API. 
Covers the following scenarios: 
- *update the phone number*
- *use existing phone number*
Primary Reviewer: @mystiberry-okta 
Optional Reviewers: @karlmcguinness-okta @tthompson-okta 
Note: We have similar gap in authentication api for the SMS factor. I will create another PR for that.

Added section related to updating the phone using 'updatePhone' option

---

_source/_use_cases/authentication/index.md

The existing link was re-directing users to the Sign In Widget Reference, when we really want them to go to the guide page.

point users to OSW guide instead of reference

---

_source/_use_cases/authentication/index.md

These links exist on the Authn API page, but not on the Auth landing page. Making the content match. 
@mystiberry-okta no rush to get this one in.

Add links to Authn API and Sessions pages

---

_source/_includes/blog_post.html
_source/_includes/code.html
_source/_includes/footer.html
_source/_includes/head.html
_source/_includes/header.html
_source/_includes/sidebar.html
_source/_layouts/base.html
_source/_layouts/blog_index.html
_source/_layouts/blog_post.html
_source/_layouts/code.html
_source/_layouts/docs_page.html
_source/_layouts/master.html
_source/_layouts/software.html

This is a "medium sized" update to remove whitespace from the HTML that Liquid template generates. The main issue here is that the current version of this site make extensive use of [Jekyll Collections](https://jekyllrb.com/docs/collections/) to generate pages and sidebars. 
This should be considered a temporary fix, until we can move back to generating sidebars and pages from [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/), instead of collections. Meaning: Use a `config.yml` or similar kind of file to drive what shows up in the sidebar, which pages show up in the "Use Cases", "Reference", and "Code" sections, and so on.

Update Liquid template code with hack to remove whitespace 

---

_source/_docs/api/resources/sessions.md

@tthompson-okta, @lboyette-okta , is this update accurate? I'm addressing Sohaib's request, not sure if my changes are enough or if we need more examples in the doc (Srini said we shouldn't be encouraging use of this api):
For session APIs, if we can mention the purpose of API call e.g. POST /sessions to create session id to be used for single logout later DELETE /sessions/sessionId. Any examples or flow of calls (e.g. Primary Auth followed by $
{orgname}
.okta.com/login/sessionCookieRedirect?token=<sessionToken>….) to establish session with Okta will be helpful
Sample to call CORS enabled /sessions/me endpoints from browser/JS http://developer.okta.com/docs/api/getting_started/enabling_cors.html

updates for POST sessions

---

_source/_docs/api/resources/authn.md
_source/_docs/api/resources/factor_admin.md
_source/_docs/api/resources/idps.md
_source/_docs/api/resources/oauth-clients.md
_source/_docs/api/resources/oauth2.md
_source/_docs/api/resources/oidc.md
_source/_docs/api/resources/resource-server-beta/required-config-changes-for-auth-server.md
_source/_docs/api/resources/sessions.md
_source/_docs/api/resources/system_log.md
_source/_docs/api/resources/tokens.md
_source/_docs/api/resources/users.md
_source/_plugins/ApiTags.rb

DRY'd up the use of lifecycle badges to link back to the new okta release lifecycle page (See _source/_plugins/ApiTags.rb).  
Going forward folks don't need to copy/paste all the link markdown and can just use the api lifecycle tag.  I removed all the manual links in existing documents.
> Note:  For some reason `client_credentials` grant_type was marked as beta.  This should be EA now with API Access Management EA.  I removed the beta badges.
@mystiberry-okta @jpf

Added support for Okta Release Lifecycle links to API Lifecycle badge liquid tags

---

_source/_3rd_party_notices/index.html

This will fix an issue with the links to our 3rd Party Notices files on static hosting sites

Fix links in 3rd Party Notices when hosted from S3

---

_source/_use_cases/authentication/index.md

the "built-in support" link under the social auth section on http://developer.okta.com/use_cases/authentication/ gets a 404

fix social auth link typo

---

scripts/build.sh
scripts/common.sh
scripts/import_external_markdown.sh
scripts/lint.sh
scripts/selenium.sh
tests/selenium/spec/check-upstream-docs-tests.js

The `import_external_markdown()` function appends files from external repositories into Markdown files in the _source directory that use the `external_source:` frontmatter option.
The plan is to start including documentation from projects like `okta/okta-signin-widget` and `okta/okta-auth-js` into developer.okta.com by including the npm packages for those projects into the `package.json` file in this repository, then we can set up transclusion in files in this repository via the `external_source:` frontmatter option.

Add support for transclusion via import_external_markdown()

---

_source/assets/js/docs.js

This is to fix linking directly to ID hashes from other pages or outside of the developer to account for the fixed header.

Add scrollTop offset for deep linking to IDs from other pages.

---

_source/_docs/api/resources/oauth-clients.md

Calls out that the `client_id` has a different set of allowable characters than the `client_secret`
@yuliu-okta @richardmateosian-okta @federations-okta 
Related-to: OKTA-115587

Add documentation for new clientId validation.

---

_source/_layouts/blog_post.html

This makes it so individual posts don't stretch to fit the page. It also fixes syntax highlighting on individual posts.
Before:
After:

Fix individual blog layout

---

_source/_posts/2015-06-11-trustpage.md
_source/_posts/2017-03-21-spring-boot-oauth.md
_source/_posts/2017-04-17-angular-authentication-with-oidc.md
_source/_sass/okta/components/_PageContent.scss

Code listings with long lines causes the blog to be a fixed width and not squish when the browser is squished. This fixes that problem. Tested in Chrome and Firefox on Mac.
Before:
After:

Fix blog layout so its responsive

---

_source/_layouts/blog_index.html
_source/_layouts/blog_post.html
_source/_sass/_code.scss
_source/_sass/okta/components/_PageContent.scss
_source/assets/css/page-blog.scss

This reverts my previous changes:
- https://github.com/okta/okta.github.io/pull/741
- https://github.com/okta/okta.github.io/pull/752
Rather than changing `blog_post.html` to use `class="PageContent"`, it seems easier to make `blog_index.html` use styles associated with `blog_post.html` (because they're responsive and stretch with the page). It also minimizes the impact on `.PageContent` since that class seems to pertain to the rest of the site.

Make blog_index more like blog_post

---

scripts/helpers.sh
scripts/setup.sh

Remove all references to import_external_markdown
We use the npm command 'import-external' which now happens to be part of the build

Remove references to import_external_markdown

---

_source/_docs/api/resources/oidc.md

- Docs say Access Token in a place where it should be ID Token
* #893 

Should say ID Token not Access Token

---

scripts/selenium.sh

* We need to migrate from phantomJS to chrome headless
* The version of chrome installed on bacon doesn't support this
* This is the first step in moving away from phantomJS

Test installation of latest chrome version

---

_source/_docs/api/resources/system_log.md

This changeset fixes a few errors in the "Attributes" section of our
`/logs` documentation:
- In the table, `eventId` should be `uuid`.
- There are references to `requestId` that should be `transaction.id`.
- There are references to `sessionId` that should be
`authenticationContext.externalSessionId`.
Also, in the "Example Log object" section, the reference to
`authentication_context` should be `authenticationContext`.
* [OKTA-127977](https://oktainc.atlassian.net/browse/OKTA-127977)
- [n/a] For functional changes, I have tested against Chrome, Firefox, and Safari, and mobile.
- [n/a] For functional changes, I have added tests.
* @mystiberry-okta 
* @bobtiernay-okta 
* @aminjashki-okta
* @rpamidimarri-okta
* @ericzhou-okta
* @richardblaylock-okta
* @jeffpeeler-okta
* …

/logs docs fixes: Attributes section

---

tests/selenium/spec/api-tags-spec.js

Removing the beta tag validation on “/docs/api/resources/oauth2.html" page.
This is failing travis test on Mysti's doc change (OKTA-124731)
@rchild-okta 

Disable Beta tag test

---

tests/selenium/spec/api-tags-spec.js

- Using the lifecycle operations page for tag checks
- Removed checks from other pages, since these tags will be changed, eventually.

Using the lifecycle operations page for tag checks

---

_source/_docs/api/getting_started/api_test_client.md

I noticed some weird separator characters in the table, added in 3ac47597c. I don't think the addition of these characters was intentional. The chars don't show up in all git diffs, but they do affect how the page renders in some browsers. Here is Chrome on macOS:
Before (currently live):
After:
- @mystiberry-okta @jakubvul-okta

Fix bad characters

---

_source/_docs/how-to/set-up-auth-server.md

- Added example of AuthZ server tests to final section. Also rearranged earlier set-up instructions to highlight fact that custom scopes and claims are not required to have working AuthZ server. The rearranging has made the diff very noisy. The only section with actual new content starts at: `## Test Your Authorization Server Configuration`
* [OKTA-130850](https://oktainc.atlassian.net/browse/OKTA-130850)

Completed section

---

_source/_code/javascript/okta_auth_sdk.md
code/javascript/okta_auth_sdk.html

- Fix okta-auth-js CDN link - it was pointing to an asset that didn't exist
* [OKTA-132875](https://oktainc.atlassian.net/browse/OKTA-132875)
@jmelberg-okta

Fix okta-auth-js CDN link

---

_source/_docs/api/getting_started/enabling_cors.md

Because we are now using SSL, none of these old http links work, chrome
blocks them as they are insecure resources.
Fixes #1014

Using https URL for the embedded caniuse.com iframe.

---

_source/_includes/footer.html
_source/_includes/head.html
_source/_includes/header.html
_source/_includes/post-footer.html
_source/_layouts/base.html
_source/_layouts/code.html
_source/_layouts/master.html
_source/_layouts/software.html

Fix errors and warnings reported by Google Tag Assistant for Google Tag Manager and Google Remarketing code.
Moved GTM code to the head. Added new post footer include file
Create new post-footer.html include file to fix warnings from GTM no-script and remarketing tags.
Moved JavaScripts from footer to this file because Google code cannot be contained in a child element.
Add new post-footer.html include file to base.html, code.html, master.html, and software.html.
* Request from Jamie Lee Rice
DevEx

Fb pjm google tag manager redux

---

_source/_docs/api/resources/oidc.md
_source/_docs/api/resources/social_authentication.md
_source/_standards/OAuth/index.md

- Remove EA tags for OIDC, key rollover (there weren't any for key rollover in particular).
Asking team if Social Login (Social Authentication) should still be marked EA. it is in one place, but not the main place.
* [OKTA-133154](https://oktainc.atlassian.net/browse/OKTA-133154)

remove EA tags for OIDC, key rollover

---

_source/_docs/api/resources/oauth-clients.md

- Various changes for client registration API. Not all have an API doc component.
- Note: We don't show HTTP status codes in returned results at the moment. They aren't super crucial, so I'd vote to keep them off the page for now.
- [OKTA-130848](https://oktainc.atlassian.net/browse/OKTA-130848)
- [OKTA-130804](https://oktainc.atlassian.net/browse/OKTA-130804)
- [OKTA-130812](https://oktainc.atlassian.net/browse/OKTA-130812)
- [OKTA-130910](https://oktainc.atlassian.net/browse/OKTA-130910)
- [OKTA-128839](https://oktainc.atlassian.net/browse/OKTA-128839)
- [OKTA-130375](https://oktainc.atlassian.net/browse/OKTA-130375)
- [OKTA-131259](https://oktainc.atlassian.net/browse/OKTA-131259)
- [OKTA-131891](https://oktainc.atlassian.net/browse/OKTA-131891)
@larsjohansen-okta @mystiberry-okta …

Client Registration Changes

---

_source/_docs/api/resources/idps.md

- idps endpoint /api/v1/users/:uid/idps is only for social idps, not saml.
* [OKTA-132878](https://oktainc.atlassian.net/browse/OKTA-132878)

endpoint for social, not saml

---

_source/_docs/api/resources/users.md

Had used ' instead of ` earlier while fixing a different bug. This just fixes that.
* [OKTA-132974](https://oktainc.atlassian.net/browse/OKTA-132974)

OKTA-132974 Fixed wrong formatting of '?' character

---

_source/_docs/how-to/sharing-cert.md
_source/_docs/how-to/updating_saml_cert.md

- Remove EA blurb from SHA how-to doc. Since key rollover is GA, and SHA is becoming GA in preview (prod delay marked in RN), no need for pre-req section at all.
* [OKTA-135126](https://oktainc.atlassian.net/browse/OKTA-135126)

remove EA from SHA doc

---

_source/_docs/api/resources/apps.md
_source/_docs/api/resources/idps.md
_source/_docs/how-to/byo_saml.md
_source/_docs/how-to/set-up-auth-server.md
_source/_docs/how-to/sharing-cert.md
_source/_docs/how-to/updating_saml_cert.md

Remove references to EA designation for key rollover (and OIDC)
https://oktainc.atlassian.net/browse/OKTA-135065

Remove references to EA designation for key rollover (and OIDC)

---

_source/_docs/api/resources/policy.md

- Update Policy API with weak password dictionary and optional recovery question changes
* [OKTA-135946](https://oktainc.atlassian.net/browse/OKTA-135946)
I ran out of possible subhheadings, so there's insufficient nesting available. (maximum 6 hashes) For that reason, Weak Password Dictionary Object is in the document structure, but Common Password Lookup Object isn't, like so:
Let me know if you have any suggestions for the naming/phrasing/structure of this doc.

Update policy api doc with new features

---

_source/_docs/api/resources/schemas.md

- Add documentation for App User Schemas API to existing Schemas API page.
Add App User Schema Model documentation to go along with API documentation.
* [OKTA-134020](https://oktainc.atlassian.net/browse/OKTA-134020)
- @okta/ud-core 
- @mystiberry-okta 
- @richardmateosian-okta 
- @georgekwon-okta

Add Documentation for App User Schemas API

---

_config.yml
_source/_assets/css/okta.scss
_source/_assets/css/okta/pages/_quickstarts.scss
_source/_assets/js/quickstart.js
_source/_includes/footer.html
_source/_includes/quickstart-coming-soon.html
_source/_layouts/quickstart.html
_source/_layouts/quickstart_partial.html
_source/quickstarts/android/default-example.md
_source/quickstarts/angular/default-example.md
_source/quickstarts/dotnet/generic-auth-code.md
_source/quickstarts/dotnet/generic-implicit.md
_source/quickstarts/index.md
_source/quickstarts/ios/default-example.md
_source/quickstarts/java/generic-auth-code.md
_source/quickstarts/java/generic-implicit.md
_source/quickstarts/java/spring-auth-code.md
_source/quickstarts/java/spring-implicit.md
_source/quickstarts/nodejs/express-auth-code.md
_source/quickstarts/nodejs/express-implicit.md
_source/quickstarts/nodejs/generic-auth-code.md
_source/quickstarts/nodejs/generic-implicit.md
_source/quickstarts/php/generic-auth-code.md
_source/quickstarts/php/generic-implicit.md
_source/quickstarts/react/default-example.md
_source/quickstarts/widget/default-example.md

Added a simple JS app for the quickstarts page, including default markdown content where code examples will go.  View by visiting http://localhost:4000/quickstarts/.  Final styling (including icons) will be added after pending style PR.
* [OKTA-135962](https://oktainc.atlassian.net/browse/OKTA-135962)

Add Quickstarts app and default content

---

_source/_use_cases/authentication/session_cookie.md

- Add a note about IE length limitations on GET to session redirect endpoint.
[OKTA-136280](https://oktainc.atlassian.net/browse/OKTA-136280)

constraints on sessionRedirect for length for IE

---

_source/feed.xml

Limit number of posts contained in RSS feed to prevent FeedBurner error
--
Issue submitted to Okta Marketing queue filed by maziel.martinez@okta.com
FeedBurner will not process any feeds larger than 1MB
https://app.asana.com/0/370676378542055/398673129913955

Limit number of posts contained in RSS feed to prevent FeedBurner error

---

tests/selenium/framework/page-objects/NavPage.js
tests/selenium/spec/page-layout-browser-size-spec.js

- Added a check that ensures that support dropdown menu is visible on click
- This is to catch bugs where the page content overlays the drop-down navigation for the "Support" navbar item
* [OKTA-138751](https://oktainc.atlassian.net/browse/OKTA-138751)

Adding check for support link on navigation bar

---

_source/quickstart/widget/default-example.md
quickstart/widget/default-example.html

* The previous example would return a session token, not an access/id token pair.  Example is now updated to do this.
* Example is also updated to redirect through Okta to get the session token, so that Safari can get the SSO cookie stored
* Cleaned up example code to use 2 spaces, and not use const for cross-browser concerns
* [OKTA-140258](https://oktainc.atlassian.net/browse/OKTA-140258)

Update widget implicit quickstart

---

_source/_docs/api/resources/policy.md

- Adds the `type` property to the policy rule object examples
- It's already documented elsewhere in the Policy API--adding to these examples because they just happen to lack that property
* [OKTA-141467](https://oktainc.atlassian.net/browse/OKTA-141467)

Doc policy rule type in examples in Policy API

---

_source/_code/javascript/okta_auth_sdk.md
_source/_code/javascript/okta_sign-in_widget.md
_source/_code/php/simplesamlphp.md
_source/_code/python/pysaml2.md
_source/_docs/api/getting_started/design_principles.md
_source/_docs/api/resources/events.md
_source/_docs/api/resources/groups.md
_source/_docs/api/resources/oauth2.md
_source/_docs/api/resources/oidc.md
_source/_docs/api/resources/schemas.md
_source/_docs/api/resources/users.md
_source/_docs/how-to/inbound-saml-with-oidc.md
_source/_docs/how-to/set-up-auth-server.md
_source/_standards/OIDC/index.md
_source/_standards/SCIM/index.md
_source/_use_cases/integrate_with_okta/oan-faqs.md
_source/_use_cases/integrate_with_okta/promotion.md
_source/_use_cases/integrate_with_okta/sso-with-saml.md
_source/documentation/stormpath-import.md

- If an old Knowledge Article has been replaced with Product doc new topic, the existing link sends you to a sign-in page, never tells you the article doesn't exist. Note: not all articles have been moved to Product doc, so not all old-style URLs have been replaced.
There is a separate REQ for using aliases instead of full URLs which tend to change over time.
[OKTA-141394](https://oktainc.atlassian.net/browse/OKTA-141394)

link changes from old support.okta.com URLs

---

_source/_docs/api/resources/oauth2.md

- Fix links that pointed to oidc instead of oauth2 per https://github.com/okta/okta.github.io/pull/1281#discussion_r140357692
I removed some extra links (you really only need to link once per paragraph!)
[OKTA-141394](https://oktainc.atlassian.net/browse/OKTA-141394)

fix oidc-md links to oauth2-md

---

_source/_docs/api/resources/policy.md

- Add excludeAttributes array in Password Complexity Object documentation
* [OKTA-140223](https://oktainc.atlassian.net/browse/OKTA-140223)

Document new excludeAttributes array in Password Complexity Object

---

_source/_docs/api/resources/users.md

- Listing users by a `filter` uses a subset of SCIM operators shown in this section: [#list-users-with-a-filter](https://developer.okta.com/docs/api/resources/users.html#list-users-with-a-filter). According to [OKTA-64880](https://oktainc.atlassian.net/browse/OKTA-64880), the "sw" field is only supported with **search**, not basic **filtering**.
* [OKTA-142555](https://oktainc.atlassian.net/browse/OKTA-142555)
* [OKTA-110553](https://oktainc.atlassian.net/browse/OKTA-110553) & [OKTA-108026](https://oktainc.atlassian.net/browse/OKTA-108026)

:bug: Removes non-supported SCIM filter

---

_source/_code/swift/index.md

- :bug: Fixes a bug where Google cached an outdated path. We will now redirect to the correct page.
- `/code/swift` -> `/code/ios`

Adds Swift code page redirect

---

_source/_docs/api/resources/factors.md

- Adds a sub-section to the enroll factor API sections for sms, call, and email.
* [OKTA-143928](https://oktainc.atlassian.net/browse/OKTA-143928)
* Primary: @mystiberry-okta 
* Optional: @nandagopalseshagiri-okta 
*NOTE* : My local setup doesn't know how to find images, so you get the empty squares next to the headings.  I get this even on pages I didn't touch.

Auto-activate subsections for enroll sms, call, and email factors

---

README.md

Updates the branch to use `source` instead of `master`. This shows the current state of our build, instead of always **failure**.

:bug: Fixes Travis CI badge

---

_source/_docs/api/resources/oidc.md

- additional `*` around line 190 broken the subtitle layout.
- clean up extra whitespace.

Fix the incorrect layout for response parameter sub-header.

---

_source/_authentication-guide/implementing-authentication/set-up-authz-server.md
_source/_authentication-guide/saml-login/index.md

- Isolating the larger rewrites that have resulted from the feedback.
In this case, the Authorization Server Set-up section didn't really make sense with the rest of the AuthN Guide. I've tried to rewrite it in light of the fact that anyone reading this guide needs a custom authorization server, whether it is the default one or one they make themselves. I've also tried to clarify some of the descriptions of rules, access policies, etc.

AuthN Guide Major Rewrites

---

.travis.yml

We don't use it, and we can build on newer images and locally debug issues when not using the Travis-CI VMs

Remove the need for sudo during build

---

tests/selenium/spec/quickstarts-spec.js

The test still runs on chrome browser using sauce labs
- Disabled a failing test on headless chrome

Disabling quick-start server selection on headless chrome

---

_config.yml
_source/_authentication-guide/auth-overview/index.md
_source/_authentication-guide/saml-login/index.md
_source/_authentication-guide/social-login/social-settings.md
_source/_authentication-guide/tokens/index.md
_source/_authentication-guide/tokens/revoking-tokens.md
_source/_authentication-guide/tokens/validating-access-tokens.md
_source/_authentication-guide/tokens/validating-id-tokens.md
_source/_code/ios/index.md
_source/_docs/api/resources/social_authentication.md
_source/_docs/how-to/inbound-saml-with-oidc.md
_source/_standards/OIDC/index.md
_source/quickstart/nodejs/express-implicit.md
_source/quickstart/nodejs/generic-implicit.md
scripts/helpers.sh
scripts/post-build-lint.sh
scripts/travis.sh

- :bug: Fixes deep-linked URLs that do not append `.html` to the `index` file.
This resolves the `404` issue when viewing on the [staging site](https://d384qaxymvjmjw.cloudfront.net).
* [OKTA-147212](https://oktainc.atlassian.net/browse/OKTA-147212)

Fix urls that do not contain '.html'

---

_source/_assets/js/myOkta.js
_source/_plugins/ApiTags.rb

- :bug: Fixes the URL the hidden `iframe` was accessing
Not sure how this was passing before, but when trying to access the URL <https://login.okta.com/discovery/iframe.html>, we receive the following event data:
```
{
messageType: "iframe_loaded"
}
```
Updating the URL to point directly to <https://login.okta.com> correctly loads the user accounts, and returns the expected user JSON.

:bug: Fixes URL in iframe

---

_source/_authentication-guide/implementing-authentication/set-up-authz-server.md
_source/_code/php/jwt-validation.md
_source/quickstart/java/generic-implicit.md
_source/quickstart/nodejs/express-implicit.md
_source/quickstart/nodejs/generic-implicit.md
_source/quickstart/php/generic-auth-code.md

- Fix various instances where `https://{yourOktaDomain}.com` should have been used.

Fix misused 'yourOktaDomain' tags

---

_source/_assets/css/okta/pages/_quickstarts.scss
_source/_layouts/quickstart.html
tests/selenium/framework/page-objects/QuickStartsPage.js
tests/selenium/spec/quickstarts-spec.js

- Adds ride-side navigation to quickstarts
- Mocks: <https://okta.invisionapp.com/share/2FBI90NN7#/screens/240193150>
- Tests: Since the URL on the page isn't updating, it was difficult to expect a condition to resolve. Instead, we wait for specific elements to appear/disappear on the page.
* [OKTA-138596](https://oktainc.atlassian.net/browse/OKTA-138596)

:seedling: Adds navigation to quickstarts

---

_source/_assets/css/okta/pages/_quickstarts.scss
_source/_layouts/quickstart.html

- :bug: Fixes overwritten CSS on docs page
- :art: Minor style changes to make all quickstart icons appear in one line
What happened: Since our CSS files are loaded on every page, the altered `quickstart.css` page changed the `max-width` element across all elements who used `PageContent has-tableOfContents PageContent-main`.
Now, we only apply the change to elements containing the id: `quickstart-body`
* [OKTA-147799](https://oktainc.atlassian.net/browse/OKTA-147799)

:bug: Fixes parent CSS being overwritten

---

tests/selenium/spec/quickstarts-spec.js

- :memo: Adds a big note indicating which tests can not be removed/updated based on their dependency in the Okta product.
* [OKTA-144943](https://oktainc.atlassian.net/browse/OKTA-144943)

:memo: Adds big note on fixed tests

---

_config.yml
_source/_assets/css/okta/components/_BlogPost.scss

- :art: Fixes code block padding when nested inside of a `<li>`
- :bug: Fixes spelling mistake
* [Issue #1305](#1305)

:bug: Fixes padding in blog posts

---

_source/_includes/head.html
_source/_layouts/docs_page.html

- :bug: Fixes a bug where the GitHub edit link and page canonical link were checked by the `html-proofer` lib.

Blacklist specific links during html-proofer check

---

_source/_docs/api/resources/zones.md

- [Some context](https://oktainc.atlassian.net/browse/REQ-10190?focusedCommentId=529452&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-529452)
- Previously our docs for `/api/v1/zones` suggested that the API supported filtering by type. That is in fact not the case as we can only filter on ids
- updated the example to use filtering on ids, not type
- note that the curl request was already correct, just the description was wrong
- my only concern is that the line is very long so it wraps now. That being said it's important that we show filtering on a list of at least 2 ids because if it was just 1 id, they would actually use a different end point `/api/v1/zones/{ZONE_ID}`
* [OKTA-148100](https://oktainc.atlassian.net/browse/OKTA-148100)

Fix filter documentation for /api/v1/zones

---

tests/selenium/framework/page-objects/BlogPage.js

- Blog page spec is flaky sometimes when run locally
- This fixes the test by waiting for the presence of certain links

Fixing the flaky blog page spec test

---

_source/_docs/platform-release-notes/platform-release-notes.md
_source/_docs/platform-release-notes/platform-release-notes2017-46.md

- A colon in excerpt kills all CSS formatting. Missed this in two files
[OKTA-149555](https://oktainc.atlassian.net/browse/OKTA-149555)

hotfix for missing formatting

---

_source/quickstart/ios/default-example.md

- Removes snippet to manage the User's session, as the current implementation will always return `nil`
This 🐛 can be tracked [here](https://oktainc.atlassian.net/browse/OKTA-150370)

Updated iOS quickstart

---

_source/_assets/css/okta/components/_PageContent.scss
_source/_assets/css/okta/components/_Sidebar.scss

- Fixes the gap in the navbar.  Still investigating why this just showed up.
The Before:
And the after:

Fixed navbar gap

---

_source/_posts/2017-03-16-spring-boot-saml.md
_source/_posts/2017-03-27-angular-okta-sign-in-widget.md
_source/_posts/2017-03-30-react-okta-sign-in-widget.md
_source/_posts/2017-04-17-angular-authentication-with-oidc.md
_source/_posts/2017-06-13-add-authentication-angular-pwa.md
_source/_posts/2017-08-08-secure-spring-microservices.md
_source/_posts/2017-08-22-build-an-ionic-app-with-user-authentication.md
_source/_posts/2017-09-14-lazy-developers-guide-to-auth-with-vue.md
_source/_posts/2017-09-19-build-a-secure-notes-application-with-kotlin-typescript-and-okta.md
_source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md

Update blog posts to specify Default AS as issuer.
I also updated all the README's in each blog posts associated GitHub repo:
* https://github.com/oktadeveloper/okta-angular-sign-in-widget-example
* https://github.com/oktadeveloper/okta-angular-openid-connect-example
* https://github.com/oktadeveloper/okta-spring-boot-angular-pwa-example
* https://github.com/oktadeveloper/okta-ionic-auth-example
* https://github.com/oktadeveloper/okta-vue-auth-example
* https://github.com/oktadeveloper/spring-boot-microservices-example
* https://github.com/oktadeveloper/okta-spring-boot-2-angular-5-example
* https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example
* https://github.com/oktadeveloper/okta-spring-boot-saml-example
* https://github.com/oktadeveloper/okta-spring-boot-oauth-example …

Update blog posts to specify Default AS as issuer

---

_source/_code/dotnet/jwt-validation.md

Google is landing you on this .NET page if you search for "okta jwt".  As such, link to the primary guide to provide an alternative document.

Link from .NET JWT guide to main guide

---

_source/_authentication-guide/tokens/refreshing-tokens.md

- Fixing erroneous mention of client credentials grant type allowing refresh tokens.
#1570

Fixing typo

---

_source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md

Add type=button to prevent PUT after DELETE. Bug reported by René Winkler:
https://developer.okta.com/blog/2017/12/04/basic-crud-angular-and-spring-boot#comment-3674069159

Fix delete button in Angular CRUD post

---

_source/_docs/api/resources/system_log.md

- Support for using the keyword `"now"` to specify a polling query has been removed. As such, references to this keyword are removed from official documentation.
* [OKTA-152985](https://oktainc.atlassian.net/browse/OKTA-152985)

OKTA-152985: Remove References To until=now in System Log

---

_source/_docs/api/getting_started/design_principles.md

- Made changes to the link header section of the API docs to better describe how the Events API and Syslog2 polling cases never retire `next links`
* [OKTA-152985](https://oktainc.atlassian.net/browse/OKTA-152985)

OKTA-152985: Clarify End of Logs Next Link

---

_source/_standards/OIDC/index.md

- The url https://developer.okta.com/standards/ currently `404`s because there is no `index.html` file produced.
Added a `redirect_from` attribute to drop the visitor directly to the OIDC page.

:bug: Fixes 404 when accessing /standards/

---

_source/_docs/api/resources/users.md

- Password max length is doc'd as `40` but should be `72`.
* [OKTA-144636](https://oktainc.atlassian.net/browse/OKTA-144636)

Correct max length for password

---

_source/_docs/api/resources/system_log.md

- Clarified the geolocation section of the logs docs with examples and more precise descriptions of the various fields in the geolocation context object.
* [OKTA-154649](https://oktainc.atlassian.net/browse/OKTA-154649)

OKTA-154649: Detail Geocontext Section of SystemLog Docs

---

_source/feed-edgar.xml

This isn't needed for our Edgar feed. Keeping it in makes the feed to
large to be imported.
Is a super tiny fix, should be able to be merged without any impact. Thanks.

Removing the RSS description property.

---

_source/_posts/2015-04-07-android-unit-testing-part-2.md
_source/_posts/2015-04-14-android-unit-testing-part-3.md
_source/_posts/2015-04-23-android-unit-testing-part-4.md
_source/_posts/2017-05-10-developers-guide-to-docker-part-1.md
_source/_posts/2017-07-25-oidc-primer-part-2.md
_source/_posts/2017-08-01-oidc-primer-part-3.md
_source/_posts/2017-08-28-developers-guide-to-docker-part-2.md
_source/_posts/2017-09-08-nosql-options-for-java-developers.md
_source/_posts/2017-10-10-nosql-options-for-java-developers-part-ii.md
_source/_posts/2017-10-11-developers-guide-to-docker-part-3.md

It is common for people who are following our multi-part blog posts to attempt to navigate forward/backward via **part-X** in the URL. Since our pages are located in nested date directories, the common case produces a `404`:
1. User is on `developer.okta.com/blog/2017/08/01/oidc-primer-part-3`
2. Attempt to visit previous post: `developer.okta.com/blog/2017/08/01/oidc-primer-part-2`
3. User sees `404` page.
This PR adds redirects to each multi-part blog post to redirect to the correct page:
1. User is on `developer.okta.com/blog/2017/08/01/oidc-primer-part-3`
2. Attempt to visit previous post `developer.okta.com/blog/2017/08/01/oidc-primer-part-2`
3. User is redirected to `developer.okta.com/blog/2017/07/25/oidc-primer-part-2`

Adds redirects for common 404 pages

---

_source/_docs/how-to/creating-token-with-groups-claim.md

- POST should be PUT for step two (add the whitelist to your app profile)
- I tested and confirmed POST always returns a "HTTP method not supported" error, and PUT does work.
[OKTA-155553](https://oktainc.atlassian.net/browse/OKTA-155553)

change post to put

---

_source/_docs/api/resources/authn.md

- Now that we have https://developer.okta.com/docs/api/getting_started/rate-limits, it's best to eliminate outdated RL references from endpoint doc. 
[OKTA-155770](https://oktainc.atlassian.net/browse/OKTA-155770)

remove old RL info from authn endpoint doc

---

scripts/gh-pages-publish.sh

Reverts okta/okta.github.io#1664
- As noted in #1664, since we cannot remove previously generated `/dist` files/folders, we are working around it. This removes the logic to remove error files, as it will no longer serve a purpose.

:fire: Remove dead file

---

_source/quickstart-fragments/angular/default-example.md
_source/quickstart-fragments/vue/default-example.md

- Fix code blocks in documentation omitting variables surrounded by `{{ }}`

:bug: Fix code snippets not showing variables surrounded by {{ }}

---

scripts/helpers.sh
scripts/htmlproofer.rb
scripts/post-build-lint.sh
scripts/publish.sh
scripts/setup.sh
scripts/travis.sh

- ✅ Adds lint tests to `publish.sh` script after removing `.html` extensions on files.
- When the `publish.sh` script is run on merges into `weekly` and `source`, we deploy the `dist` output to S3.
- `weekly`: https://developer.trexcloud.com
- `source`: https://dq3iyfxeowfmd.cloudfront.net/
Bacon commit with passing tests (alerted order of when branch verification is processed): [2a759](http://bacon.aue1e.internal/#!/commits/okta.github.io/sha/2a759ea9958f7437a041a1212bd52486c26089c2).

:white_check_mark: Update publish script to include lint checks

---

_source/_docs/api/resources/factor_admin.md

- Fix description of retrieving org factors
- See [the confusing line here](https://developer.okta.com/docs/api/resources/factor_admin#get-org-factor)
* [Issue #1687](#1687 )

:bug: Fix description of retrieving org factors

---

_source/_assets/css/okta/components/_BlogPost.scss
_source/_assets/css/okta/components/_PageContent.scss

Contributes to fixing #1694. Screenshot below.
This is what it looks like before this change:

Change blockquote so it matches doc CSS

---

_source/_docs/api/getting_started/api_test_client.md
_source/_docs/api/resources/oauth-clients.md

Client Registration needed a scrub!
- Multiple, outdated postman buttons and getting started text that's no longer needed.
- Remove outdated EA tags.
[OKTA-158179](https://oktainc.atlassian.net/browse/OKTA-158179)
tested locally and made sure postman buttons point to the correct collection.

remove old ea tags and outdated getting started section and fix postman buttons

---

scripts/publish.sh

This script copies over the old version of the site verbatim, but we do have image cachebusting and caching in cloudfront now so this may no longer be necessary
This change will oly affect our source staging site, this will not affect the production deploy to Github pages

Remove post-build-prod step from S3 deploy

---

_source/_authentication-guide/implementing-authentication/auth-code.md
_source/_change-log/2017-11.md
_source/_code/php/index.md

- Remove links for Symfony  ~~and Slim~~(there are no slim references) from the docs as they are soon to be replaced.

Removes Symfony sample app links

---

_source/_docs/api/resources/users.md

- List Users with a Filter does return deprovisioned users, so removing the note from doc.
[OKTA-151641](https://oktainc.atlassian.net/browse/OKTA-151641)

remove incorrect note from list users with a filter

---

_source/_posts/2018-02-15-build-crud-app-vuejs-node.md

- After publish I noticed that the first mention of Epilogue was misspelled 'Epiloge'
- I also noticed that the link for ExpressJS was linking to express.com. Should be expressjs.com

Small fixes

---

_source/_docs/api/resources/users.md

- Doc support for salted SHA-256 algorithm for password import 
* [OKTA-158149](https://oktainc.atlassian.net/browse/OKTA-158149)
- @mystiberry-okta 
- @srinivasanagandla-okta 
- @edjohns-okta

 Doc support for salted SHA-256 algorithm for password import 

---

_source/_posts/2017-08-23-five-java-tips.md
_source/_posts/2017-09-19-build-a-secure-notes-application-with-kotlin-typescript-and-okta.md
_source/_posts/2018-03-06-okta-open-source-samples-and-quickstarts.md
scripts/htmlproofer.rb

- Fixes the html-proofer to ignore quickstart links that contain `#`. This is required because the `html-proofer` library expects any URL containing a slash `/` to be a path or file (not a partial)
This PR is broken into the following commits:
1.  🐛 fix
2.  Updates broken links failing the `html-proofer`
3. Introduces a broken link to be caught by Travis
4. Reverts the introduced link for a clean build

:bug: Fix quickstart html-proofer

---

_source/_change-log/2018-10.md

- A bug related to X-Forwarded-For header was in IT products RN, should be in API products change log. Verified by team and several others.
[OKTA-159414](https://oktainc.atlassian.net/browse/OKTA-159414)

Misplaced bug for RN

---

_source/_docs/api/getting_started/rate-limits.md

This fixes an issue with a redirect URL that was messed up because it included a URI fragment. By removing the fragment we preserve the redirect functionality but we don't generate invalid filenames that will be hard for scripts to parse/modify.

Removing URI fragment from `redirect_from` frontmatter

---

_source/_includes/blog_post.html

Comments don't render when there are single quotes in the title. This fixes the issue.

Allow blog post titles to have a single quote

---

_source/_posts/2017-08-22-build-an-ionic-app-with-user-authentication.md

- Ionic Cloud Auth is no more, their doc links don't work, so I removed the link. I also compulsively fixed a missing word.

removing broken links

---

_source/quickstart-fragments/dotnet/aspnet4-auth-code.md

Updates to the ASP.NET 4.x auth code quickstart to reflect the updated example.
Supersedes PR #1883 
Closes #1881

Update dotnet auth code quickstart to OWIN 4.0 libs

---

_source/_code/dotnet/jwt-validation.md

Fixes #1780. Specific fix here (line 133): https://github.com/okta/okta.github.io/compare/1780-fix-dotnet-validation-instructions?expand=1#diff-074effc5fbc657560c2beb988d711e38R133

Update .NET JWT validation guide

---

_source/quickstart-fragments/dotnet/aspnet4-auth-code.md

Add an additional step to configure the ServicePointManager when using TLS 1.2 and .NET <4.6.
* #1917

Add a step to configure ServicePointManager for TLS 1.2 & .NET <4.6

---

_source/_assets/css/okta/base/_variables.scss
_source/_assets/css/okta/components/_Blog.scss
_source/_assets/css/okta/components/_BlogPost.scss
_source/_assets/css/okta/components/_Button.scss
_source/_assets/css/okta/components/_DocsPage.scss
_source/_assets/css/okta/components/_PageContent.scss
_source/_assets/css/okta/components/_ProductSection.scss
_source/_assets/css/okta/components/_Swiftype.scss
_source/_assets/css/okta/components/_misc.scss
_source/_assets/css/okta/pages/_code.scss
_source/_assets/css/okta/pages/_product.scss
_source/_assets/css/okta/pages/_quickstarts.scss

- Sweeps current sass files and replaces hex values with named variables.
- In `_source/_assets/css/okta/pages/_quickstarts.scss`, removes a declaration that is no longer used.
There should be no visual or user-facing changes, and I've sanity-checked to QA as much as I can.
Does not touch legacy files for safety. After this change, we should no longer need to introduce one-off or hard-coded color values.
Color names are programmatically generated and are universally unique with our design system. cc @edburyenegren-okta 
* [UX-1083](https://oktainc.atlassian.net/browse/UX-1083)

Replace CSS color values with variables

---

_source/_docs/api/resources/oauth-clients.md

- There was an extra client secret in one example. Now there's not.
[OKTA-166384](https://oktainc.atlassian.net/browse/OKTA-166384)

remove repeated line from oauth-client doc

---

_source/_posts/2018-02-15-build-crud-app-vuejs-node.md

Updates "[Build a Basic CRUD App with Vue.js and Node](https://developer.okta.com/blog/2018/02/15/build-crud-app-vuejs-node)" for the latest version of libraries (including @okta/okta-vue 1.0) and locks down dependencies.

Update Vue + Node CRUD post for Okta Vue 1.0.0

---

_source/_posts/2018-02-20-9-talks-i-cant-wait-to-see-at-iterate.md

- link to youtube channel oktadev changed, apparently.
blog post, no JIRA.

fix broken link to okta for devs

---

_source/_docs/api/resources/oidc.md

- Document ID tokens from refresh requests
- The response table for /token now matches other APIs and just lists the possible values. rt and id_token inclusion is now completely dependent on scope.
* [OKTA-136495](https://oktainc.atlassian.net/browse/OKTA-136495)
@mystiberry-okta @danielzeller-okta

Document ID tokens from refresh requests

---

_source/_docs/api/resources/users.md

- Credentials was incorrectly listed as part of credentials object. Fixed it. Tested that "credentials" isn't returned in the results it was removed from using Postman collection.
[OKTA-164555](https://oktainc.atlassian.net/browse/OKTA-164555)

fix credentials object

---

_source/_posts/2017-03-27-angular-okta-sign-in-widget.md
_source/_posts/2017-04-17-angular-authentication-with-oidc.md
_source/_posts/2017-09-19-build-a-secure-notes-application-with-kotlin-typescript-and-okta.md

It's likely that tutorials don't work with v6, so prevent users from installing it.

Lock down Angular CLI version since v6 has been released

---

_source/_docs/api/getting_started/rate-limits.md

- Clarified that the exceptions to a general rate limit are for the listed URL only, not extensions of it.
[OKTA-165417](https://oktainc.atlassian.net/browse/OKTA-165417)

Clarify rate limits for special "id" or "login" per minute limits

---

_source/_posts/2017-05-09-progressive-web-applications-with-angular-and-spring-boot.md
_source/_posts/2017-09-19-build-a-secure-notes-application-with-kotlin-typescript-and-okta.md
_source/_posts/2017-12-04-basic-crud-angular-and-spring-boot.md

Without versions, people will get Angular Material 6 + doom and gloom.

Specify version for Angular Material so tutorials work

---

_source/_posts/2017-08-08-secure-spring-microservices.md

This PR updates [Secure a Spring Microservices Architecture with Spring Security, JWTs, Juiser, and Okta](https://developer.okta.com/blog/2017/08/08/secure-spring-microservices) to pin the starting point to [v1.0](https://github.com/oktadeveloper/spring-boot-microservices-example/releases/tag/v1.0) of the spring-boot-microservices-example repo, which uses Spring Boot 1.5.10.
This is necessary because the Stormpath Zuul Starter and Juiser do not work with Spring Boot 2.0. However, it is possible to update the [preceding tutorial](https://developer.okta.com/blog/2017/06/15/build-microservices-architecture-spring-boot) and the [OAuth version](https://developer.okta.com/blog/2018/02/13/secure-spring-microservices-with-oauth) to use Spring Boot 2.0.

Change initial clone command to v1.0 tag on repo

---

_source/quickstart-fragments/php/generic-implicit.md

- Moves the `setClientId` method into the main `$jwtVerifier` constructor to match the [`README`](https://github.com/okta/okta-jwt-verifier-php#usage)
* [OKTA-172033](https://oktainc.atlassian.net/browse/OKTA-172033)

Updates PHP quickstart

---

_source/_docs/api/getting_started/rate-limits.md
_source/_docs/api/resources/system_log.md

- Update rate limits for Enterprise orgs, and add limits for Developer (free), Developer (paid), and One App orgs.
- Some limits are now the same, and don't need to be printed separately. Those rows have been removed.
- Clean up minor bugs in text.
[OKTA-169183](https://oktainc.atlassian.net/browse/OKTA-169183)

Update rate limit documentation

---

_source/_posts/2017-03-21-spring-boot-oauth.md

Updates "[Get Started with Spring Boot, OAuth 2.0, and Okta](https://developer.okta.com/blog/2017/03/21/spring-boot-oauth)" to use Spring Boot 2.0.

Upgrade OAuth blog post to use Spring Boot 2.0

---

_source/_docs/api/resources/policy.md

Related to OKTA-173191
Bacon: test
- Remove the support for ON_NETWORK and OFF_NETWORK in policy API.
NOTE: npm start fails locally and could not build the local version of the site. Will investigate that before merging this in.
* [OKTA-173191](https://oktainc.atlassian.net/browse/OKTA-173191)
@jakubvul @eklein-okta @dannavarro-okta @richardblaylock-okta please review

Changes to remove the references to ON_NETWORK and OFF_NETWORK

---

_source/_docs/api/resources/users.md

Login names no longer need to be email addresses.  More details are on the schemas page, so here I just linked to the new Validation section there, and updated the section on "short name" logins to reflect new behavior.
- Changed table re login Validation to link to the section on the Schemas page.
- Updated the section discussing short-name logins.
- Updated the section re what can be changed in the base properties.  Note that changing permissions had not previously been added to that section.
* [OKTA-164984](https://oktainc.atlassian.net/browse/OKTA-164984)

Update users.md for new login pattern validation

---

_source/_docs/api/resources/authn.md

- U2F has already been GA'ed.
- Missed removing the EA label from the Authn docs.
* [OKTA-179206](https://oktainc.atlassian.net/browse/OKTA-176206)

remove EA flag from Authn API docs

---

scripts/setup.sh

- Adds yarn to the $PATH to fix `/root/okta/okta.github.io/scripts/publish.sh: line 82: ci-update-package: command not found` error
* [OKTA-182540](https://oktainc.atlassian.net/browse/OKTA-182540)
Primary reviewers:
@jmelberg-okta 
@bdemers 
Addition reviewers:
@rchild-okta

Adding yarn to the PATH to fix publish.sh

---

_source/_posts/2018-07-30-10-ways-to-secure-spring-boot.md

Links seem to work when using a desktop browser, but not on mobile Safari.

Fix Okta Signup and Playground links in Secure Spring Boot post

---

_source/_docs/api/resources/oidc.md
_source/_docs/api/resources/policy.md
_source/_docs/api/resources/users.md
_source/_reference/postman_collections/index.md

Policy API reference
* Add links to the Postman collection for the Policy API 
OIDC reference
* Clean up for formatting and accuracy
* Update logout endpoint to reflect changes in OKTA-180521: expired or no Okta session results in a redirect, not a JSON error. Invalid ID tokens result in an error page redirect.
User API reference
* Minor cleanup of formatting/typos
* Clarify that links returned on the User object may vary depending on your policies
- [OKTA-180521](https://oktainc.atlassian.net/browse/OKTA-180521)

Nate's basket of documentation fixes no. 3

---

_source/_docs/api/resources/system_log.md

System Log API: delineate polling vs. bounded requests.
[OKTA-141156](https://oktainc.atlassian.net/browse/OKTA-141156)
/cc @analytics-okta

System Log API: delineate polling vs. bounded requests

---

_source/_docs/api/resources/system_log.md

System Log API: 
- Move `authenticationContext.externalSessionId` and `transaction.id` descriptions to "Event Correlation" section.
- Clarify descriptions.
- Simplify example verbiage.
- Replace proper nouns in Event Correlation Example table headers with JSON field paths.
* [OKTA-177766](https://oktainc.atlassian.net/browse/OKTA-177766)
/cc @analytics-okta

System Log API: improve sessionId and tx.id info

---

_source/_docs/api/resources/authn.md

- Cron job that checks for external links has been failing
- The error seems to be related to an external link
- Ignoring this link should fix the error 

Fixes cron job by ignoring html-proofer for external link

---

_source/_docs/api/resources/users.md

- Document limit of 20 groups for user creation.
- Also took the opportunity to fix a minor typo elsewhere.
* [Issue #184773](#184773)
* [OKTA-184773](https://oktainc.atlassian.net/browse/OKTA-184773)

Document limit of 20 groups for user creation

---

_source/_docs/api/resources/policy.md

- Policy API: Correcting name of type value
One of the values that the 'type' attribute of the Rules object can be set to is SIGN_ON, but the documentation previously gave the value as OKTA_SIGN_ON.
(Note that, confusingly, the Policy object does have 'OKTA_SIGN_ON' as one the values that its 'type' attribute can be set to.)
As a a side issue, I have removed a sentence that said you need to supply Policy ID as a required parameter when calling the  ‘Create a Policy’ API. This didn't makes sense: a Policy you are just creating would not have an ID yet.
* [OKTA-190429] (https://oktainc.atlassian.net/browse/OKTA-190429)

[OKTA-190429] Policy API: Correcting name of type value

---

_source/_posts/2018-09-27-build-a-simple-api-service-with-express-and-graphql.md

- This puts a little blurb earlier in the blog letting people know
where to find the sample code on github, in case they want to
skip ahead to the final product. The github README still walks
the user through creating their Okta account and setting up the
variables they need to get the app up and running properly
* https://github.com/oktadeveloper/okta-express-graphql-example/issues/2#issuecomment-431657877

graphql-express: add link to sample code earlier

---

_source/_standards/SCIM/SCIMFiles/Okta-SCIM-11-SPEC-Test.json

Updated test plan according to OKTA-192001
- These two tests in SCIM 1.1 Spec Test Suite (https://developer.okta.com/standards/SCIM/SCIMFiles/Okta-SCIM-11-SPEC-Test.json) do not set the Content-Type Header which causes the customer's SCIM application to fail.
1. 'Required Test: Create Okta user with realisitic values'
2. 'Required Test: Expect failure when recreating user with same values'
SCIM 1.1 specs (http://www.simplecloud.info/specs/draft-scim-api-01.html#create-resource) shows examples of POST request where Content-Type header is set.
* [OKTA-192001](https://oktainc.atlassian.net/browse/OKTA-192001)
@balathiruvalluvan-okta 
@ivanvoloshyn-okta

ai_OKTA-192001_Update_SCIM_1.1_Spec_Test_Suite

---

_source/_standards/SCIM/SCIMFiles/Okta-SCIM-11-SPEC-Test.json

These two tests in SCIM 1.1 Spec Test Suite (https://developer.okta.com/standards/SCIM/SCIMFiles/Okta-SCIM-11-SPEC-Test.json) do not set the Content-Type Header which causes the customer's SCIM application to fail.
1. 'Required Test: Create Okta user with realisitic values'
2. 'Required Test: Expect failure when recreating user with same values'
SCIM 1.1 specs (http://www.simplecloud.info/specs/draft-scim-api-01.html#create-resource) shows examples of POST request where Content-Type header is set.
* [OKTA-192001](https://oktainc.atlassian.net/browse/OKTA-192001)
@ivanvoloshyn-okta 
@balathiruvalluvan-okta

Updated OKTA Scim 1.1 Spec Test Plan according to OKTA-192001

---

_source/_docs/api/resources/oidc.md

- For clarity, changing the description of the state property, as used in the postMessage() data model. New description: The unmodified `state` value from the request.  
* [OKTA-159463](https://oktainc.atlassian.net/browse/OKTA-159463)

[OKTA-159463] Changing description of state property in postMessage Data Model

---

_source/_docs/api/resources/factors.md

- Fixing typo in Call Factor enrollment doc.
* First part of #2482

Fixing copypasta typo

---

_source/_docs/api/resources/oidc.md

Updated doc to reflect changes for OKTA-114737.
- Updated /.well-known/oauth-authorization-server metadata response to include OIDC response types.
* [OKTA-114737](https://oktainc.atlassian.net/browse/OKTA-114737)
* [PR-30893](https://github.com/okta/okta-core/pull/30893)

Updated documentation for /.well-known/oauth-authorization-server (OKTA-114737)

---

_source/_change-log/2018-49.md

TODO: we need to add a note to this page about the version change so it doesn't look as odd that we have two 2018.12's
the current 2018.12.0 and the original 2018.12

Update version scheme 2018.49 -> 2018.12.0

---

_source/_code/python/pysaml2.md

Changes the variables in frontmatter to normal markdown info  Resolves #2542

fixes python PySAML2 Example

---

_source/_docs/api/resources/events.md
_source/_includes/sidebar.html
_source/_reference/index.html

Removes links to the (deprecated) Events API docs from the API Reference index sidebar.
* [OKTA-198911](https://oktainc.atlassian.net/browse/OKTA-198911)
/cc @okta/analytics

Remove links to Events API docs

---

scripts/find-missing-slashes.js

when you create a string with a backslash `'\s'` ,it changes it to `'s'`. i assume the intention was to have a regex with `/\s/`, so you need to start with a string  with an escaped backslash: `'\\s'`

fix regexp

---

.travis.yml

Bundler 2.0 causing issues for us. 
- https://travis-ci.community/t/bundle-is-not-installed-for-ruby-2-3/1641/6
- https://status.rubygems.org/incidents/dh3cd8fjd5qw

Adds version lock for bundler

---

_source/_docs/api/getting_started/rate-limits.md

- Update to O365 wsfed endpoint rate limit.
- This should go out with the 2019.1.0 update (and be announced in the API change log), though check with @bridgetwent-okta first.
* [OKTA-201807](https://oktainc.atlassian.net/browse/OKTA-201807)

Updating O365 Rate Limit

---

_source/_assets/js/myOkta.js

Orgs created in production infrastructure are currently ignored by this script. This fix makes the script work with all orgs.
This is crucial for our onboarding, since we are moving new orgs to production infra (by default), new users are not currently seeing their org URLs populated automatically in the documentation.

Update org discovery script to remove oktapreview whitelist

---

_source/_change-log/2019-02-0.md
_source/_data/event-types.json

Apostrophe character used in event log descriptions causing Travis errors.

Fix event types illegal apostrophe

---

_source/_use_cases/inline_hooks/api_am_hook/api_am_hook.md
_source/_use_cases/inline_hooks/index.md

Changing the name of the hook to Token Inline Hook. Previously, the docs pages called it the API Access Management Inline Hook.

Changing the name of the inline hook

---

_source/_change-log/2019-02-0.md

Name of the hook was changed after release. This is to change the name used in the change log.

Name Change of API AM Inline Hook to Token Inline Hook in RN

---

_source/_use_cases/events-api-migration/index.md

- Fixing typos on page. Specifically: instances of "the Logs API" and trailing whitespace.

Changing Logs API to System Log API

---

_source/_docs/api/resources/users.md

Removing EA reference from the doc
Resolves: OKTA-212554
Bacon : test
Release : 2019.03.0
* [OKTA-212554](https://oktainc.atlassian.net/browse/OKTA-212554)

OKTA-212554: update API doc to remove EA reference for user search support

---

_source/_docs/api/resources/roles.md

- Create API Docs for new Role-To-Group assignment APIs
- Fix some gaps in the existing individual role assignment APIs
- Re-structure the Role Assignment section to address both user and group assignments in parallel
- Monolith PR: https://github.com/okta/okta-core/pull/32731
(This depends on https://github.com/okta/okta.github.io/pull/2704)
* I understand we have to wait until FF is GAed before publishing these
(Screenshot: https://okta.box.com/s/yuymwkgvkrsamyyk9p63g9dzqil01rcc)
* [OKTA-207769](https://oktainc.atlassian.net/browse/OKTA-207769)
cc: @okta/flm @rchild-okta

Create API Docs for new Role-To-Group assignment APIs

---

_source/_docs/api/resources/users.md

- Update Create/Update User API documentation to include missing details about the recently supported SHA-1, MD-5 hashes.
- Relevant code changes in Monolith build/release version : 2019.03.0
- Follow-up PR to fix gaps from previous PR : https://github.com/okta/okta.github.io/pull/2755/
* [OKTA-213417](https://oktainc.atlassian.net/browse/OKTA-213417)

OKTA-213417 : Update Create/Update User API documentation to include missing details about the recently supported SHA-1, MD-5 hashes.

---

_source/_docs/api/resources/roles.md

- Fix a Role-To-Group endpoint doc pointing to users instead
- Is this PR related to a Monolith release? Yes, 2019.03.0
* [OKTA-213746](https://oktainc.atlassian.net/browse/OKTA-213746)

Fix a Role-To-Group endpoint doc pointing to users instead

---

_source/_posts/2018-03-16-build-react-native-authentication-oauth-2.md

Fixes issue in [Build a React Native Application and Authenticate with OAuth 2.0](https://developer.okta.com/blog/2018/03/16/build-react-native-authentication-oauth-2).
Reported by [Juan De la Cruz](http://disq.us/p/21ij6uz).

Fix paths to Formidable Labs' GitHub repo

---

_source/_data/authors.yml

Updated the twitter handles on contractor author details to reflect the Oktadev twitter account.

Update Social Media Handles on Contractors

---

.github/workflows/branch-cleanup.yml

Apparently, GitHub doesn't fire off events for the 'pull_request' type
when a PR is merged.
This will hopefully get the auto-delete-branches workflow working.

Changing the event that 'triggers' the workflow.
